### ISSUE TITLE
StockAvailable - setQuantity - Duplicate data on key : product_sqlstock

### ISSUE THREAD

**Issue by thalassa-web** [PrestaShop/PrestaShop#11806]
**Describe the bug**
Received product data from specific webservice, I tried to update product stock with the "StockAvailable::setQuantity" method, and I obtain SQL error :
Duplicata du champ '31-0-0-0' pour la clef 'product_sqlstock'. From DbCore->insert() Query was : INSERT INTO `ps_stock_available` (`id_product`, `id_product_attribute`, `id_shop`, `id_shop_group`, `quantity`, `depends_on_stock`, `out_of_stock`) VALUES ('31', '0', '0', '0', '0', '0', '0')

**To Reproduce**
1. Create a product by webservice
2. Define the product stock for a specific shop by calling "StockAvailable::setQuantity" with the product id a quantity and a specific shop id.
3. Why quantity is 0 and id_shop is 0 in the sql insert ? 

**Screenshots**
Here we are the stack trace :
```
ERROR - [2018-12-18 14:14:33][SQL Error] Duplicata du champ '31-0-0-0' pour la clef 'product_sqlstock'. From DbCore->insert() Query was : INSERT INTO `ps_stock_available` (`id_product`, `id_product_attribute`, `id_shop`, `id_shop_group`, `quantity`, `depends_on_stock`, `out_of_stock`) VALUES ('31', '0', '0', '0', '0', '0', '0')
ERROR - [2018-12-18 14:14:33]#0 /home/www/comparez-vous-memes/www/classes/db/Db.php(743): WebserviceRequest->setError(500, '[SQL Error] Dup...', 97)
#1 /home/www/comparez-vous-memes/www/classes/db/Db.php(378): DbCore->displayError('INSERT INTO `ps...')
#2 /home/www/comparez-vous-memes/www/classes/db/Db.php(718): DbCore->query('INSERT INTO `ps...')
#3 /home/www/comparez-vous-memes/www/classes/db/Db.php(467): DbCore->q('INSERT INTO `ps...', true)
#4 /home/www/comparez-vous-memes/www/classes/ObjectModel.php(529): DbCore->insert('ps_stock_availa...', Array, false)
#5 /home/www/comparez-vous-memes/www/classes/stock/StockAvailable.php(397): ObjectModelCore->add(true, false)
#6 /home/www/comparez-vous-memes/www/src/Adapter/StockManager.php(75): StockAvailableCore->add()
#7 /home/www/comparez-vous-memes/www/src/Core/Stock/StockManager.php(380): PrestaShop\PrestaShop\Adapter\StockManager->getStockAvailableByProduct(Object(Product), 0)
#8 /home/www/comparez-vous-memes/www/src/Core/Stock/StockManager.php(349): PrestaShop\PrestaShop\Core\Stock\StockManager->prepareMovement(31, 0, 2, Array)
#9 /home/www/comparez-vous-memes/www/classes/stock/StockAvailable.php(518): PrestaShop\PrestaShop\Core\Stock\StockManager->saveMovement(31, 0, 2)
#10 /home/www/comparez-vous-memes/www/override/classes/stock/StockAvailable.php(59): StockAvailableCore::setQuantity(31, 0, 2, 1)
#11 /home/www/comparez-vous-memes/www/modules/xlpos/lib/classes/article/prestashop/Article.php(641): StockAvailable::setQuantityIfChanged(31, 0, 2, 1)
#12 /home/www/comparez-vous-memes/www/modules/xlpos/lib/classes/article/prestashop/Article.php(587): xlpos\lib\classes\article\prestashop\Article->gererStockStandard(Object(xlpos\lib\classes\article\Article), Object(xlpos\lib\classes\boutique\Boutique))
#13 /home/www/comparez-vous-memes/www/modules/xlpos/lib/classes/article/prestashop/Article.php(217): xlpos\lib\classes\article\prestashop\Article->gererStock(Object(xlpos\lib\classes\article\Article), Object(Product), Object(xlpos\lib\classes\boutique\Boutique))
#14 /home/www/comparez-vous-memes/www/modules/xlpos/lib/classes/article/prestashop/Article.php(164): xlpos\lib\classes\article\prestashop\Article->importerPourUneBoutique(Object(xlpos\lib\classes\article\Article), Object(xlpos\lib\classes\boutique\Boutique))
#15 /home/www/comparez-vous-memes/www/modules/xlpos/lib/classes/article/Article.php(944): xlpos\lib\classes\article\prestashop\Article->importer(Object(xlpos\lib\classes\article\Article), Array)
#16 /home/www/comparez-vous-memes/www/modules/xlpos/lib/classes/article/Article.php(702): xlpos\lib\classes\article\Article->envoyerVersEboutique(Object(stdClass))
#17 /home/www/comparez-vous-memes/www/modules/xlpos/lib/classes/article/Article.php(456): xlpos\lib\classes\article\Article->remplirEtEnregistrer(Object(stdClass))
#18 /home/www/comparez-vous-memes/www/modules/xlpos/lib/classes/abstraites/ClasseTable.php(700): xlpos\lib\classes\article\Article->importer(Object(stdClass))
#19 /home/www/comparez-vous-memes/www/modules/xlpos/lib/classes/article/Article.php(420): xlpos\lib\classes\abstraites\ClasseTable->importerLigne(Object(stdClass), true)
#20 /home/www/comparez-vous-memes/www/modules/xlpos/lib/service/ImporterArticles.php(48): xlpos\lib\classes\article\Article::importerListe(Array)
#21 /home/www/comparez-vous-memes/www/modules/xlpos/lib/service/Service.php(81): xlpos\lib\service\ImporterArticles->executerAction()
#22 /home/www/comparez-vous-memes/www/modules/xlpos/lib/service/ActionDispatcher.php(70): xlpos\lib\service\Service->executer(Object(stdClass))
#23 /home/www/comparez-vous-memes/www/override/classes/XlposAction.php(234): xlpos\lib\service\ActionDispatcher::executerAction('ImporterArticle...', Object(stdClass))
#24 /home/www/comparez-vous-memes/www/override/classes/XlposAction.php(285): XlposAction->runService('{"articles":[{"...')
#25 /home/www/comparez-vous-memes/www/classes/webservice/WebserviceRequest.php(1482): XlposAction->add()
#26 /home/www/comparez-vous-memes/www/classes/webservice/WebserviceRequest.php(1296): WebserviceRequestCore->saveEntityFromXml(201)
#27 /home/www/comparez-vous-memes/www/classes/webservice/WebserviceRequest.php(526): WebserviceRequestCore->executeEntityPost()
#28 /home/www/comparez-vous-memes/www/webservice/dispatcher.php(87): WebserviceRequestCore->fetch('W4T485SIP3WAXFO...', 'POST', 'xlpos_action', Array, false, '<?xml version="...')
#29 {main}
```

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1.25-1+ubuntu16.04.1+deb.sury.org+1

**Comment by khouloudbelguith** [comment]
Hi @tii-bruno,

Thanks for your report.
How did you call "StockAvailable::setQuantity", with a custom script?
If yes, thanks to providing us this script to test it.
Thanks!

**Comment by thalassa-web** [comment]
I override the class StockAvailable to add a method :
```php
class StockAvailable extends StockAvailableCore
{
    /**
     * Set the quantity only if it changed
     * It is useful if a module listen the hook "actionUpdateQuantity" which is useful only if the quantity evolve
     * For example, the module mail alerts send an email when a product has less (or equal) quantity tha a value.
     * If the stock is less (or equal) of this value, doesn't evolve, and set quantity is called, an email will be send
     * it is quite annoying …
     * @param int $id_product
     * @param int $id_product_attribute
     * @param int $quantity
     * @param null|int $id_shop
     * @return boolean The stock has been modified
     */
    public static function setQuantityIfChanged($id_product, $id_product_attribute, $quantity, $id_shop = null)
    {
        //#12069
        $actualQty = static::getQuantityAvailableByProduct($id_product, $id_product_attribute, $id_shop);
        \xlpos\lib\utils\HLog::log("STOCK PRODUCT #{$id_product}[#$id_product_attribute] - ACTUAL : $actualQty / NEW : $quantity");
        if ($quantity === $actualQty) {
            return false;
        }
        \xlpos\lib\utils\HLog::log("STOCK PRODUCT #{$id_product}[#$id_product_attribute] UPDATED");
        static::setQuantity($id_product, $id_product_attribute, $quantity, $id_shop);
        return true;
    }
}
```
I call it like this :
```php
StockAvailable::setQuantityIfChanged(product_id, 0, $quantite, $shop_id);
```

**Comment by khouloudbelguith** [comment]
Hi @tii-bruno,

Thanks for your feedback.
When I tried with your override, I have exceptions when I update the quantity.
![image](https://user-images.githubusercontent.com/16067358/50213071-dc65d500-037c-11e9-842c-cea3844b2c5f.png)
Thanks to check & feedback.

**Comment by thalassa-web** [comment]
Yes of course you have …
I did not clean my code up …
Here you have the cleaned up class :
```php
class StockAvailable extends StockAvailableCore
{
    /**
     * Set the quantity only if it changed
     * It is useful if a module listen the hook "actionUpdateQuantity" which is useful only if the quantity evolve
     * For example, the module mail alerts send an email when a product has less (or equal) quantity tha a value.
     * If the stock is less (or equal) of this value, doesn't evolve, and set quantity is called, an email will be send
     * it is quite annoying …
     * @param int $id_product
     * @param int $id_product_attribute
     * @param int $quantity
     * @param null|int $id_shop
     * @return boolean The stock has been modified
     */
    public static function setQuantityIfChanged($id_product, $id_product_attribute, $quantity, $id_shop = null)
    {
        //#12069
        $actualQty = static::getQuantityAvailableByProduct($id_product, $id_product_attribute, $id_shop);
        if ($quantity === $actualQty) {
            return false;
        }
        static::setQuantity($id_product, $id_product_attribute, $quantity, $id_shop);
        return true;
    }
}
```

**Comment by khouloudbelguith** [comment]
Hi @tii-bruno,

Thanks for your feedback.
Now the override works, but there is no exception `Duplicata du champ '31-0-0-0' pour la clef 'product_sqlstock` displayed.
I attached a video record.
https://drive.google.com/file/d/1tApgYVlpExb48QPHeJZJpe9PnRYCV5qB/view
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @thalassa-web,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by jul-m** [comment]
Hello,

I encountered the same problem. This comes from the line "StockAvailable::getStockAvailableIdByProductId($id_product, $id_product_attribute, $id_shop);". I am using the version 1.7.6.1 of Prestashop.

If the product does not exist in the "ps_stock_available" table, the "getStockAvailableByProduct" function in the "src/Adapter/StockManager" class creates the record. However, even when the command is called by the function "checkProductStock" of the base class Prestashop "OrderDetail", the problem occurs (tested on a blank Prestashop installation).

What happens if the product does not exist in the table "ps_stock_available" and there is not the argument "id_shop" filled in :
-> function "StockManager->getStockAvailableByProduct()" created the record for this product in DB with id_shop = 0.
-> When the product is reordered, the "StockManager->getStockAvailableByProduct()" function searches the stock for this product again, but determines the store id to the "classes\StockAvailable\addSqlShopRestriction )" function. So we have a "WHERE id_shop = 1" for example. It does not find the record already created with "id_shop = 0". It retents to record the same thing in DB, with id_shop = 0, and suddenly we have a duplicate.

Rather than modifying all the classes that call the StockManager-> getStockAvailableByProduct() function to add the shop id as an argument, I changed the function as follows:

```
    public function getStockAvailableByProduct($product, $id_product_attribute = null, $id_shop = null)
    {
        $stockAvailable = $this->newStockAvailable($this->getStockAvailableIdByProductId($product->id, $id_product_attribute, $id_shop));

        if (!$stockAvailable->id)
        {
            $shopAdapter = new ShopAdapter();
            $stockAvailable->id_product = (int) $product->id;
            $stockAvailable->id_product_attribute = (int) $id_product_attribute;

            $outOfStock = $this->outOfStock((int) $product->id, $id_shop);
            $stockAvailable->out_of_stock = (int) $outOfStock;

            if ($id_shop === null)
            {
                $shop_group = $shopAdapter->getContextShopGroup();
            }
            else
            {
                $shop_group = $shopAdapter->ShopGroup((int) $shopAdapter->getGroupFromShop((int) $id_shop));
            }

            // if quantities are shared between shops of the group
            if ($shop_group->share_stock)
            {
                $stockAvailable->id_shop = 0;
                $stockAvailable->id_shop_group = (int) $shop_group->id;
            }
            else
            {
                // ADD FIX BUG duplicate product_sqlstock
                if ($id_shop === null)
                {
                    $id_shop = $shopAdapter->getContextShopID();
                }
                // END FIX
                
                $stockAvailable->id_shop = (int) $id_shop;
                $stockAvailable->id_shop_group = 0;
            }
            $stockAvailable->add();
        }

        return $stockAvailable;
    }
```

Unfortunately we can not overload the classes that are in src, so I should redo the change each update. it would be nice to integrate it into an update, or to find another solution if it is not suitable.

I created an issue for this problem : https://github.com/PrestaShop/PrestaShop/issues/16240
