### ISSUE TITLE
Module names - unexpected API behaviour

### ISSUE THREAD

**Issue by wjatekTest** [PrestaShop/PrestaShop#13787]
**Describe the bug**
When you try to submit order with incorrect module name, method getInstanceByName($module_name) in Module.php class returns false instead of throwing exception or something. It causes problem when you try to create order by API - when you put wrong module name server response is empty and you don't know what is wrong - Order.php:1687 - $payment_module - trying to call method on boolean.
It should be handled properly. For example: when you try to create address by API with empty country there is clear message that country id is missing.

**To Reproduce**
1. Create XML with new order data.
2. Change module to random word or sth.
3. Send it by API.
4. See response body - it's empty!

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @wjatekTest,

I used this script
```

<?php
// Here we define constants /!\ You need to replace this parameters
ini_set('display_errors', 'on');
define('DEBUG', true);
define('PS_SHOP_PATH', 'http://projet/shop');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = $webService->get(array('url' => PS_SHOP_PATH . '/api/orders?schema=blank'));

$xml->children()->children()->id_address_delivery = 1;
$xml->children()->children()->id_address_invoice =  1;
$xml->children()->children()->id_cart = 19;
$xml->children()->children()->id_currency = 1;
$xml->children()->children()->current_state = 1;
$xml->children()->children()->id_lang = 1;
$xml->children()->children()->id_customer = 1;
$xml->children()->children()->id_carrier = 0;
$xml->children()->children()->total_paid = '56973';
$xml->children()->children()->total_paid_real = '56973';
$xml->children()->children()->total_paid_tax_excl = '56973';
$xml->children()->children()->total_paid_tax_incl = '56977';
$xml->children()->children()->total_products = 1338;
$xml->children()->children()->total_products_wt = 1337;
$xml->children()->children()->conversion_rate = '1';
$xml->children()->children()->secure_key = md5('-1');
$xml->children()->children()->valid = 1;
$xml->children()->children()->module = 'sdsqd';
$xml->children()->children()->payment = 'banksdqdsdswire';
$xml->children()->children()->current_state = 1;

unset($xml->children()->children()->id);
unset($xml->children()->children()->date_add);
unset($xml->children()->children()->date_upd);
unset($xml->children()->children()->associations);
unset($xml->children()->children()->delivery_date);
unset($xml->children()->children()->invoice_date);
unset($xml->children()->children()->total_discounts_tax_incl);
unset($xml->children()->children()->total_discounts_tax_excl);


$opt = array('resource' => 'orders');
$opt['postXml'] = $xml->asXML();
$xml = $webService->add($opt);

```

But I have this error
![image](https://user-images.githubusercontent.com/16067358/57707388-734e6900-765f-11e9-8bbd-e1c378ee42f8.png)

Thanks to check & feedback

**Comment by wjatekTest** [comment]
Thanks for feedback!
Unfortunately I don't use PHP WebService library for Prestashop, but I think this exception is caused directly by problem I described.

**Comment by khouloudbelguith** [comment]
Hi @wjatekTest,

>Unfortunately I don't use PHP WebService library for Prestashop

How did you create an order by API?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @wjatekTest,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by wjatekTest** [comment]
What kind of detais do you need? I think problem is described well. PHP errors like these are unacceptable in this kind of application and should be at least handled and returned by web service.

**Comment by khouloudbelguith** [comment]
Hi @wjatekTest,

What is the exact XML sent did you use in your case?

Thanks!

**Comment by wjatekTest** [comment]
I think it is not important information. But if you want to test it just try setting module name to random string in your order XML and thats it

**Comment by khouloudbelguith** [comment]
@wjatekTest, thanks for your feedback.
I manage to reproduce the issue with PS1.7.5.2 & ps1.7.6.0BETA1.
If I use this script

```
<?php
// Here we define constants /!\ You need to replace this parameters
ini_set('display_errors', 'on');
define('DEBUG', true);
define('PS_SHOP_PATH', 'http://projet/beta176');
define('PS_WS_AUTH_KEY', 'key');
require_once('PSWebServiceLibrary.php');
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = $webService->get(array('url' => PS_SHOP_PATH . '/api/orders?schema=blank'));

$xml->children()->children()->id_address_delivery = 1;
$xml->children()->children()->id_address_invoice =  1;
$xml->children()->children()->id_cart = 32;
$xml->children()->children()->id_currency = 1;
$xml->children()->children()->current_state = 1;
$xml->children()->children()->id_lang = 1;
$xml->children()->children()->id_customer = 1;
$xml->children()->children()->id_carrier = 0;
$xml->children()->children()->total_paid = '56973';
$xml->children()->children()->total_paid_real = '56973';
$xml->children()->children()->total_paid_tax_excl = '56973';
$xml->children()->children()->total_paid_tax_incl = '56977';
$xml->children()->children()->total_products = 1338;
$xml->children()->children()->total_products_wt = 1337;
$xml->children()->children()->conversion_rate = '1';
$xml->children()->children()->secure_key = md5('-1');
$xml->children()->children()->valid = 1;
$xml->children()->children()->module = 'ps_checkpayment';
$xml->children()->children()->payment = 'Payment by check';
$xml->children()->children()->current_state = 1;

unset($xml->children()->children()->id);
unset($xml->children()->children()->date_add);
unset($xml->children()->children()->date_upd);
unset($xml->children()->children()->associations);
unset($xml->children()->children()->delivery_date);
unset($xml->children()->children()->invoice_date);
unset($xml->children()->children()->total_discounts_tax_incl);
unset($xml->children()->children()->total_discounts_tax_excl);


$opt = array('resource' => 'orders');
$opt['postXml'] = $xml->asXML();
$xml = $webService->add($opt);
```
But, I f I change 
`$xml->children()->children()->module = 'ps_checkpayment';`

to 

`$xml->children()->children()->module = 'test';`

I have an error 

```
</pre></div><div style="display:table;background:#CCC;font-size:8pt;padding:7px"><h6 style="font-size:9pt;margin:0">RETURN HTTP BODY</h6><pre></pre></div>PHP Fatal error:  Uncaught PrestaShopWebserviceException: This call to PrestaShop Web Services failed and returned an HTTP status of 500. That means: Internal Server Error. in /projet/1760beta1/PSWebServiceLibrary.php:87
Stack trace:
#0 /projet/1760beta1/PSWebServiceLibrary.php(217): PrestaShopWebservice->checkStatusCode(500)
#1 /projet/1760beta1/or.php(44): PrestaShopWebservice->add(Array)
#2 {main}
  thrown in /projet/1760beta1/PSWebServiceLibrary.php on line 87

Fatal error: Uncaught PrestaShopWebserviceException: This call to PrestaShop Web Services failed and returned an HTTP status of 500. That means: Internal Server Error. in /projet/1760beta1/PSWebServiceLibrary.php on line 87

PrestaShopWebserviceException: This call to PrestaShop Web Services failed and returned an HTTP status of 500. That means: Internal Server Error. in /projet/1760beta1/PSWebServiceLibrary.php on line 87

Call Stack:
    0.0001     372840   1. {main}() /projet/1760beta1/or.php:0
    0.3622     438872   2. PrestaShopWebservice->add() /projet/1760beta1/or.php:44
    0.4690     439600   3. PrestaShopWebservice->checkStatusCode() /projet/1760beta1/PSWebServiceLibrary.php:217

```

And this error not clear.

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by wjatekTest** [comment]
It is simple, I described it in my first post in this issue. Method which is supposed to return Module by name returns FALSE (?!) instead of object or null (if there is no Module with given name) and it is not checked afterwards. It causes an error, because in Order.php:1687 (PS version mentioned in original post) you try to call method on variable wchich is not an object but FALSE - it causes fatal error and webservice returns code 500 without any details. I suppose it is not singular case, but I have no time to check it

Maybe I'll try to fix in the free time.

Btw. I'm sure you will find clear and meaningful error in PHP logs on your Prestashop server
