### ISSUE TITLE
Impossible to load Legacy classes in Console commands

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#14173]

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers what do you think? what is the severity of this issue?

Thanks!

**Comment by eternoendless** [comment]
It's probably a bootstrapping issue. Needs to be investigated so that PrestaShop is correctly initialized when launching module commands. I suppose that this is not a problem when using Core sf commands?

**Comment by mickaelandrieu** [comment]
Hi  @eternoendless, it depends: if you create a service that requires an object model as constructor parameter you may break the official command "php bin/console debug:container".

I know some agencies require a legacy file in their command and initiate a fake employee in order to make their commands works as expected because the PrestaShop autoloader needs it.

**Comment by PierreRambaud** [comment]
Look like you need to initialize the legacy:
https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Command/GenerateMailTemplatesCommand.php#L99

**Comment by PierreRambaud** [comment]
FYI It's fixed in 1.7.6.2

**Comment by mickaelandrieu** [comment]
As #15081 is not merged, I don't think so. The problem is not only about requiring the right file.

But if you think so, feel free to close the related PR so I don't have to maintain it anymore if you don't plan to accept it.

**Comment by mickaelandrieu** [comment]
> FYI It's fixed in 1.7.6.2

It's not.

```php
<?php

namespace Solvolabs\Test\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Product;

class ShowProductsCommand extends Command
{
    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this
            ->setName('test:show-products')
            ->setDescription('Displays the last 10 Products')
            ->setHelp('This command allows you to display the shop products')
        ;
    }

    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $io = new SymfonyStyle($input, $output);
        $io->title('Training Shop status command');



        $products = Product::getProducts(1, 0, 10, 'id_product', 'ASC');

        $io->table(
            ['ID', 'Name', 'Stock', 'Activated?'],
            $this->formatProductInformation($products)
        );
    }

    /**
     * @param array $products the list of the products
     *
     * @return array
     */
    private function formatProductInformation(array $products)
    {
        $shopsInformation = [];
        /** @var Product $product */
        foreach ($products as $product) {
            $shopsInformation[] = [
                $product->id,
                $product->name,
                $product->quantity,
                $product->active ? '✔' : '✘',
            ];
        }

        return $shopsInformation;
    }
}
```

```
C:\wamp64\www\boutique>php bin/console test:show-products
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Undefined class constant 'EXCEPTION' in C:\wamp64\www\boutique\vendor\symfony\symfony\src\Symfony\Component\
Console\Application.php:986
Stack trace:
#0 C:\wamp64\www\boutique\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(86): Symfony\Component\Console\Application->doRunCommand(Object(Solvolabs\Test\Com
mand\ShowProductsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 C:\wamp64\www\boutique\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(255): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Solvolabs\Test\Co
mmand\ShowProductsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\wamp64\www\boutique\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(74): Symfony\Component\Console\Application->doRun(Obje in C:\wamp64\www\boutique\v
endor\symfony\symfony\src\Symfony\Component\Console\Application.php on line 986

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Undefined class constant 'EXCEPTION' in C:\wamp64\www\boutique\vendor\symfony\symfony\src\Symfony\Component\Conso
le\Application.php:986
Stack trace:
#0 C:\wamp64\www\boutique\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(86): Symfony\Component\Console\Application->doRunCommand(Object(Solvolabs\Test\Com
mand\ShowProductsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 C:\wamp64\www\boutique\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(255): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Solvolabs\Test\Co
mmand\ShowProductsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\wamp64\www\boutique\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(74): Symfony\Component\Console\Application->doRun(Obje in C:\wamp64\www\boutique\v
endor\symfony\symfony\src\Symfony\Component\Console\Application.php on line 986
```

PrestaShop 1.7.6.5.

```

**Comment by matks** [comment]
Reopening the issue as it's still there

I'll deal with it

**Comment by mickaelandrieu** [comment]
Hi,

I don't want to be notified, so please create your own issue.

Thanks.

**Comment by PierreRambaud** [comment]
@mickaelandrieu Feel free to remove notification on the right panel, with this, you'll no longer receive notifications :+1: 
![image](https://user-images.githubusercontent.com/1462701/83537797-564c3880-a4f5-11ea-8059-00920bc16b7e.png)

**Comment by mickaelandrieu** [comment]
Done !

**Comment by matks** [comment]
Spent a lot of time today trying to fix this without modifying Command and Application classes to avoid BC break.
My idea is to use Console Command events, plug myself "just before any command is run" and load the fake context.

However this has to be done after container is booted. So I need to plug myself
- after `$kernel->boot();` (so container is available)
- before `doRun()`

and the 2 happens at same time in FrameworkBundle/Console/Application
```
    public function doRun(InputInterface $input, OutputInterface $output)
    {
        $this->kernel->boot();

        $this->setDispatcher($this->kernel->getContainer()->get('event_dispatcher'));

        $this->registerCommands();

        if ($this->registrationErrors) {
            $this->renderRegistrationErrors($input, $output);
        }

        return parent::doRun($input, $output);
    }
```

I also found some limitation that I reported to Symfony https://github.com/symfony/symfony/issues/37680

**Comment by mickaelandrieu** [comment]
Or ... you could have accepted the PR I've done months ago, fix, tests and module included 🤪 

Believe me or not, even after clicking on "Unsubscribe" I'm still notified both per email and on the website :/

**Comment by matks** [comment]
> Believe me or not, even after clicking on "Unsubscribe" I'm still notified both per email and on the website :/

This looks like a GitHub issue. You might want to report it. Lately they have shipped a lot of features and improvements, it seems they can fix things fast.
