### ISSUE TITLE
FYI Class "AdminLinkWidgetController" not found

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#14435]
Reading the log there seems to be something that should be fixed? I did not have any problems btw.
```

[2019-06-30 13:45:23] app.ERROR: Class "AdminLinkWidgetController" not found in controllers/admin [] []
[2019-06-30 13:45:25] app.INFO: Exporting mail with theme modern for language English (English) [] []
[2019-06-30 13:45:25] app.INFO: Core output folder: C:\laragon\www\prestashop_1.7.6.0-rc.1/mails [] []
[2019-06-30 13:45:25] app.INFO: Modules output folder: C:\laragon\www\prestashop_1.7.6.0-rc.1/modules/ [] []
[2019-06-30 13:45:28] app.INFO: Exporting mail with theme modern for language Dansk (Danish) [] []
[2019-06-30 13:45:28] app.INFO: Core output folder: C:\laragon\www\prestashop_1.7.6.0-rc.1/mails [] []
[2019-06-30 13:45:28] app.INFO: Modules output folder: C:\laragon\www\prestashop_1.7.6.0-rc.1/modules/ [] []
[2019-06-30 13:53:14] cache.WARNING: Failed to save key "%5BPrestaShopBundle%5CEntity%5CLang%24isoCode%5D%5B1%5D" (array) {"key":"%5BPrestaShopBundle%5CEntity%5CLang%24isoCode%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): rename(C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\var\\cache\\prod\\pools\\qSWZpQ17QI\\5d18a2aa661c54.48160271,C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\var\\cache\\prod\\pools\\qSWZpQ17QI\\F\\X\\Gs4Xe-IVZXMVX3XqmTh7): Adgang n�gtet. (code: 5) at C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Cache\\Traits\\FilesystemCommonTrait.php:93)"} []
[2019-06-30 13:53:14] cache.WARNING: Failed to save key "%5BPrestaShopBundle%5CEntity%5CModuleHistory%23setIdEmployee%5D%5B1%5D" (array) {"key":"%5BPrestaShopBundle%5CEntity%5CModuleHistory%23setIdEmployee%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): rename(C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\var\\cache\\prod\\pools\\qSWZpQ17QI\\5d18a2aa661c54.48160271,C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\var\\cache\\prod\\pools\\qSWZpQ17QI\\Q\\Z\\jhUX2tBecNtpuXjDQYB1): Adgang n�gtet. (code: 5) at C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Cache\\Traits\\FilesystemCommonTrait.php:93)"} []
[2019-06-30 13:53:14] cache.WARNING: Failed to save key "%5BPrestaShopBundle%5CEntity%5CModuleHistory%23getIdModule%5D%5B1%5D" (array) {"key":"%5BPrestaShopBundle%5CEntity%5CModuleHistory%23getIdModule%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): rename(C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\var\\cache\\prod\\pools\\qSWZpQ17QI\\5d18a2aa661c54.48160271,C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\var\\cache\\prod\\pools\\qSWZpQ17QI\\W\\K\\hn3VW-Zmibq8Jj69QEhM): Adgang n�gtet. (code: 5) at C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Cache\\Traits\\FilesystemCommonTrait.php:93)"} []
[2019-06-30 13:53:14] cache.WARNING: Failed to save key "%5BPrestaShopBundle%5CEntity%5CProductDownload%24nbDaysAccessible%5D%5B1%5D" (array) {"key":"%5BPrestaShopBundle%5CEntity%5CProductDownload%24nbDaysAccessible%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): rename(C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\var\\cache\\prod\\pools\\qSWZpQ17QI\\5d18a2aa661c54.48160271,C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\var\\cache\\prod\\pools\\qSWZpQ17QI\\E\\Z\\QZQt4NsbeqzV5MFdQ7AA): Adgang n�gtet. (code: 5) at C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Cache\\Traits\\FilesystemCommonTrait.php:93)"} []
[2019-06-30 13:53:16] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Cannot rename "C:\laragon\www\prestashop_1.7.6.0-rc.1\var\cache\prod\appFBAB.tmp" to "C:\laragon\www\prestashop_1.7.6.0-rc.1\var\cache\prod/appProdProjectContainerUrlMatcher.php"." at C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php line 289 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Cannot rename \"C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\var\\cache\\prod\\appFBAB.tmp\" to \"C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\var\\cache\\prod/appProdProjectContainerUrlMatcher.php\". at C:\\laragon\\www\\prestashop_1.7.6.0-rc.1\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Filesystem\\Filesystem.php:289)"} []

```

PHP error log:
```
[30-Jun-2019 11:43:08 UTC] PHP Warning:  file_put_contents(C:\laragon\www\prestashop_1.7.6.0-rc.1/var/cache/prod\cacert.pem): failed to open stream: No such file or directory in C:\laragon\www\prestashop_1.7.6.0-rc.1\classes\Tools.php on line 2117
[30-Jun-2019 13:54:44 Europe/Copenhagen] PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "C:\laragon\www\prestashop_1.7.6.0-rc.1/var/cache/prod\smarty\compile": rmdir(C:\laragon\www\prestashop_1.7.6.0-rc.1/var/cache/prod\smarty\compile): Directory not empty. in C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php:180
Stack trace:
#0 C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php(177): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php(177): Symfony\Component\Filesystem\Filesystem->remove(Array)
#2 C:\laragon\www\prestashop_1.7.6.0-rc.1\classes\Tools.php(3430): Symfony\Component\Filesystem\Filesystem->remove(Array)
#3 [internal function]: ToolsCore::{closure}()
#4 {main}
  thrown in C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php on line 180
[30-Jun-2019 17:05:36 Europe/Copenhagen] PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "C:\laragon\www\prestashop_1.7.6.0-rc.1/var/cache/prod/": rmdir(C:\laragon\www\prestashop_1.7.6.0-rc.1/var/cache/prod/): Directory not empty. in C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php:180
Stack trace:
#0 C:\laragon\www\prestashop_1.7.6.0-rc.1\classes\Tools.php(3430): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 [internal function]: ToolsCore::{closure}()
#2 {main}
  thrown in C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php on line 180
[30-Jun-2019 17:05:37 Europe/Copenhagen] PHP Warning:  require(C:\laragon\www\prestashop_1.7.6.0-rc.1\var\cache\prod\ContainerHg7zf91\getRouting_LoaderService.php): failed to open stream: No such file or directory in C:\laragon\www\prestashop_1.7.6.0-rc.1\var\cache\prod\ContainerHg7zf91\appProdProjectContainer.php on line 1632
[30-Jun-2019 17:05:37 Europe/Copenhagen] PHP Fatal error:  require(): Failed opening required 'C:\laragon\www\prestashop_1.7.6.0-rc.1\var\cache\prod\ContainerHg7zf91\getRouting_LoaderService.php' (include_path='C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor/pear/pear_exception;C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor/pear/console_getopt;C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor/pear/pear-core-minimal/src;C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor/pear/archive_tar;.;C:/laragon/etc/php/pear') in C:\laragon\www\prestashop_1.7.6.0-rc.1\var\cache\prod\ContainerHg7zf91\appProdProjectContainer.php on line 1632
[30-Jun-2019 17:05:37 Europe/Copenhagen] PHP Warning:  require(C:\laragon\www\prestashop_1.7.6.0-rc.1\var\cache\prod\ContainerHg7zf91\getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in C:\laragon\www\prestashop_1.7.6.0-rc.1\var\cache\prod\ContainerHg7zf91\appProdProjectContainer.php on line 1632
[30-Jun-2019 17:05:37 Europe/Copenhagen] PHP Fatal error:  require(): Failed opening required 'C:\laragon\www\prestashop_1.7.6.0-rc.1\var\cache\prod\ContainerHg7zf91\getPrestashop_AccessDenied_ListenerService.php' (include_path='C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor/pear/pear_exception;C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor/pear/console_getopt;C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor/pear/pear-core-minimal/src;C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor/pear/archive_tar;.;C:/laragon/etc/php/pear') in C:\laragon\www\prestashop_1.7.6.0-rc.1\var\cache\prod\ContainerHg7zf91\appProdProjectContainer.php on line 1632
[30-Jun-2019 17:11:45 Europe/Copenhagen] PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "C:\laragon\www\prestashop_1.7.6.0-rc.1/var/cache/dev\smarty\compile": rmdir(C:\laragon\www\prestashop_1.7.6.0-rc.1/var/cache/dev\smarty\compile): Directory not empty. in C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php:180
Stack trace:
#0 C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php(177): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php(177): Symfony\Component\Filesystem\Filesystem->remove(Array)
#2 C:\laragon\www\prestashop_1.7.6.0-rc.1\classes\Tools.php(3430): Symfony\Component\Filesystem\Filesystem->remove(Array)
#3 [internal function]: ToolsCore::{closure}()
#4 {main}
  thrown in C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php on line 180
[30-Jun-2019 17:14:14 Europe/Copenhagen] PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "C:\laragon\www\prestashop_1.7.6.0-rc.1/var/cache/dev\pools": rmdir(C:\laragon\www\prestashop_1.7.6.0-rc.1/var/cache/dev\pools): Directory not empty. in C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php:180
Stack trace:
#0 C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php(177): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 C:\laragon\www\prestashop_1.7.6.0-rc.1\classes\Tools.php(3430): Symfony\Component\Filesystem\Filesystem->remove(Array)
#2 [internal function]: ToolsCore::{closure}()
#3 {main}
  thrown in C:\laragon\www\prestashop_1.7.6.0-rc.1\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php on line 180
```

**Comment by khouloudbelguith** [comment]
Hi @MathiasReker,

Thanks for your report.
About the first log /Project_Prestashop/var/log
I have the same issue with PS1.7.6.0rc1
```
[2019-06-26 11:00:04] app.ERROR: Class "AdminLinkWidgetController" not found in controllers/admin [] []
[2019-06-26 11:01:06] app.INFO: Exporting mail with theme modern for language English (English) [] []
[2019-06-26 11:01:06] app.INFO: Core output folder: /projet/1760rc1/mails [] []
[2019-06-26 11:01:06] app.INFO: Modules output folder: /projet/1760rc1/modules/ [] []
[2019-06-26 11:01:30] app.INFO: Exporting mail with theme modern for language Français (French) [] []
[2019-06-26 11:01:30] app.INFO: Core output folder: /projet/1760rc1/mails [] []
[2019-06-26 11:01:30] app.INFO: Modules output folder: /projet/1760rc1/modules/ [] []
```

In the PS1.7.5.2 => I don't have the same errors.
ping @PrestaShop/prestashop-core-developers what do you think?

@MathiasReker about the PHP error log, I have similar errors with PS1.7.5.2

`[Thu Jun 27 14:56:33.210060 2019] [:error] [pid 26325] [client 127.0.0.1:60743] PHP Fatal error:  Uncaught Symfony\\Component\\Filesystem\\Exception\\IOException: Failed to remove file "/projet/1752stable/var/cache/dev/annotations.map": unlink(/projet/1752stable/var/cache/dev/annotations.map): Permission denied. in /projet/1752stable/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:183\nStack trace:\n#0 /projet/1752stable/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php(177): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#1 /projet/1752stable/classes/Tools.php(3343): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#2 [internal function]: ToolsCore::{closure}()\n#3 {main}\n  thrown in /projet/1752stable/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 183, referer: http://projet/1752stable/install-dev/index.php`

But with PS1.7.6.0rc1, no, I don't have similar errors.

**Comment by jolelievre** [comment]
Hello @khouloudbelguith and @MathiasReker 

About the error with `AdminLinkWidgetController` this is a known issue concerning the automatic tab registration with modern symfony routes, this was reported in this issue https://github.com/PrestaShop/PrestaShop/issues/12640

But you don't need to be alarmed by this error, as it is caught by `ModuleTabRegister` and display in the error logs. For now the only way to register a "symfony tab" is to add it manually and use legacylink for the matching. I will try to push this issue in 177 roadmap.

About the other error, seems to be a problem of permission in the cache folder. Another possibility is if the cache was cleared but another request was filling it in parallel, this can cause folders expected to be empty to contain files which prevents from removing them. Not sure how to fix this though 😕

**Comment by MathiasReker** [comment]
@jolelievre Thanks. I think you are right. I could have made a request while clearing the cache.
