### ISSUE TITLE
 Combination image selector do not works since upgrade 1.7.6 with Firefox Developper

### ISSUE THREAD

**Issue by pcdata** [PrestaShop/PrestaShop#14708]
Hello, 
I have upgrade my prestashop to 1.7.6 this morning and now the image's selector for the combination's product do not works with Firefox Developper.
And I have loose all the image combination for some product combination in the back office.
I am not able to choose a picture, when you clic on an image to affect it to the combination, the image is not selected.

It works with Chrome.

Each new version have some new problem.
I have upgrade to resolve a payment problem and now another one appeared.

I am testing Prestashop since a few month but how is it possible to work and to sell something seriously with that software ?? 
There is a lot of problems, it's abosutely amazing even for a free product.

PrestaShop version: 1.7.6
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @pcdata,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & 1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Thanks to downgrade your version PHP, check & feedback.

**Comment by DPStudioGR** [comment]
I also have the same problem on all browsers (i also created a new post) 
I did change my php to 7.2 and the problem persists..

**Comment by DPStudioGR** [comment]
has anyone tried to roll back to resolve the issue?
i tried twice and get the following error..

This is not a simple issue ......
i also tried to rollback to 1.7.5.2 and i get the following error..

[INTERNAL] /home/stampast/public_html/stampa-stampa.com/config/config.inc.php line 123 - Error: Call to a member function getName() on null #0 /home/stampast/public_html/stampa-stampa.com/modules/autoupgrade/classes/UpgradeContainer.php(550): require_once() #1 /home/stampast/public_html/stampa-stampa.com/modules/autoupgrade/classes/TaskRunner/AbstractTask.php(120): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore() #2 /home/stampast/public_html/stampa-stampa.com/Iriathen/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\AbstractTask->init() #3 {main}

**Comment by khouloudbelguith** [comment]
@Stampa-Stampa,

What is the exact version of the 1-click upgrade did you use?

Thanks!

**Comment by DPStudioGR** [comment]
v4.9.0

**Comment by khouloudbelguith** [comment]
@Stampa-Stampa, In my case, I did not manage to reproduce the issue with PS1.7.6.0 after upgrade from PS1.7.5.2 using the 1-click upgrade v4.9.0 using Firefox & Chrome (Images are well selected for each combination).
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by DPStudioGR** [comment]
will have to check wiht my server... the only error log file i found contains the following errors since the day i updated.

[2019-07-17 22:39:04] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2019-07-17 22:39:06] doctrine.DEBUG: SELECT name FROM psxa_module WHERE active = 1 [] []
[2019-07-17 22:39:06] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"a3e57e","_route":"_wdt"},"request_uri":"https://stampa-stampa.com/stampa-stampa.com/Iriathen/index.php/_wdt/a3e57e?_token=N8pF7bUZ430LXHl_4SH0VyVY9BdaUGojYoRBNlRZaWA","method":"GET"} []
[2019-07-17 22:39:06] php.INFO: User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector". {"exception":"[object] (ErrorException(code: 0): User Deprecated: Implementing \"Symfony\\Component\\HttpKernel\\DataCollector\\DataCollectorInterface\" without the \"reset()\" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class \"Csa\\Bundle\\GuzzleBundle\\DataCollector\\GuzzleCollector\". at /home/stampast/public_html/stampa-stampa.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php:215)"} []
[2019-07-17 22:39:07] doctrine.DEBUG: SELECT name FROM psxa_module WHERE active = 1 [] []
[2019-07-17 22:39:07] request.INFO: Matched route "admin_combination_generate_form". {"route":"admin_combination_generate_form","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\CombinationController::generateCombinationFormAction","combinationIds":"34841-34842-34843-34844-34845-34846-34847-34848-34849-34850-34851-34852-34853-34854-34855-34856-34857-34858-34859-34860","_route":"admin_combination_generate_form"},"request_uri":"https://stampa-stampa.com/stampa-stampa.com/Iriathen/index.php/sell/catalog/products/combinations/form/34841-34842-34843-34844-34845-34846-34847-34848-34849-34850-34851-34852-34853-34854-34855-34856-34857-34858-34859-34860?_token=N8pF7bUZ430LXHl_4SH0VyVY9BdaUGojYoRBNlRZaWA","method":"GET"} []
[2019-07-17 22:39:07] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2019-07-17 22:39:07] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"info@stampa-stampa.com"} []
[2019-07-17 22:39:07] php.INFO: User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector". {"exception":"[object] (ErrorException(code: 0): User Deprecated: Implementing \"Symfony\\Component\\HttpKernel\\DataCollector\\DataCollectorInterface\" without the \"reset()\" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class \"Csa\\Bundle\\GuzzleBundle\\DataCollector\\GuzzleCollector\". at /home/stampast/public_html/stampa-stampa.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php:215)"} []
[2019-07-17 22:39:07] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2019-07-17 22:39:08] doctrine.DEBUG: SELECT name FROM psxa_module WHERE active = 1 [] []
[2019-07-17 22:39:08] request.INFO: Matched route "admin_combination_generate_form". {"route":"admin_combination_generate_form","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\CombinationController::generateCombinationFormAction","combinationIds":"34841-34842-34843-34844-34845-34846-34847-34848-34849-34850-34851-34852-34853-34854-34855-34856-34857-34858-34859-34860","_route":"admin_combination_generate_form"},"request_uri":"https://stampa-stampa.com/stampa-stampa.com/Iriathen/index.php/sell/catalog/products/combinations/form/34841-34842-34843-34844-34845-34846-34847-34848-34849-34850-34851-34852-34853-34854-34855-34856-34857-34858-34859-34860?_token=N8pF7bUZ430LXHl_4SH0VyVY9BdaUGojYoRBNlRZaWA","method":"GET"} []
[2019-07-17 22:39:08] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2019-07-17 22:39:08] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"info@stampa-stampa.com"} []
[2019-07-17 22:39:08] php.INFO: User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector". {"exception":"[object] (ErrorException(code: 0): User Deprecated: Implementing \"Symfony\\Component\\HttpKernel\\DataCollector\\DataCollectorInterface\" without the \"reset()\" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class \"Csa\\Bundle\\GuzzleBundle\\DataCollector\\GuzzleCollector\". at /home/stampast/public_html/stampa-stampa.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php:215)"} []
[2019-07-17 22:39:08] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2019-07-17 22:39:18] doctrine.DEBUG: SELECT name FROM psxa_module WHERE active = 1 [] []
[2019-07-17 22:39:18] request.INFO: Matched route "admin_performance". {"route":"admin_performance","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\Configure\\AdvancedParameters\\PerformanceController::indexAction","_legacy_controller":"AdminPerformance","_legacy_link":"AdminPerformance","_route":"admin_performance"},"request_uri":"https://stampa-stampa.com/stampa-stampa.com/Iriathen/index.php/configure/advanced/performance/?_token=N8pF7bUZ430LXHl_4SH0VyVY9BdaUGojYoRBNlRZaWA","method":"GET"} []
[2019-07-17 22:39:18] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2019-07-17 22:39:18] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"info@stampa-stampa.com"} []
[2019-07-17 22:39:18] doctrine.DEBUG: SELECT * FROM psxa_memcached_servers [] []
[2019-07-17 22:39:18] doctrine.DEBUG: SELECT * FROM psxa_memcached_servers [] []
[2019-07-17 22:39:18] translation.WARNING: Translation not found. {"id":"Never recompile template files","domain":"AdminAdvparametersFeature","locale":"en-US"} []
[2019-07-17 22:39:18] translation.WARNING: Translation not found. {"id":"Recompile templates if the files have been updated","domain":"AdminAdvparametersFeature","locale":"en-US"} []
[2019-07-17 22:39:18] translation.WARNING: Translation not found. {"id":"Force compilation","domain":"AdminAdvparametersFeature","locale":"en-US"} []
[2019-07-17 22:39:18] translation.WARNING: Translation not found. {"id":"File System","domain":"AdminAdvparametersFeature","locale":"en-US"} []
[2019-07-17 22:39:18] translation.WARNING: Translation not found. {"id":"MySQL","domain":"AdminAdvparametersFeature","locale":"en-US"} []
[2019-07-17 22:39:18] translation.WARNING: Translation not found. {"id":"Never clear cache files","domain":"AdminAdvparametersFeature","locale":"en-US"} []
[2019-07-17 22:39:18] translation.WARNING: Translation not found. {"id":"Clear cache everytime something has been modified","domain":"AdminAdvparametersFeature","locale":"en-US"} []
[2019-07-17 22:39:18] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2019-07-17 22:39:19] doctrine.DEBUG: SELECT name FROM psxa_module WHERE active = 1 [] []
[2019-07-17 22:39:19] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"fe7c5c","_route":"_wdt"},"request_uri":"https://stampa-stampa.com/stampa-stampa.com/Iriathen/index.php/_wdt/fe7c5c?_token=N8pF7bUZ430LXHl_4SH0VyVY9BdaUGojYoRBNlRZaWA","method":"GET"} []
[2019-07-17 22:39:19] php.INFO: User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector". {"exception":"[object] (ErrorException(code: 0): User Deprecated: Implementing \"Symfony\\Component\\HttpKernel\\DataCollector\\DataCollectorInterface\" without the \"reset()\" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class \"Csa\\Bundle\\GuzzleBundle\\DataCollector\\GuzzleCollector\". at /home/stampast/public_html/stampa-stampa.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php:215)"} []
[2019-07-17 22:39:23] doctrine.DEBUG: SELECT name FROM psxa_module WHERE active = 1 [] []
[2019-07-17 22:39:23] request.INFO: Matched route "admin_performance_save". {"route":"admin_performance_save","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\Configure\\AdvancedParameters\\PerformanceController::processFormAction","_legacy_controller":"AdminPerformance","_legacy_link":"AdminPerformance:update","_route":"admin_performance_save"},"request_uri":"https://stampa-stampa.com/stampa-stampa.com/Iriathen/index.php/configure/advanced/performance/?_token=N8pF7bUZ430LXHl_4SH0VyVY9BdaUGojYoRBNlRZaWA","method":"POST"} []
[2019-07-17 22:39:23] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2019-07-17 22:39:23] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"info@stampa-stampa.com"} []
[2019-07-17 22:39:23] doctrine.DEBUG: SELECT * FROM psxa_memcached_servers [] []
[2019-07-17 22:39:23] php.INFO: User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector". {"exception":"[object] (ErrorException(code: 0): User Deprecated: Implementing \"Symfony\\Component\\HttpKernel\\DataCollector\\DataCollectorInterface\" without the \"reset()\" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class \"Csa\\Bundle\\GuzzleBundle\\DataCollector\\GuzzleCollector\". at /home/stampast/public_html/stampa-stampa.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php:215)"} []
[2019-07-17 22:39:23] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []

**Comment by khouloudbelguith** [comment]
@Stampa-Stampa, in your log file, you don't have any errors, only some warnings & PHP Info.
Could you please try to enable debug mode in your store and debug request which is sent for a product when selecting an image in your browser, using DevTools, so:

1. enable debug mode
2. go to the product page
3. open up developer tools
4. go to Network tab
5. Try to select an image for a combination
6. wait for an error, you should see red request information in Network tab
7. click on it, you should see the error message in "Response" or "Preview" tab

Thanks!

**Comment by DPStudioGR** [comment]
From the start once i open a product i get this...**
GET https://stampa-stampa.com/stampa-stampa.com/Iriathen/themes/new-theme/public/index.php?controller=AdminDashboard&token=48fb438a31f3f2558109ae59ab31a311 net::ERR_ABORTED 404

**Comment by DPStudioGR** [comment]
the same with an other..
GET https://stampa-stampa.com/stampa-stampa.com/Iriathen/themes/new-theme/public/index.php?controller=AdminDashboard&token=48fb438a31f3f2558109ae59ab31a311 net::ERR_ABORTED 404

**Comment by khouloudbelguith** [comment]
@Stampa-Stampa, could you please provide me a screenshot, Is there any exception displayed in the Response Tab?

Thanks!

**Comment by DPStudioGR** [comment]
i  am not sure how to find exceptions i only get this 
i also found that in debug mode..

"Enabling the "sensio_framework_extra.router.annotations" configuration is deprecated since version 5.2. Set it to false and use the "Symfony\Component\Routing\Annotation\Route" annotation from Symfony itself.
Hide context    Hide trace
[▼
  "exception" => SilencedErrorContext {#99128 ▶}
]
{▼
  /home/stampast/public_html/stampa-stampa.com/vendor/sensio/framework-extra-bundle/DependencyInjection/SensioFrameworkExtraExtension.php:41 {▶}
  /home/stampast/public_html/stampa-stampa.com/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php:71 {▶}
}
"

**Comment by khouloudbelguith** [comment]
@Stampa-Stampa, Could you please provide me the link to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

**Comment by khouloudbelguith** [comment]
@Stampa-Stampa, I checked your shop, all images are well selected.
(i checked with Firefox & Chrome => OK)
I sent you via email a screen record.

Thanks!

**Comment by DPStudioGR** [comment]
Thank you very much for your time and effort..
indeed i installed firefox and all works fine....  
despite the fact that i cleared cache on chrome and erased all still the issue persists...  :(

**Comment by khouloudbelguith** [comment]
@Stampa-Stampa, what is the exact version Chrome did you use?

Thanks!

**Comment by DPStudioGR** [comment]
75.0.3770.142 (official) (64-bit)

**Comment by khouloudbelguith** [comment]
@Stampa-Stampa, I tried also with Chrome Version 75.0.3770.80 (Official Build) (64-bit) & it is OK.
I sent you a screen record by email.

Thanks!

**Comment by radzi00** [comment]
I have the same 404 issue with 1.7.6.0 on a product edit page:
/themes/new-theme/public/index.php?controller=AdminDashboard&token=XXX (404)

I can confirm that there is no index.php in that directory.

**Comment by khouloudbelguith** [comment]
Hi @pcdata, @Stampa-Stampa, @radzi00,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by dtwfung** [comment]
I have installed a fresh installation of 1.7.6.1. I got the same error too.
GET https://cop9gun.com/XXXX/admin123/themes/new-theme/public/index.php?controller=AdminDashboard&token=a7066b8363509a4bb9da3a3169e99d93 net::ERR_ABORTED 404
product_page.bundle.js?1.7.6.1:60 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
product_page.bundle.js?1.7.6.1:60 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
object.gif:1 GET https://cop9gun.com/XXXX/js/tiny_mce/skins/prestashop/img/object.gif 404

I'm using 
PHP version: 7.1.30
Google Chrome 
Version 76.0.3809.132 (Official Build) (64-bit)
Tried on Microsoft Edge and got same error. I don't mind to give the access point to you to reproduce the error.

**Comment by ignaciomorenohojas** [comment]
I ran into what looks like the same underlying issue on PrestaShop 1.7.6.9 and tracked down a likely root cause, sharing in case it helps.

**Context:** product with ~300 active combinations (137 colors × 4 sizes) and 168 images, each color's 2 images shared across its sizes. Combination-image associations kept randomly disappearing after saving from the admin — likely due to timeouts, since this product sends a very large payload on every save.

**Root cause:** some of the "missing" images weren't just missing rows in `ps_product_attribute_image` — they had been silently reassigned to `id_product = 0` in `ps_image`, presumably from an interrupted save. Once detached from the product, the BO image editor couldn't find them either.

**Fix:**
```sql
SET @max_pos = (SELECT COALESCE(MAX(position), -1) FROM ps_image WHERE id_product = <PRODUCT_ID>);
SET @rownum = 0;
UPDATE ps_image
SET position = @max_pos + (@rownum := @rownum + 1)
WHERE id_product = 0
ORDER BY id_image;

UPDATE ps_image SET id_product = <PRODUCT_ID> WHERE id_product = 0;
```

After reattaching, combination-image associations could be rebuilt normally. Not 100% sure it's the same failure mode as the original report, but the symptom matches closely enough to be worth documenting here.
