### ISSUE TITLE
Error on ThemeManager.php during upgrade from 1.6.1.23 to 1.7.6.0

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#14904]
Hi
I get this error using 1-click upgrade module

[INTERNAL] /var/www/html/todoparatucoche/17/src/Core/Addon/Theme/ThemeManager.php line 301 - PrestaShop\PrestaShop\Core\Domain\Theme\Exception\FailedToEnableThemeModuleException: Unfortunately, the module did not return additional details. #0 /var/www/html/todoparatucoche/17/src/Core/Addon/Theme/ThemeManager.php(180): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array) #1 /var/www/html/todoparatucoche/17/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(92): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic') #2 /var/www/html/todoparatucoche/17/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme17('classic') #3 /var/www/html/todoparatucoche/17/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(680): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic') #4 /var/www/html/todoparatucoche/17/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(117): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme() #5 /var/www/html/todoparatucoche/17/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #6 /var/www/html/todoparatucoche/17/adminvictor/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #7 {main}

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/62069571-e1ef9b80-b238-11e9-883b-766d14c7eb7f.png)

**Additional information**
1-click upgrade module: 4.9.0
PrestaShop version: 1.7.6.0
PHP version: 7.0

**Comment by Maofree** [comment]
I solve it upgrading the modules
it is ok now
