### ISSUE TITLE
unable to save or modifiy product , post error 500 only in production mode

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#15154]
Open a product imported from database backup, try to edit it and save.

Request URL: https://www.store.com/admin/index.php/product/form/81611?_token=PhuhII7RdQ4dyagV_dgHTtE53zfAyTvCsDClv8yI9ZI
Request Method: POST
Status Code: 500 
Remote Address: XXX.XXX.XXX.XXX:443
Referrer Policy: no-referrer-when-downgrade

RED ALERT MESSAGE "Unable to update settings".

Turn on dev mode result in green success message confirmation but products are not updated (after a refresh we cant see the modification in any fields) .

POST https://www.store.com/admin/index.php/product/form/81607?_token=PhuhII7RdQ4dyagV_dgHTtE53zfAyTvCsDClv8yI9ZI 500
send @ main.bundle.js:292
ajax @ main.bundle.js:292
send @ form.js?1.7.0:856
(anonymous) @ form.js?1.7.0:1030
dispatch @ main.bundle.js:292
_.handle @ main.bundle.js:292

Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.error (form.js?1.7.0:907)
    at u (main.bundle.js:292)
    at Object.fireWith [as rejectWith] (main.bundle.js:292)
    at i (main.bundle.js:292)
    at XMLHttpRequest.<anonymous> (main.bundle.js:292)
error @ form.js?1.7.0:907
u @ main.bundle.js:292
fireWith @ main.bundle.js:292
i @ main.bundle.js:292
(anonymous) @ main.bundle.js:292
load (async)
send @ main.bundle.js:292
ajax @ main.bundle.js:292
send @ form.js?1.7.0:856
(anonymous) @ form.js?1.7.0:1030
dispatch @ main.bundle.js:292
_.handle @ main.bundle.js:292

**Additional information**
PrestaShop version: 1.7.4.4
PHP version: 7.1 fpm

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

What is the exact version PrestaShop did you use?

Thanks!

**Comment by matteolavaggi** [comment]
1.7.4.4 

I've test this bug with apache and nginx so is not something related to web server.
memcache is disable and opcache, dev cache, prod cache, pagespeed cache, nginx cache are flushed every time before the try.

Using the "add product" button reload the admin control panel instead open the new product page:

Request URL: https://naws01.sixrace.it/admin638mhuhr8/index.php/product/new?_token=mOYz8AcEG60O0j2Jf48SXwuURszXZFfm_j20AsXIGBI
Request Method: GET
Status Code: 302 
Remote Address: 51.68.81.86:443
Referrer Policy: no-referrer-when-downgrade
cache-control: max-age=0, must-revalidate, private
content-type: text/html; charset=UTF-8
date: Mon, 19 Aug 2019 12:45:40 GMT
location: /admin638mhuhr8/index.php/product/form/?_token=mOYz8AcEG60O0j2Jf48SXwuURszXZFfm_j20AsXIGBI

Request URL: https://naws01.sixrace.it/admin638mhuhr8/index.php/product/form/index.php?controller=AdminDashboard&token=85f64f73d9a7d486490478a0e64a0717
Request Method: GET
Status Code: 200 
Remote Address: 51.68.81.86:443
Referrer Policy: no-referrer-when-downgrade


This is frustrating. We try 100 times to create a ps 1.7.4.4 working setup with no problem but seem impossible to have...

**Comment by khouloudbelguith** [comment]
@matteolavaggi, this issue occurs only in production mode? in dev mode is ok?

Thanks!

**Comment by matteolavaggi** [comment]
In dev mode:

Creation of product show this error:

Unknown column 'additional_delivery_times' in 'field list'<br /><br /><pre>INSERT INTO `ps_product` (`id_shop_default`, `id_manufacturer`, `id_supplier`, `reference`, `supplier_reference`, `location`, `width`, `height`, `depth`, `weight`, `quantity_discount`, `ean13`, `isbn`, `upc`, `cache_is_pack`, `cache_has_attachments`, `is_virtual`, `state`, `additional_delivery_times`, `id_category_default`, `id_tax_rules_group`, `on_sale`, `online_only`, `ecotax`, `minimal_quantity`, `low_stock_threshold`, `low_stock_alert`, `price`, `wholesale_price`, `unity`, `unit_price_ratio`, `additional_shipping_cost`, `customizable`, `text_fields`, `uploadable_files`, `active`, `redirect_type`, `id_type_redirected`, `available_for_order`, `available_date`, `show_condition`, `condition`, `show_price`, `indexed`, `visibility`, `cache_default_attribute`, `advanced_stock_management`, `date_add`, `date_upd`, `pack_stock_type`) VALUES ('1', '0', '0', '', '', '', '0', '0', '0', '0', '0', '', '', '', '0', '0', '0', '0', '1', '2', '113', '0', '0', '0', '1', NULL, '0', '0', '0', '', '0', '0', '0', '0', '0', '1', '', '0', '1', '0000-00-00', '0', 'new', '1', '0', 'both', '0', '0', '2019-08-19 14:48:18', '2019-08-19 14:48:18', '3')</pre>



Instead there is no output for the error on saving, nor in exception log or dev log.

Saving result in green flag "setting supdated", but after a refresh of the product the change are not persistent -_- !

**Comment by matteolavaggi** [comment]
Ok seems that prestashop dev team choose to add a couple of additional field in the ps_product database structure from 1.3 to 1.4 ( O_O ), in fact making incomaptible a backup restore with drop table statement (the more secure one). .. Any one have a copy of original ps 1.7.4 database structure? 

thanks

**Comment by khouloudbelguith** [comment]
@matteolavaggi, You can find the full schema for 1.7.4.4 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.4.4/install-dev/data/db_structure.sql

Thanks!

**Comment by matteolavaggi** [comment]
Thanks. Why alter a table structure important like ps_product ... ?!

**Comment by matteolavaggi** [comment]
Thanks. Why alter a table structure important like ps_product ... ?!

Updating the table with missing field does not fix the problem, only remove the debug exception message when load the new page product.

So the problem is not related to database. There is no dev log entry on save, only the red alert message: "unable to update setting".


We need to migrate from a 1.3 to 1.4 for 2 main BUG (modules page that take 20 minutes to load , and product page that take 10 minutes to save)... and we found 1 of the 2 problem also on ps 1.7.4 (the saving problem).

Now in back office under dev mode we get a red alert but new product are stored in databse (just this is so strange). Reload the product page result in a new product entry, but the save procedure take very long time with the update circle runnin over the save button in top right corner with no end:
![image](https://user-images.githubusercontent.com/24798703/63271125-bc830a00-c299-11e9-9d74-61da9aef4f5f.png)

**Comment by khouloudbelguith** [comment]
@matteolavaggi, Could you please check those issues: #9677, #9954, #9717, #9955.
It can be an issue similar.
Thanks to check & feedback.

**Comment by matteolavaggi** [comment]
#9677 has a link to a merge that involve a classes/Tag.php file, this file is complete different on ps 1.7.4.4 than the one shown here:

MERGE FILE:

        foreach ($list as $tag) {
            $data[] = array(
                'id_tag' => (int) $tag,
                'id_product' => (int) $id_product,
                'id_lang' => (int) $id_lang,
                'id_product' => (int) $idProduct,
                'id_lang' => (int) $idLang,
            );
        }


MY FILE 
 foreach ($list as $tag) {
            $data .= '('.(int) $tag.','.(int) $idProduct.','.(int) $idLang.'),';
        }
        $data = rtrim($data, ',');


So exactly what is the best practice to get bug fix from git repo? We see above that from one release to another there is change in file and also in database, so i cant simply clone the lastest repo and overwrite mine 1.7.4.4. How i can apply for patch ?

**Comment by khouloudbelguith** [comment]
@matteolavaggi, this change was applied after merging this PR: https://github.com/PrestaShop/PrestaShop/pull/10448/files

Thanks to check & feedback.

**Comment by matteolavaggi** [comment]
Ok but really i cant figure out a safe way to apply bug fix , they are commited in new release but new release are not upgradable overwriting file on old release because there is also database change, so any suggestion? we work on upgrade from 3 month now ^^ 

BTW this bug is not related to TAG, i've write up that happen also on creating new product, i've try to create a product with only name and price and "prova" in the description fields. no " and no other fields .

Create product, apply change on description and hit save, error are shawn but setting are saved:
![image](https://user-images.githubusercontent.com/24798703/63273826-f7d40780-c29e-11e9-95e3-b628722f9de2.png)

![image](https://user-images.githubusercontent.com/24798703/63273879-13d7a900-c29f-11e9-967a-58f733660c57.png)

Maybe is related to this problem (every time we go on product page and click on product edit we get a token error, also if we have open the product page few second before):

[2019-08-19 16:36:20] request.INFO: Matched route "admin_product_form". {"route":"admin_product_form","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\ProductController::formAction","_legacy_controller":"AdminProducts","_legacy_param_mapper_class":"PrestaShop\\PrestaShop\\Adapter\\Product\\AdminProductDataProvider","_legacy_param_mapper_method":"mapLegacyParametersProductForm","id":"81613","_route":"admin_product_form"},"request_uri":"http://naws01.sixrace.it/admin638mhuhr8/index.php/product/form/81613?_token=2OCGCvjRo0oVrhX2ZvjE9IXBSoc1ZWm3c2Fc_tI8UBM","method":"GET"} []
[2019-08-19 16:36:20] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2019-08-19 16:36:20] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"matteo.lavaggi@pineappleitaly.com"} []
[2019-08-19 16:36:20] doctrine.DEBUG: SELECT name FROM ps_module WHERE active = 1 [] []
[2019-08-19 16:36:20] php.INFO: User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector". {"exception":"[object] (ErrorException(code: 0): User Deprecated: Implementing \"Symfony\\Component\\HttpKernel\\DataCollector\\DataCollectorInterface\" without the \"reset()\" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class \"Csa\\Bundle\\GuzzleBundle\\DataCollector\\GuzzleCollector\". at /var/www/htdocs/www.sixrace.it/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php:215)"} []
[2019-08-19 16:36:20] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2019-08-19 16:36:20] request.INFO: Matched route "admin_security_compromised". {"route":"admin_security_compromised","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\SecurityController::compromisedAccessAction","_route":"admin_security_compromised"},"request_uri":"http://naws01.sixrace.it/admin638mhuhr8/index.php/security/compromised?_token=g_wDMYL-nVQk3gtN1uPJ2Dzv8jIrrTKRAcMJ39rTLZM&uri=http%253A%252F%252Fnaws01.sixrace.it%252Fadmin638mhuhr8%252Findex.php%252Fproduct%252Fform%252F81613%253F","method":"GET"} []
[2019-08-19 16:36:20] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2019-08-19 16:36:20] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"matteo.lavaggi@pineappleitaly.com"} []
[2019-08-19 16:36:20] doctrine.DEBUG: SELECT name FROM ps_module WHERE active = 1 [] []
[2019-08-19 16:36:20] php.INFO: User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector". {"exception":"[object] (ErrorException(code: 0): User Deprecated: Implementing \"Symfony\\Component\\HttpKernel\\DataCollector\\DataCollectorInterface\" without the \"reset()\" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class \"Csa\\Bundle\\GuzzleBundle\\DataCollector\\GuzzleCollector\". at /var/www/htdocs/www.sixrace.it/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php:215)"} []
[2019-08-19 16:36:20] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2019-08-19 16:36:21] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"7cda9f","_route":"_wdt"},"request_uri":"http://naws01.sixrace.it/admin638mhuhr8/index.php/_wdt/7cda9f?_token=g_wDMYL-nVQk3gtN1uPJ2Dzv8jIrrTKRAcMJ39rTLZM","method":"GET"} []
[2019-08-19 16:36:21] doctrine.DEBUG: SELECT name FROM ps_module WHERE active = 1 [] []
[2019-08-19 16:36:21] php.INFO: User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector". {"exception":"[object] (ErrorException(code: 0): User Deprecated: Implementing \"Symfony\\Component\\HttpKernel\\DataCollector\\DataCollectorInterface\" without the \"reset()\" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class \"Csa\\Bundle\\GuzzleBundle\\DataCollector\\GuzzleCollector\". at /var/www/htdocs/www.sixrace.it/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php:215)"} []


![image](https://user-images.githubusercontent.com/24798703/63274227-b98b1800-c29f-11e9-92d4-454b98ef2496.png)

**Comment by khouloudbelguith** [comment]
@matteolavaggi, about the visual issue, it is added to our bug roadmap, the issue created here: https://github.com/PrestaShop/PrestaShop/issues/9668
Did you check if it is a reference issue?

Thanks!

**Comment by matteolavaggi** [comment]
Is not a reference issue, the created product was right made under ps 1.7.3 and reference is short

**Comment by matteolavaggi** [comment]
This is the 1 click upgrade first attempt:
![image](https://user-images.githubusercontent.com/24798703/63276346-76cb3f00-c2a3-11e9-94cc-74a54a3d2fb7.png)

We change the Tag file, so upgrade stop on that file (i think for permission problem). The result is a complete broken store ! 

WTF .. cant proceed and update all other files?! OR this is the "normal" result of the 1 click upgrade module ... Have you ever try to run a 1 click upgrade on some prestashop store? its possible ? 

I suppose there is no way to have it working back right?

**Comment by matteolavaggi** [comment]
This is the second run:
[INTERNAL] /var/www/htdocs/www.sixrace.it/app/AppKernel.php line 59 - Error: Class 'League\Tactician\Bundle\TacticianBundle' not found #0 /var/www/htdocs/www.sixrace.it/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(488): AppKernel->registerBundles() #1 /var/www/htdocs/www.sixrace.it/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles() #2 /var/www/htdocs/www.sixrace.it/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #3 /var/www/htdocs/www.sixrace.it/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #4 /var/www/htdocs/www.sixrace.it/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #5 /var/www/htdocs/www.sixrace.it/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #6 /var/www/htdocs/www.sixrace.it/admin638mhuhr8/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #7 {main}


Why lot of error?

**Comment by khouloudbelguith** [comment]
@matteolavaggi, this issue is fixed with PR: https://github.com/PrestaShop/PrestaShop/pull/14620, it fixes this issue: https://github.com/PrestaShop/PrestaShop/issues/14617
It is added to the PS1.7.6.1 milestone.
Thanks!

**Comment by matteolavaggi** [comment]
Ok dear, but i cant upgrade from 1.7.4 to 1.7.6 due to an issue fixed on 1.7.7 ?!?!?!?!????????????

Are you serius? So how can i go out this infinite loop? Now backend give me error 500. No dev log or exception log

![image](https://user-images.githubusercontent.com/24798703/63277761-3620f500-c2a6-11e9-98dc-d2a919920479.png)


And I run prestashop under php 7.1 not 5.6  ...

**Comment by khouloudbelguith** [comment]
@matteolavaggi, this issue: #14617 is fixed in the next patch 1.7.6.1 & not 1.7.7.
This new issue is displayed on which page? BO/FO?
Thanks!

**Comment by matteolavaggi** [comment]
Ok i've downloaded the last stable release of 1.7.6 , so 1.7.6 has a bug that does not allow the 1 click upgrade to work .. O_O .. ok.

After the upgrade we only get that error message, all other files was just upgraded. We get the error 500 on backoffice url. Front office has the maintenance mode enabled so we dont know how to proceed. There is no log to help debug.

**Comment by khouloudbelguith** [comment]
@matteolavaggi, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by matteolavaggi** [comment]
Hi, every time we change something we flush manual all the cache, restart apache, flush opcache, restart php-fpm, check permission on file and folder. 

Disabling maintenance mode not help. Error 500 with no log entry

**Comment by khouloudbelguith** [comment]
@matteolavaggi, debug mode is enabled? there is no exception displayed?

Thanks!

**Comment by matteolavaggi** [comment]
i've just answer at this question. Debug mode is enabled and there is no exception disaplyed, you have the screenshoot of exactly what we see ...

How is possible that there is no way to fix some bug in ps?

We found bug in ps 1.7.4 (on saving product so not a function that is not used) .. try to update to 1.6.0 with 1 click update fail due to a bug (if its only one bug, we never know that) solved only in ps 1.6.1.

So we end up with a FO and BO broken. No way to get back (we try to revert back the file but this is not enough) . 

Dev log is empty, exception log is empty, we have no way to go ...

**Comment by khouloudbelguith** [comment]
@matteolavaggi, Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt

Thanks!

**Comment by matteolavaggi** [comment]
i've send to you the error of the web log... i've run 5 times a manual upgrade to 1.7.6. Now i've a shop with unpredictable new bug and no support for 80% of the module installed .... ^^

I've update also php to 7.2 but still get some error.

The main problem i can found NOW is related to home page default language redirect:


Go on https://naws01.sixrace.it/

result in

[Debug] This page has moved
Please use the following URL instead: https://naws01.sixrace.it/it/

Do you have any idea?

in the mean while i can post some consideration:

Another default module go away from free to paid:

Google Analytics  is not compatible with ps 1.6.7 ...

**Comment by khouloudbelguith** [comment]
@matteolavaggi,

>i've send to you the error of the web log

I didn't receive any log file.

>The main problem i can found NOW is related to home page default language redirect:

It is ok in my side
https://drive.google.com/file/d/1HKgNo4pT6aMXC5vkigdh92GX-4HXawym/view
It is just a redirection info displayed when debug mode is enabled & the "Redirect to the canonical URL" option is set to "302 Moved Temporarily (recommended while setting up your store)" 
![image](https://user-images.githubusercontent.com/16067358/63339723-6ebfdd80-c33d-11e9-96a5-f1da65596672.png)

You can change this option.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
