### ISSUE TITLE
Upgrade 1.7.5.1 to 1.7.6.1

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15370]
```
Copied /zaplecze/themes/new-theme/template/page_header_toolbar.tpl.
[DEV] ajax request : upgradeDb
[SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[CLEANING CACHE] File dev removed
[CLEANING CACHE] File prod removed
[INTERNAL] /home/xxxxx/domains/yyyyy.pl/public_html/backup/vendor/composer/autoload_real.php line 61 - require(/home/xxxxx/domains/yyyyy.pl/public_html/backup/vendor/composer/../icanboogie/common/bootstrap.php): failed to open stream: No such file or directory
[INTERNAL] /home/xxxxx/domains/yyyyy.pl/public_html/backup/vendor/composer/autoload_real.php line 61 - require(/home/xxxxx/domains/yyyyy.pl/public_html/backup/vendor/composer/../icanboogie/common/lib/helpers.php): failed to open stream: No such file or directory
Migrating old setting file...
parameters file already exists!
Finished...
```

`[INTERNAL] /home/xxxxx/domains/yyyyy.pl/public_html/backup/src/PrestaShopBundle/PrestaShopBundle.php line 64 - Error: Class 'PrestaShopBundle\DependencyInjection\Compiler\OverrideTwigServiceCompilerPass' not found #0 /home/xxxxx/domains/yyyyy.pl/public_html/backup/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(797): PrestaShopBundle\PrestaShopBundle->build(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #1 /home/xxxxx/domains/yyyyy.pl/public_html/backup/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(768): Symfony\Component\HttpKernel\Kernel->prepareContainer(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #2 /home/xxxxx/domains/yyyyy.pl/public_html/backup/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(636): Symfony\Component\HttpKernel\Kernel->buildContainer() #3 /home/xxxxx/domains/yyyyy.pl/public_html/backup/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #4 /home/xxxxx/domains/yyyyy.pl/public_html/backup/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #5 /home/xxxxx/domains/yyyyy.pl/public_html/backup/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #6 /home/xxxxx/domains/yyyyy.pl/public_html/backup/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #7 /home/xxxxx/domains/yyyyy.pl/public_html/backup/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #8 /home/xxxxx/domains/yyyyy.pl/public_html/backup/zaplecze/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #9 {main}`

PHP 7.2

In fact there is no 
require(**/home/xxxxx/domains/yyyyy.pl/public_html/backup/vendor/composer/../icanboogie/common/lib/helpers.php**) file...

**Comment by ghost** [comment]
Issue caused by the issue with cloning site. After reupload all process go flawless
