### ISSUE TITLE
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getAdminLink() on null in  /modules/welcome/OnBoarding/Configuration.php:79

### ISSUE THREAD

**Issue by hekep** [PrestaShop/PrestaShop#17792]
After installation:

2020-02-21T11:31:20.283167683Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP Warning:  Use of undefined constant _PS_ADMIN_DIR_ - assumed '_PS_ADMIN_DIR_' (this will throw an Error in a future version of PHP) in /modules/welcome/OnBoarding/Configuration.php on line 289
2020-02-21T11:31:20.28321679Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP Stack trace:
2020-02-21T11:31:20.283273244Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP   1. {main}() /install/index.php:0
2020-02-21T11:31:20.283287619Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP   2. InstallControllerHttp::execute() /install/index.php:48
2020-02-21T11:31:20.283293682Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP   3. InstallControllerHttpProcess->process() /install/classes/controllerHttp.php:266
2020-02-21T11:31:20.283297591Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP   4. InstallControllerHttpProcess->processInstallModules() /install/controllers/http/process.php:104
2020-02-21T11:31:20.283313569Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP   5. PrestaShopBundle\Install\Install->installModules() /install/controllers/http/process.php:233
2020-02-21T11:31:20.283318075Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP   6. PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->install() /src/PrestaShopBundle/Install/Install.php:1042
2020-02-21T11:31:20.289745466Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP   7. PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->upgrade() /src/Core/Addon/Module/ModuleManager.php:297
2020-02-21T11:31:20.289788759Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP   8. PrestaShop\PrestaShop\Adapter\Module\ModuleDataUpdater->upgrade() /src/Core/Addon/Module/ModuleManager.php:396
2020-02-21T11:31:20.289796336Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP   9. ModuleCore::getModulesOnDisk() /src/Adapter/Module/ModuleDataUpdater.php:99
2020-02-21T11:31:20.289800724Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  10. ModuleCore::isModuleTrusted() /classes/module/Module.php:1394
2020-02-21T11:31:20.289805197Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  11. ModuleCore::generateTrustedXml() /classes/module/Module.php:1737
2020-02-21T11:31:20.289809752Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  12. ModuleCore::checkModuleFromAddonsApi() /classes/module/Module.php:1842
2020-02-21T11:31:20.289814118Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  13. ModuleCore::getInstanceByName() /classes/module/Module.php:1888
2020-02-21T11:31:20.289817384Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  14. ModuleCore::coreLoadModule() /classes/module/Module.php:1120
2020-02-21T11:31:20.28982138Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  15. PrestaShop\PrestaShop\Adapter\ServiceLocator::get() /classes/module/Module.php:1141
2020-02-21T11:31:20.289825836Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  16. PrestaShop\PrestaShop\Core\Foundation\IoC\Container->make() /src/Adapter/ServiceLocator.php:65
2020-02-21T11:31:20.289830515Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  17. PrestaShop\PrestaShop\Core\Foundation\IoC\Container->doMake() /src/Core/Foundation/IoC/Container.php:177
2020-02-21T11:31:20.28983538Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  18. PrestaShop\PrestaShop\Core\Foundation\IoC\Container->makeInstanceFromClassName() /src/Core/Foundation/IoC/Container.php:164
2020-02-21T11:31:20.289839899Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  19. ReflectionClass->newInstance() /src/Core/Foundation/IoC/Container.php:131
2020-02-21T11:31:20.289846284Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  20. Welcome->__construct() /src/Core/Foundation/IoC/Container.php:131
2020-02-21T11:31:20.28985054Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  21. OnBoarding\OnBoarding->__construct() /modules/welcome/welcome.php:75
2020-02-21T11:31:20.289854654Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  22. OnBoarding\OnBoarding->loadConfiguration() /modules/welcome/OnBoarding/OnBoarding.php:57
2020-02-21T11:31:20.289859159Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  23. OnBoarding\Configuration->getConfiguration() /modules/welcome/OnBoarding/OnBoarding.php:141
2020-02-21T11:31:20.289875439Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP  24. OnBoarding\Configuration->generateSfBaseUrl() /modules/welcome/OnBoarding/Configuration.php:55
2020-02-21T11:31:20.300951887Z [21-Feb-2020 13:31:20 Europe/Helsinki] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getAdminLink() on null in /modules/welcome/OnBoarding/Configuration.php:79
2020-02-21T11:31:20.300991054Z Stack trace:
2020-02-21T11:31:20.300996089Z #0 /modules/welcome/OnBoarding/OnBoarding.php(141): OnBoarding\Configuration->getConfiguration(Object(PrestaShopBundle\Service\Routing\Router))
2020-02-21T11:31:20.301001607Z #1 /modules/welcome/OnBoarding/OnBoarding.php(57): OnBoarding\OnBoarding->loadConfiguration(Object(PrestaShopBundle\Service\Routing\Router))
2020-02-21T11:31:20.301006383Z #2 /modules/welcome/welcome.php(75): OnBoarding\OnBoarding->__construct(Object(PrestaShopBundle\Translation\TranslatorComponent), Object(Smarty_Data), Object(Welcome), Object(PrestaShopBundle\Service\Routing\Router))
2020-02-21T11:31:20.301011117Z #3 [internal function]: Welcome->__construct()
2020-02-21T11:31:20.301014663Z #4 /src/Core/Foundation/IoC/Container.php(131): ReflectionClass->newInstance()
2020-02-21T11:31:20.301018371Z #5 /src/Core/Foundation/IoC/Container.php(164): PrestaShop\PrestaShop\Core\Foundation\IoC\Container->makeInstanceFromClass in /modules/welcome/OnBoarding/Configuration.php on line 79

**Additional information**

PHP version 7.2.28
Prestashop version 1.7.6.3

**Comment by khouloudbelguith** [comment]
Hi @hekep,

Thanks for your report.
What is the exact version of the welcome module did you use?
What is the exact language/country did you use during the install?
Did you download this version from the official link of PrestaShop?

Thanks!

**Comment by hekep** [comment]
Welcome module version 6.0
Finnish language.
https://github.com/PrestaShop/PrestaShop/releases/download/1.7.6.3/prestashop_1.7.6.3.zip

**Comment by khouloudbelguith** [comment]
@hekep, I did not manage to reproduce the issue with PS1.7.6.3.
I attached a screen record
https://drive.google.com/file/d/1MTwAXNJsHAHdbPtHaGNCRo3dm2J_AN7H/view
Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by hekep** [comment]
It feels like you did  tried to reproduce in PHP 7.1.     We got the error in PHP 7.2.28.

**Comment by hekep** [comment]
It is PHP 7.2.27:

![image](https://user-images.githubusercontent.com/1901788/75149916-c6376f80-570b-11ea-8229-a4b7dcfaa7a9.png)

**Comment by hekep** [comment]
Folders OK:

![image](https://user-images.githubusercontent.com/1901788/75150090-3f36c700-570c-11ea-92ea-e8279e7379c7.png)

**Comment by hekep** [comment]
Your page  https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/ says  1.7.6.3  should be PHP 7.2 compatible.

**Comment by khouloudbelguith** [comment]
@hekep,

>Your page https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/ says 1.7.6.3 should be PHP 7.2 compatible.
 
Yes!
PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.

>It feels like you did tried to reproduce in PHP 7.1. We got the error in PHP 7.2.28.

No, In my screen record, I used PHPv7.2.
The screenshot provided is just an example.
So, I don't think, it is related to the PHP version.

Could you please try to rename the folder `welcome` to `welcome_old` into this path `Project_folder/modules/`, clear cache, check & feedback.

**Comment by hekep** [comment]
Hi,

Thanks for your effort. We suspect the problem is in server. You can close the issue.

**Comment by khouloudbelguith** [comment]
@hekep, thanks for your feedback.
I will close the issue, feel free to open a new one when needed.

Thanks!

**Comment by ebubekirakyol** [comment]
> Hi,
> 
> Thanks for your effort. We suspect the problem is in server. You can close the issue.

Hello how did you solve it? What was problem? Can you help me?
