### ISSUE TITLE
Clearing the cache results in a blank page

### ISSUE THREAD

**Issue by ebonit** [PrestaShop/PrestaShop#20582]
#### Describe the bug

After a clean install I go to the backoffice and set it to debug in menu performance. Then I immediately do a clear cache. That gives me a blank page. The frontend still works.

when I remove the var/cache/dev directory on the commandline, all works fine again.

#### Expected behavior

the backoffice keeps working.

#### Steps to Reproduce

1. clean install
2. login into the backoffice
3. Go to: Configure->Advanced Parameters->Performance
4. Set to debug, however this is not necessary to run into this issue
5. cleaar cache with the button on top

**Screenshots**

In my php log I see the following 

```
[13-Aug-2020 10:04:51 US/Eastern] PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/": **rmdir(/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/): Directory not empty.** in /home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:180
Stack trace:
#0 /home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/classes/Tools.php(3443): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 [internal function]: ToolsCore::{closure}()
#2 {main}
  thrown in /home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180
[13-Aug-2020 10:04:53 US/Eastern] PHP Fatal error:  require(): Failed opening required '/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/ContainerBrrykux/getMbo_Tab_Collection_ProviderService.php' (include_path='/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/pear_exception:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/console_getopt:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/pear-core-minimal/src:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/archive_tar:.:/usr/local/php73/lib/php') in /home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/ContainerBrrykux/appDevDebugProjectContainer.php on line 1722
[13-Aug-2020 10:04:53 US/Eastern] PHP Fatal error:  require(): Failed opening required '/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/ContainerBrrykux/getPrestashop_AccessDenied_ListenerService.php' (include_path='/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/pear_exception:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/console_getopt:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/pear-core-minimal/src:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/archive_tar:.:/usr/local/php73/lib/php') in /home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/ContainerBrrykux/appDevDebugProjectContainer.php on line 1722
[13-Aug-2020 10:04:53 US/Eastern] PHP Warning:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: require(/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/ContainerBrrykux/getRouting_LoaderService.php): failed to open stream: No such file or directory in /home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/ContainerBrrykux/appDevDebugProjectContainer.php:1722
Stack trace:
#0 /home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/ContainerBrrykux/appDevDebugProjectContainer.php(1722): require()
#1 /home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(304): ContainerBrrykux\appDevDebugProjectContainer->load('getRouting_Load...')
#2 /home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php(56): Symfony\Component\DependencyInjection\Container->get('routing.loader')
#3 /home/usoa/domains/unitedseeds.er in /home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/ContainerBrrykux/appDevDebugProjectContainer.php on line 1722
[13-Aug-2020 10:04:53 US/Eastern] PHP Fatal error:  ContainerBrrykux\appDevDebugProjectContainer::load(): Failed opening required '/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/ContainerBrrykux/getRouting_LoaderService.php' (include_path='/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/pear_exception:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/console_getopt:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/pear-core-minimal/src:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/archive_tar:.:/usr/local/php73/lib/php') in /home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/ContainerBrrykux/appDevDebugProjectContainer.php on line 1722
[13-Aug-2020 10:04:53 US/Eastern] PHP Fatal error:  require(): Failed opening required '/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/ContainerBrrykux/getDebug_FileLinkFormatter_UrlFormatService.php' (include_path='/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/pear_exception:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/console_getopt:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/pear-core-minimal/src:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/archive_tar:.:/usr/local/php73/lib/php') in /home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/ContainerBrrykux/appDevDebugProjectContainer.php on line 1722
```

the var/cache/dev directory is only partly removed. as you see in the first stack trace the removal fails:
rmdir(/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/): Directory not empty.

when I remove the var/cache/dev directory on the commandline, all works fine again.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: PHP 7.3.14

**Comment by ebonit** [comment]
this is the content of the not remover cache dir

![Schermafbeelding 2020-08-13 om 16 26 51](https://user-images.githubusercontent.com/13302588/90146910-eb836d00-dd81-11ea-8646-4a1c6927eff8.png)

**Comment by hfezvcksks** [comment]
Prestashop 1.7.6.* requires a php version between 5.6 and 7.2: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

I hope that helps

**Comment by ebonit** [comment]
with php7.2 The issue remains but is somewhat better. When I do a clear cache with debug enabled I receive an exception instead of a php error stack in the php error log

```
 (1/1) FatalErrorException

Compile Error: require(): Failed opening required '/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/ContainerBrrykux/removed-ids.php' (include_path='/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/pear_exception:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/console_getopt:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/pear-core-minimal/src:/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/vendor/pear/archive_tar:.:/usr/local/php72/lib/php')
```

![Schermafbeelding 2020-08-13 om 17 21 32](https://user-images.githubusercontent.com/13302588/90153763-a95e2980-dd89-11ea-80c1-4f1c7055f6d1.png)


when I refresh though, the var/cache/dev directory is properly filled with the new cache. So it is definatley better but still errors.

**Comment by ebonit** [comment]
Server information Linux #1 SMP Tue Jan 28 14:11:45 UTC 2020 x86_64

Server software version: Apache/2

PHP version: 7.2.27

Memory limit: 128M

Max execution time: 30

Upload Max File size: 64M

**Comment by ebonit** [comment]
and finally I tried php 7.1 That seems to have solved this issue.
clearing the cache works as expected. no errors in teh error_log and no thrown exception. 


Server information Linux #1 SMP Tue Jan 28 14:11:45 UTC 2020 x86_64

Server software version: Apache/2

PHP version: 7.1.33

Memory limit: 128M

Max execution time: 30

Upload Max File size: 64M

**Comment by ebonit** [comment]
with PHP5.6 I keep running into permission problems. for instance all directories are 755 but php5.6 expects them to be 777
this applies to the var/cache directories and the var/logs dirs. probably more..

PHP version: 5.6.40

**Comment by SimonGrn** [comment]
>the var/cache/dev directory is only partly removed. as you see in the first stack trace the removal fails:
rmdir(/home/usoa/domains/unitedseeds.ericbb.nr1net.corp/public_html/var/cache/dev/): Directory not empty.

>when I remove the var/cache/dev directory on the commandline, all works fine again.

This looks like a permissions problem. Apache is under which user ? And is your directory under the correct user ?

**Comment by khouloudbelguith** [comment]
Hi @ebonit,

I did not manage to reproduce the issue with PS1.7.6.7.
I attached a screen record
https://drive.google.com/file/d/1cKwQxCkAU6ZvlMNsdAarVWL1g2XqiD1E/view?usp=sharing
@SimonGrn said it could a permission issue or could be similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/11105#issuecomment-585609734
Also, you can follow this comment: https://github.com/PrestaShop/PrestaShop/issues/12667#issuecomment-544963403 as a solution.

Thanks!

**Comment by ebonit** [comment]
I will furher look into this in the first week of september. I am on a vacation.

regards, Ebonit

**Comment by khouloudbelguith** [comment]
@ebonit, thanks!
Waiting for your feedback.

**Comment by PierreRambaud** [comment]
Duplicate of #11105
