### ISSUE TITLE
Error 500 when i've try to create an order with webservicce

### ISSUE THREAD

**Issue by QueeNFrisk** [PrestaShop/PrestaShop#21387]
Hi i'm trying to create an order with webservice but it throw an 500 error:

`PHP Fatal error:  Uncaught PrestaShopWebserviceException: This call to PrestaShop Web Services failed and returned an HTTP status of 500. That means: Internal Server Error. in <removed>\vendor\prestashop\prestashop-webservice-lib\PSWebServiceLibrary.php:117`
`Stack trace:
 #0 <removed>\vendor\prestashop\prestashop-webservice-lib\PSWebServiceLibrary.php(301): PrestaShopWebservice->checkStatusCode(500)
#1 <removed>\Orders.php(54): PrestaShopWebservice->add(Array)
#2 <removed>\Orders.php(90): orders->add(Array, Array)
#3 {main}
  thrown in <removed>\vendor\prestashop\prestashop-webservice-lib\PSWebServiceLibrary.php on line 117`

and this is my code

```PHP
require_once '../vendor/autoload.php';
require_once '../config.php';

class orders extends config {

  protected function get(){
    $response = parent::ws()->get([
      'resource' => 'orders',
      'display' => 'full'
    ]);
    $returned = [];
    foreach($response->children()->children() as $orders) {
      array_push($returned, $orders);
    }
    return $returned;
  }

  public function add ($params = [], $products = []){
    $schemaBlank = parent::ws()->get([
      'url' => 'https://<shop>/store/api/orders?schema=blank'
    ]);
    $order = $schemaBlank->children()->children();
    $order->id_address_delivery = $params['idAddressDelivery'];
    $order->id_address_invoice = $params['idAddressInvoice'];
    $order->id_cart = $params['idCart'];
    $order->id_currency = $params['idCurrency'];
    $order->id_lang = $params['idLang'];
    $order->id_customer = $params['idCustomer'];
    $order->id_carrier = $params['idCarrier'];
    $order->module = $params['module'];
    $order->payment = $params['payment'];
    $order->total_paid = $params['totalPaid'];
    $order->total_paid_real = $params['totalPaidReal'];
    $order->total_products = $params['totalProducts'];
    $order->total_products_wt = $params['totalProductsWt'];
    $order->conversion_rate = $params['conversionRate'];

    for($i=0;$i<count($products);$i++){
      $order->associations->order_rows->order_row[$i]->product_id = $products[$i]['id'];
      $order->associations->order_rows->order_row[$i]->product_attribute_id = $products[$i]['attributeId'];
      $order->associations->order_rows->order_row[$i]->product_quantity = $products[$i]['quantity'];
      $order->associations->order_rows->order_row[$i]->product_name = $products[$i]['name'];
      $order->associations->order_rows->order_row[$i]->product_reference = $products[$i]['sku'];
      $order->associations->order_rows->order_row[$i]->product_ean13 = $products[$i]['ean'];
      $order->associations->order_rows->order_row[$i]->product_price = $products[$i]['price'];
    }

    print_r($order);

    $createXml = parent::ws()->add([
      'resource' => 'orders',
      'postXml' => $schemaBlank->asXML()
    ]);

    var_dump($createXml);
  }

}

// This info is only for the example

$a = new orders;
$a->add(
  array( // Params
    'idAddressDelivery' => '6',
    'idAddressInvoice' => '6',
    'idCart' => '35',
    'idCurrency' => '1',
    'idLang' => '1',
    'idCustomer' => '6',
    'idCarrier' => '4',
    'currentState' => '1',
    'module' => 'ps_wirepayment',
    'invoiceNumber' => '1',
    'deliveryNumber' => 'HGFJT5UJG79YGU',
    'valid' => '1',
    'shippingNumber' => 'QG89GPPCVMEIN14OMR4M21',
    'payment' => 'Pago por transferencia bancaria',
    'totalDiscounts' => '0',
    'totalPaid' => '385.82',
    'totalPaidReal' => '385.82',
    'totalProducts' => '350.19',
    'totalProductsWt'=> '260.19',
    'totalShipping' => '15',
    'conversionRate' => '1',
    'reference' => 'VDYLRLKDF'
  ),
  array( // products
    array(
      'id' => '114',
      'attributeId' => '0',
      'quantity' => '1',
      'name' => 'TARJETA DE VÍDEO EVGA GTX 1660 SUPER SC ULTRA GAMING 6GB GDDR6 HDMI DP',
      'sku' => '06G-P4-1068-KR',
      'ean' => '4250812435125',
      'price' => '26100000.70'
    ),
    array(
      'id' => '73',
      'attributeId' => '0',
      'quantity' => '1',
      'name' => 'ENSO BLACK TEMPERED GLASS ALCHEMY 3.0 AURA SYNC RGB W CONT',
      'sku' => 'BFC-ENS-150-KKWGK-RP',
      'ean' => '4712883216602',
      'price' => '9800000.60'
    ),
    array(
      'id' => '70',
      'attributeId' => '0',
      'quantity' => '1',
      'name' => 'GAMMAXX 400 AIR COOLER AM4 AM3+ INTEL XXX LED BLUE',
      'sku' => 'DP-MCH4-GMX400',
      'ean' => '6933412708131',
      'price' => '2500000.52'
    )
  )
);
```

And i've read a lot of this endpoint but don't find any problem

Prestashop version: 1.7.6.3
Php version: 7.0.0
Mysql Version: 5.6.41-84.1 - Percona Server (GPL), Release 84.1, Revision b30861

**Comment by khouloudbelguith** [comment]
Hi @P41N3ST,

I  did not manage to reproduce the issue using PS1.7.6.8.
I used this script

```php
<?php
ini_set('display_errors', 'on');
define('DEBUG', true);
define('PS_SHOP_PATH', 'http://shop.com');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');
$ws = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = $ws->get(array('url' => PS_SHOP_PATH . '/api/orders?schema=blank'));
//$order = $xml->addChild('order');

$xml->children()->children()->id_address_delivery= 2;
$xml->children()->children()->id_address_invoice= 2;
$xml->children()->children()->id_cart= 33;
$xml->children()->children()->id_currency =1;
$xml->children()->children()->id_lang =1;
$xml->children()->children()->id_customer = 2;
$xml->children()->children()->id_carrier= 2;
$xml->children()->children()->current_state =1;
$xml->children()->children()->module ='ps_checkpayment';
$xml->children()->children()->date_add = '2020-09-07 17:20:52';
$xml->children()->children()->date_upd = '2020-09-07 17:20:52';
$xml->children()->children()->id_shop_group = 1;
$xml->children()->children()->id_shop =1 ;
$xml->children()->children()->secure_key = '39d384484f8d7659725f76407c29f2e4';
$xml->children()->children()->payment = 'Payment by check';
$xml->cTHankshildren()->children()->total_paid = 39.460000;
$xml->children()->children()->total_paid_tax_incl = 39.460000 ;
$xml->children()->children()->total_paid_tax_excl = 39.460000;
$xml->children()->children()->total_paid_real =  0.000000;
$xml->children()->children()->total_products = 34.460000;
$xml->children()->children()->total_products_wt = 34.460000;
$xml->children()->children()->total_shipping = 5.000000 ;
$xml->children()->children()->total_shipping_tax_incl = 5.000000 ;
$xml->children()->children()->total_shipping_tax_excl = 4.200000 ;
$xml->children()->children()->carrier_tax_rate = 0.000;
$xml->children()->children()->total_wrapping =0.000000;
$xml->children()->children()->total_wrapping_tax_incl = 0.000000;
$xml->children()->children()->total_wrapping_tax_excl =0.000000;
$xml->children()->children()->conversion_rate = 1.000000 ;
$xml->children()->children()->reference ='OWSBTSTAB';

$opt = array(
    'resource' => 'orders',
    'postXml' => $xml->asXML(),
);

$xml = $ws->add($opt);
```

Thanks to check and feedback.

**Comment by QueeNFrisk** [comment]
Neither can I replicate it or solve it. But here is my output

```Json
{
  "id":{ },
  "id_address_delivery":"6",
  "id_address_invoice":"6",
  "id_cart":"35",
  "id_currency":"1",
  "id_lang":"1",
  "id_customer":"6",
  "id_carrier":"4",
  "current_state":{ },
  "module":"ps_wirepayment",
  "invoice_number":{ },
  "invoice_date":{ },
  "delivery_number":{ },
  "delivery_date":{ },
  "valid":{ },
  "date_add":{ },
  "date_upd":{ },
  "shipping_number":{ },
  "id_shop_group":{ },
  "id_shop":{ },
  "secure_key":{ },
  "payment":"Pago por transferencia bancaria",
  "recyclable":{ },
  "gift":{ },
  "gift_message":{ },
  "mobile_theme":{ },
  "total_discounts":{ },
  "total_discounts_tax_incl":{ },
  "total_discounts_tax_excl":{ },
  "total_paid":"385.82",
  "total_paid_tax_incl":{ },
  "total_paid_tax_excl":{ },
  "total_paid_real":"385.82",
  "total_products":"350.19",
  "total_products_wt":"260.19",
  "total_shipping":{ },
  "total_shipping_tax_incl":{ },
  "total_shipping_tax_excl":{ },
  "carrier_tax_rate":{ },
  "total_wrapping":{ },
  "total_wrapping_tax_incl":{ },
  "total_wrapping_tax_excl":{ },
  "round_mode":{ },
  "round_type":{ },
  "conversion_rate":"1",
  "reference":"VDYLRLKDF",
  "associations":{
    "order_rows":{
      "order_row":[
        {
          "id":{ },
          "product_id":"114",
          "product_attribute_id":"0",
          "product_quantity":"1",
          "product_name":"TARJETA DE V\u00cdDEO EVGA GTX 1660 SUPER SC ULTRA GAMING 6GB GDDR6 HDMI DP",
          "product_reference":"06G-P4-1068-KR",
          "product_ean13":"4250812435125",
          "product_isbn":{ },
          "product_upc":{ },
          "product_price":"261.70",
          "id_customization":{ },
          "unit_price_tax_incl":{ },
          "unit_price_tax_excl":{ }
        },
        {
          "product_id":"73",
          "product_attribute_id":"0",
          "product_quantity":"1",
          "product_name":"ENSO BLACK TEMPERED GLASS ALCHEMY 3.0 AURA SYNC RGB W CONT",
          "product_reference":"BFC-ENS-150-KKWGK-RP",
          "product_ean13":"4712883216602",
          "product_price":"98.60"
        },
        {
          "product_id":"70",
          "product_attribute_id":"0",
          "product_quantity":"1",
          "product_name":"GAMMAXX 400 AIR COOLER AM4 AM3+ INTEL XXX LED BLUE",
          "product_reference":"DP-MCH4-GMX400",
          "product_ean13":"6933412708131",
          "product_price":"25.52"
        }
      ]
    }
  }
}
```

**Comment by khouloudbelguith** [comment]
@P41N3ST, so the issue is not reproduced anymore?

Thanks!

**Comment by QueeNFrisk** [comment]
Occurs, but i cannot reproduce it in another installation

**Comment by QueeNFrisk** [comment]
The error on postman

![image](https://user-images.githubusercontent.com/11914764/95773657-84503f00-0c84-11eb-97cf-cb895ac1e2bd.png)

**Comment by khouloudbelguith** [comment]
@P41N3ST,

The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.
The creation of an order via WS is ok.
You can follow this [comment](https://github.com/PrestaShop/PrestaShop/issues/19906#issuecomment-688426679), just `id_carrier` and `total_shipping` are wrong during the creation of the order.

Thanks!

**Comment by QueeNFrisk** [comment]
I couldn't get it to work, I made the decision to make another prestashop api

But thank you so much for your help.
