### ISSUE TITLE
1.7.6.9 -> 1.7.7.1: Some DB Columns are missed

### ISSUE THREAD

**Issue by indaco** [PrestaShop/PrestaShop#22881]
Upgrading to 1.7.7.1 I got the following error:

**Autoupgrade Logs**

```
[2021-01-18 11:05:14] [INTERNAL] /Users/user1/Sites/sitenamehere.local/vendor/doctrine/common/lib/Doctrine/Common/Proxy/Exception/UnexpectedValueException.php line 41 - Doctrine\Common\Proxy\Exception\UnexpectedValueException: The type hint of parameter "lang" in method "setLang" in class "PrestaShop\Module\TextTranslate\Entity\Translation" is invalid.
#0 /Users/user1/Sites/sitenamehere.local/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php(1086): Doctrine\Common\Proxy\Exception\UnexpectedValueException::invalidParameterTypeHint('PrestaShop\\Modu...', 'setLang', 'lang')
#1 /Users/user1/Sites/sitenamehere.local/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php(989): Doctrine\Common\Proxy\ProxyGenerator->formatType(Object(ReflectionNamedType), Object(ReflectionMethod), Object(ReflectionParameter))
#2 /Users/user1/Sites/sitenamehere.local/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php(954): Doctrine\Common\Proxy\ProxyGenerator->getParameterType(Object(ReflectionParameter))
#3 /Users/user1/Sites/sitenamehere.local/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php(796): Doctrine\Common\Proxy\ProxyGenerator->buildParametersString(Array)
#4 [internal function]: Doctrine\Common\Proxy\ProxyGenerator->generateMethods(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /Users/user1/Sites/sitenamehere.local/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php(270): call_user_func(Array, Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /Users/user1/Sites/sitenamehere.local/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php(152): Doctrine\Common\Proxy\ProxyGenerator->generateProxyClass(Object(Doctrine\ORM\Mapping\ClassMetadata), '/Users/user1/Si...')
#7 /Users/user1/Sites/sitenamehere.local/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php(70): Doctrine\Common\Proxy\AbstractProxyFactory->generateProxyClasses(Array)
#8 /Users/user1/Sites/sitenamehere.local/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php(52): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp('/Users/user1/Si...')
#9 /Users/user1/Sites/sitenamehere.local/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(686): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp('/Users/user1/Si...')
#10 /Users/user1/Sites/sitenamehere.local/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#11 /Users/user1/Sites/sitenamehere.local/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot()
#12 /Users/user1/Sites/sitenamehere.local/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel()
#13 /Users/user1/Sites/sitenamehere.local/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants()
#14 /Users/user1/Sites/sitenamehere.local/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade()
#15 /Users/user1/Sites/sitenamehere.local/z0ll4t0yz4dm1n20/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run()
#16 {main}
```

#### 1. The left menu in BO disappeared

Fixed as per #22250 

```sql
ALTER TABLE `PREFIX_tab` ADD `enabled` TINYINT(1) NOT NULL DEFAULT '1' AFTER `active`;
```

#### 2. SHOP HOMEPAGE: Unknown column 'ocr.deleted'

For the query:
```sql
SELECT COUNT(*) FROM `ps_orders` o LEFT JOIN `ps_order_cart_rule` ocr ON (ocr.`id_order` = o.`id_order`) WHERE o.`id_customer` = 0 AND ocr.`deleted` = 0 AND ocr.`id_cart_rule` = 2 LIMIT 1
```

Fixed with:

```sql
ALTER TABLE `PREFIX_order_cart_rule` ADD `deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' AFTER `free_shipping`;
```

####  3. SHOP HOMEPAGE: Unknown column ‘pa.mpn’ in ‘field list’

For the query below:

```sql
SELECT a.`id_attribute`, a.`id_attribute_group`, al.`name`, agl.`name` as `group`, pa.`reference`, pa.`ean13`, pa.`isbn`, pa.`upc`, pa.`mpn` 
FROM `ps_attribute` a LEFT JOIN `ps_attribute_lang` al ON (al.`id_attribute` = a.`id_attribute` AND al.`id_lang` = 2) LEFT JOIN `ps_product_attribute_combination` pac ON (pac.`id_attribute` = a.`id_attribute`) LEFT JOIN `ps_product_attribute` pa ON (pa.`id_product_attribute` = pac.`id_product_attribute`) INNER JOIN ps_product_attribute_shop product_attribute_shop ON (product_attribute_shop.id_product_attribute = pa.id_product_attribute AND product_attribute_shop.id_shop = 1) LEFT JOIN `ps_attribute_group_lang` agl ON (a.`id_attribute_group` = agl.`id_attribute_group` AND agl.`id_lang` = 2) WHERE pa.`id_product` = 6028854 AND pac.`id_product_attribute` = 1234 AND agl.`id_lang` = 2
```

Fixed with:

```sql
ALTER TABLE `PREFIX_product_attribute` ADD `mpn` VARCHAR(40) AFTER `upc`;
```

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2.34
* Autoupgrade module: fresh new installation

**Comment by hibatallahAouadni** [comment]
Hello @indaco 

Thanks for your well detailed report.
Ping @PrestaShop/prestashop-core-developers @PrestaShop/prestashop-maintainers I think it's says all :clap: he didn't miss any detail about the Autoupgrade issues.

Thanks!

**Comment by PierreRambaud** [comment]
These sql requests are already in the 1.7.7.0.sql file. And other are related to doctrine update.
You should check your errors logs in case something failed during the database upgrade.

**Comment by nsanelab** [comment]
Thanks for your response. That one was the only error I got during the upgrade process and the only one within the log file for the autoupgrade module. 

I run it on a different PS instance and it worked well without any errors. 

Do not know why it happened on the initial instance where I run the upgrade.

**Comment by indaco** [comment]
Thanks for your proper response. 
That error was the only one I got during the upgrade process and the only one present within the log file for the autoupgrade module.

FYI, I run it again on a different PS instance and worked with no errors.
Do not know what happened on the initial instance and why I had to do some stuff manually.

If you like, you can close this.
Thanks

**Comment by PierreRambaud** [comment]
The magic of the PHP world :sweat_smile:

**Comment by matks** [comment]
@PierreRambaud You have been detected by @matks's PHP defender troops. We do not forgive. We do not forget. Expect us.

**Comment by PierreRambaud** [comment]
Please @hibatallahAouadni be sure you're able to reproduce the issue :)

**Comment by hibatallahAouadni** [comment]
Hello @PierreRambaud 

When I upgraded from 1.7.6.9 to 1.7.7.0, the only issue I encountred is #22250
From 1.7.6.9 to 1.7.7.1, I didn't encounter any issue :tada: everything works perfectly (I attached my log file)
[log.txt](https://github.com/PrestaShop/PrestaShop/files/5843358/log.txt)

Thanks!

**Comment by PierreRambaud** [comment]
IF we are not able to reproduce, I'm not sure we can do something.
@indaco if you can provide us more information or a way to fix it, please create a pull request :)

**Comment by indaco** [comment]
@PierreRambaud unfortunately I cannot reproduce it.

The way I fixed it is already on my initial message.
