### ISSUE TITLE
ps_crossselling : Smarty cache clearing can break payment flow

### ISSUE THREAD

**Issue by Matt75** [PrestaShop/PrestaShop#24338]
#### Describe the bug

The module https://github.com/PrestaShop/ps_crossselling generate a lot of cache files on filesystem and clear cache at every order status change causing poor performances and issues during checkout.

It generate a lot of cache files due to cache key used, that's contains every id_product in current cart https://github.com/PrestaShop/ps_crossselling/blob/v2.0.1/ps_crossselling.php#L190

It clear cache at every order status changes
https://github.com/PrestaShop/ps_crossselling/blob/v2.0.1/ps_crossselling.php#L108

That's cause poor performances and sometime issues during checkout when PrestaShop doing the order create process.

#### Expected behavior

Avoid clear cache on Order Status change and stop generate too much cache files on filesystem.

#### Steps to Reproduce

Very hard to reproduce so don't loose time to try, it require a shop with many users at same time to create reproductible conditions

1. Install https://github.com/PrestaShop/ps_crossselling
2. Have a lot of files in cache on filesystem (Add product to cart, go to cart page, repeat multiple times)
3. Have some concurrent process on filesystem
4. Make a payment
5. If you're unlucky you will encountered an error 500

**Stack trace**

```
UnexpectedValueException: RecursiveDirectoryIterator::__construct(/app/cache/prod/smarty/cache/ps_crossselling/19469/1/1/1/1/1/10/4e/42): failed to open dir: No such file or directory
#17 vendor/prestashop/smarty/sysplugins/smarty_internal_cacheresource_file.php(196): __construct
#16 [Anonymous function](0): getChildren
#15 vendor/prestashop/smarty/sysplugins/smarty_internal_cacheresource_file.php(196): clear
#14 vendor/prestashop/smarty/Smarty.class.php(845): clearCache
#13 classes/Tools.php(3021): clearCache
#12 classes/module/Module.php(2391): _clearCache
#11 modules/ps_crossselling/ps_crossselling.php(115): _clearCache
#10 modules/ps_crossselling/ps_crossselling.php(110): hookActionOrderStatusPostUpdate
#9 classes/Hook.php(924): coreCallHook
#8 classes/Hook.php(328): callHookOn
#7 classes/Hook.php(860): exec
#6 classes/order/OrderHistory.php(403): changeIdOrderState
#5 classes/PaymentModule.php(737): validateOrder
#4 modules/ps_checkout/src/ValidateOrder.php(195): validateOrder
#3 modules/ps_checkout/controllers/front/validate.php(121): postProcess
#2 classes/controller/Controller.php(242): run
#1 classes/Dispatcher.php(428): dispatch
#0 index.php(28): null
```

#### Additional information

Reported by Sentry
* PrestaShop version: 1.7.3.3
* PHP version: 7.1.33

**Comment by hibatallahAouadni** [comment]
Hello @Matt75 

It seems your issue is similar to this one #20874
And your PS version is 1.7.3.3 or 1.7.7.3?

> If you're unlucky you will encountered an error 500

Well, I tried a few times but couldn't reproduce it (I think I'm lucky :grin: )
Please check and feedback.

Thanks!

**Comment by Matt75** [comment]
Hi @hibatallahAouadni 

Both issues has common issue with performances but my issue is the module break the order process after payment.
So customer has paid but no order created in PrestaShop or order has been created but with inconsistancies...

**Comment by Matt75** [comment]
We have a merchant with more 50 orders not created after payments every days !
So I made a Pull Request on this module because Sentry reports keep going.

**Comment by lmeyer1** [comment]
@kpodemski  
I think there are two flaws that combined give this issue:
- The cache key is not well calculated. Currently all product ids are concatenated, not even in a specific order. This can indeed lead to an explosion of the number of cached templates. Given 1000 articles, a max of 3 articles per cart, and the max number of templates is 1000 + 2 * 1000 ^2 + 3 ! * 1000 ^3 = 6002001000 files !
- There is no need to empty the cache on every order state update. 

The solution to the latter is what @Matt75 implemented (remove `actionOrderStatusPostUpdate` hook and replace with `actionObjectProductUpdateAfter` and `actionObjectProductDeleteAfter` hook).
The solution to the former is to never cache a template, if there are more than one product_id. This allows to cache the results on the product detail page, while avoiding the issue stated above.

Do you think there are other things to take into account about this performance issue?

**Comment by boo-code** [comment]
Both halves still reproduce on `dev` (2.0.3), and `ps_crossselling#43` by @lmeyer1 is open against exactly this - stale since 2023-06 and currently conflicting, which is probably why it never landed. Rather than duplicate it, here are measurements, since the thread has none and the remaining disagreement is a design choice rather than a diagnosis.

Measured on a 9.2 shop, `dev` versus `dev` plus a local patch, same shop both times:

| | product page | cart page, 21 distinct baskets | Shipped -> Delivered | Delivered -> Payment error |
| --- | --- | --- | --- | --- |
| `dev` | 1 file / 11 dirs | 6 files / 63 dirs | cache dropped | cache dropped |
| patched | 1 file / 11 dirs | 0 / 0 | cache kept | cache dropped |

**On the cache key, #43 is right and my patch agrees with it line for line.** `getCacheIdKey()` joins every product id in the cart, so two shoppers share an entry only if their baskets hold exactly the same products. The hit rate is near zero while each distinct basket costs a write and a directory tree - which is the shape of the 500 reported here, a `RecursiveDirectoryIterator` opening a directory another process had just removed. #43 returns `null` from `getCacheIdKey()` above one product; I arrived at the same condition independently. The product-page column is the control that this leaves the useful cache alone.

**On the invalidation the two differ, and this is the part worth a decision.** #43 removes the `actionOrderStatusPostUpdate` registration entirely and replaces it with a `CROSSSELLING_CACHE_LIFE` TTL, default 86400, plus a manual clear button. The alternative is to keep the hook and narrow it: the recommendations come only from valid orders - `getOrderProducts()` filters on `o.valid = 1`, and `OrderHistory` sets `$order->valid = $new_os->logable` - so a transition that leaves `logable` alone cannot change a single recommendation. Shipped to Delivered, both `logable = 1`, was clearing the cached block of every product in the order for nothing, while Delivered to Payment error genuinely does change the set. That is the last two columns above.

The trade-off, stated plainly: the TTL removes invalidation cost entirely but lets a recommendation be up to a day stale and adds a setting; the narrowed hook keeps recommendations exact and adds no configuration, at the cost of still doing per-product clears on the transitions that matter. Both fix the reported 500, because both stop the cart-page churn.

@Matt75 the reproduction note says not to waste time trying - the two probes behind that table make it deterministic without concurrency, by counting cache entries after N distinct baskets and after a status change, rather than waiting for the race.

One caveat for anyone re-measuring: my first attempt compared the shop's installed build against `dev` plus the patch, and those differ by more than the patch - the installed build declares `min 1.7.2.0` and carries a `_clearCache()` override that `dev` does not. The table is `dev` against `dev` + patch.
