### ISSUE TITLE
Upgrade failed with error: Cache key must be string, "NULL" given

### ISSUE THREAD

**Issue by psyray** [PrestaShop/PrestaShop#25671]
#### Describe the bug

While upgrading database from 1.7.5.2 to 1.7.7.6 from command line with `php install/upgrade/upgrade.php` upgrade failed with this message
```
PHP Fatal error:  Uncaught Symfony\Component\Cache\Exception\InvalidArgumentException: Cache key must be string, "NULL" given in /var/www/vhosts/xxx/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Cache/CacheItem.php:162
Stack trace:
#0 /var/www/vhosts/xxx/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/AbstractTrait.php(235): Symfony\Component\Cache\CacheItem::validateKey(NULL)
#1 /var/www/vhosts/xxx/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php(156): Symfony\Component\Cache\Adapter\AbstractAdapter->getId(NULL)
#2 /var/www/vhosts/xxx/httpdocs/src/Core/Localization/CLDR/DataLayer/LocaleCache.php(82): Symfony\Component\Cache\Adapter\AbstractAdapter->getItem(NULL)
#3 /var/www/vhosts/xxx/httpdocs/src/Core/Data/Layer/AbstractDataLayer.php(90): PrestaShop\PrestaShop\Core\Localization\CLDR\DataLayer\LocaleCache->doRead(NULL)
#4 /var/www/vhosts/xxx/httpdocs/src/Core/Localization/CLDR/LocaleDataSource.php(62): in /var/www/vhosts/xxx/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Cache/CacheItem.php on line 162

```

#### Expected behavior

Database upgrade should run fine

#### Steps to Reproduce

Firstly you need two 1.7.5.2 version (local and dev - with GIT versioning)
1. In local environment make and upgrade from 1.7.5.2 to 1.7.7.6 with 1 click upgrade
2. Push files with git to dev environment (version 1.7.5.2)
3. In dev env execute `php install/upgrade/upgrade.php`
4. See errors above

#### Where the problem comes

Problem comes from `ps_1761_update_currencies.php` upgrade script.
This script relies on `Context` to get the current locale, but, and I don't know why, it returns null.
Context does not seems to contains all vallues.
![image](https://user-images.githubusercontent.com/1230954/130339906-d5438da1-2e79-4953-94f5-fd6bbbf96f4d.png)

Problem located in line https://github.com/PrestaShop/PrestaShop/blob/30f668874fdc21d55eecb5a8fda6a48af317fe28/install-dev/upgrade/php/ps_1761_update_currencies.php#L53

#### Try

I've tried changing this line from 
```php
$cldrLocale = $localeRepoCLDR->getLocale($context->language->getLocale());
```
to
```php
$cldrLocale = $localeRepoCLDR->getLocale('fr');
```

Upgrade will finish fine, but other errors occurs later related to Twig while displaying admin page (order...).
So it's not good.
The upgrade script does not get the correct Context object, so database contains bad CLDR datas, and website is buggy after.

Somebody could tell me why my database upgrade from command line did not get the correct context ?
It's a multistore install

#### Additional information

* PrestaShop version: 1.7.5.2 & 1.7.7.6 
* PHP version: 7.2.34

**Comment by psyray** [comment]
Seems that the problem comes from this hardcoded value **1** in the `initContext` method
https://github.com/PrestaShop/PrestaShop/blob/76d89d7833644e461be72f131cca6de43d5a8d99/src/PrestaShopBundle/Install/Upgrade.php#L302

In my database, there is no shop assigned to the `PS_LANG_DEFAULT` value, maybe because I'm in multistore context
![image](https://user-images.githubusercontent.com/1230954/130425882-75022ea3-e50a-483a-af11-8372c4d24ce8.png)

I think you should do more checks to be sure that language is loaded
https://github.com/PrestaShop/PrestaShop/blob/76d89d7833644e461be72f131cca6de43d5a8d99/src/PrestaShopBundle/Install/Upgrade.php#L305-L308
After I execute this query
```sql
INSERT INTO `ps_configuration` (`id_configuration`, `id_shop_group`, `id_shop`, `name`, `value`, `date_add`, `date_upd`) VALUES ('0', '1', '1', 'PS_LANG_DEFAULT', '1', '2018-11-25 23:37:10', '2018-11-25 23:37:10');
```
![image](https://user-images.githubusercontent.com/1230954/130426640-9ba31b63-29c0-4a03-9d08-18eae22cc296.png)
Language are correctly loaded

Same problem for the `PS_COUNTRY_DEFAULT` value
https://github.com/PrestaShop/PrestaShop/blob/76d89d7833644e461be72f131cca6de43d5a8d99/src/PrestaShopBundle/Install/Upgrade.php#L309-L313

```sql
INSERT INTO `ps_configuration` (`id_configuration`, `id_shop_group`, `id_shop`, `name`, `value`, `date_add`, `date_upd`) VALUES ('0', '1', '1', 'PS_COUNTRY_DEFAULT', '8', '2018-11-25 23:37:10', '2018-11-25 23:37:10');
```

**Comment by psyray** [comment]
And last but not least, the `updateLangs()` method failed 
https://github.com/PrestaShop/PrestaShop/blob/76d89d7833644e461be72f131cca6de43d5a8d99/src/PrestaShopBundle/Install/Upgrade.php#L838
With the same problem of bad configuration check
https://github.com/PrestaShop/PrestaShop/blob/76d89d7833644e461be72f131cca6de43d5a8d99/src/PrestaShopBundle/Install/Upgrade.php#L761
But this time the check is done **without the shop** (because in the `initContext` - see my previous message - the context is initialized with a shop hardcoded of **1**) and in my database there was a record **with the shop** which is introduced within the update of the 1.7.6.0 in the `ps_1760_update_configuration.php` file
![image](https://user-images.githubusercontent.com/1230954/130451176-e1389c87-fc7f-4e96-a895-d0d9af6dc9ba.png)

https://github.com/PrestaShop/PrestaShop/blob/ddcd3e3ad05b559ee7e1194c8054e0d6b2974eba/install-dev/upgrade/php/ps_1760_update_configuration.php#L32
So, this time again, the configuration returns `null` and this method fails, making the update fails with code **44** - [According to the docs](https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/#error-codes) error is: `Error #44: Error while updating translations.`
https://github.com/PrestaShop/PrestaShop/blob/ddcd3e3ad05b559ee7e1194c8054e0d6b2974eba/src/PrestaShopBundle/Install/Upgrade.php#L747-L782

Executing this query (with the 2 from my precedent message), **before the upgrade process** solve the problem, and db upgrade finish correctly with an ok message `<?xml version="1.0" encoding="UTF-8"?><action result="ok" id="">`
```sql
INSERT INTO `ps_configuration` (`id_configuration`, `name`, `value`, `date_add`, `date_upd`) VALUES ('0', 'PS_MAIL_THEME', 'modern', '2021-08-23 14:07:47', '2021-08-23 14:07:47');
```
I think this problem is only related to multistore configuration

**Comment by hibatallahAouadni** [comment]
Hello @psyray 

After testing the issue in multiple ways with @florine2623, here's the results:

- Upgrading a shop `1.7.5.2 stable version `with the module `1-Click upgrade` => Done :heavy_check_mark: 
- Upgrading a shop `1.7.5.2 tag` (cloned from Git) with `manual upgrade` => Error :x: 

![image](https://user-images.githubusercontent.com/23308427/130594151-dc11cde3-5faa-4789-aad0-2145e29fd5f9.png)

As the `ps_currency_lang` table doesn't exist:

![image](https://user-images.githubusercontent.com/23308427/130594203-06f3fbd3-f83d-4af7-8f80-8050b8810147.png)

Upgrading a shop `1.7.5.2 stable version` with `manual upgrade` => Error :x: 

![image](https://user-images.githubusercontent.com/23308427/130598306-d9cf078e-a7a2-443d-ba45-cb76612caf34.png)

I was able to reproduce the issue. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

PS: we should add a request in the `manual upgrade` to create this new table `ps_currency_lang`
PS: we didn't reproduce this issue with any `177` version (check this issue #25303)

Thank you

**Comment by psyray** [comment]
Thanks for testing ;)
I confirm that 1 click upgrade is working fine for me also

**Comment by ga-devfront** [comment]
I am closing this ticket because the manual upgrade no longer exists, the only way to update now is to use the update assistant (compatible from 1.7 to version 9).
