### ISSUE TITLE
prestashop 1.7.6.5 upgrade to 1.7.7.7 ajax server error / PHP Fatal error: Uncaught Error: Class 'League\\Tactician\\Bundle\\TacticianBundle' not found

### ISSUE THREAD

**Issue by ibrahimfsasmaz** [PrestaShop/PrestaShop#25809]
hello,

I am having the error below while upgrading 1.7.6.5 to 1.7.7.7

```
"....
All files upgraded. Now upgrading database...
[Ajax / Server Error for action upgradeDb] textStatus: "error " errorThrown:" " jqXHR: "
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.25 (Debian) Server at prestashop-656835-2143685.cloudwaysapps.com Port 80
"


the detail is like below

"[Tue Sep 07 18:44:12.907977 2021] [proxy_fcgi:error] [pid 18230:tid 140315943843584] [client 212.2.212.147:17798] AH01071: Got error 'PHP message: PHP Warning: include(/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/composer/../league/tactician-bundle/TacticianBundle.php): failed to open stream: No such file or directory in /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/composer/ClassLoader.php on line 444\nPHP message: PHP Warning: include(/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/composer/../league/tactician-bundle/TacticianBundle.php): failed to open stream: No such file or directory in /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/composer/ClassLoader.php on line 444\nPHP message: PHP Warning: include(): Failed opening '/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/composer/../league/tactician-bundle/TacticianBundle.php' for inclusion (include_path='/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/pear/pear_exception:/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/pear/console_getopt:/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/pear/pear-core-minimal/src:/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/pear/archive_tar:.:/usr/share/php') in /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/composer/ClassLoader.php on line 444\nPHP message: PHP Fatal error: Uncaught Error: Class 'League\\Tactician\\Bundle\\TacticianBundle' not found in /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/app/AppKernel.php:59\nStack trace:\n#0 /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(488): AppKernel->registerBundles()\n#1 /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\\Component\\HttpKernel\\Kernel->initializeBundles()\n#2 /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(195): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/adminpanel/index.php(86): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, false)\n#4 {main}\n thrown in /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/app/AppKernel.php on line 59\n', referer: https://prestashop-656835-2143685.cloudwaysapps.com/adminpanel/index.php?tab=AdminSelfUpgrade&token=7f806be2542436615a0548cd32633429"
```

how can I fix that pls ?

`PHP Fatal error: Uncaught Error: Class 'League\\Tactician\\Bundle\\TacticianBundle' not found`

**Comment by hibatallahAouadni** [comment]
Hello @ibrahimfsasmaz 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by ibrahimfsasmaz** [comment]
this is a problem about prestashop core upgrade, means that there is a bug at 1-click upgrade

**Comment by hibatallahAouadni** [comment]
Hello @ibrahimfsasmaz 

> this is a problem about prestashop core upgrade, means that there is a bug at 1-click upgrade

To confirm this sentence, we need steps to reproduce the issue.

Thanks for understanding.
