### ISSUE TITLE
 error upgrading 1.7.6.5 to 1.7.7.7 with 1-click upgrade

### ISSUE THREAD

**Issue by ibrahimfsasmaz** [PrestaShop/PrestaShop#25821]
hello,

I am having the error below while upgrading 1.7.6.5 to 1.7.7.7
```

"....
All files upgraded. Now upgrading database...
[Ajax / Server Error for action upgradeDb] textStatus: "error " errorThrown:" " jqXHR: "
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.25 (Debian) Server at prestashop-656835-2143685.cloudwaysapps.com Port 80
"


the detail is like below

"[Tue Sep 07 18:44:12.907977 2021] [proxy_fcgi:error] [pid 18230:tid 140315943843584] [client 212.2.212.147:17798] AH01071: Got error 'PHP message: PHP Warning: include(/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/composer/../league/tactician-bundle/TacticianBundle.php): failed to open stream: No such file or directory in /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/composer/ClassLoader.php on line 444\nPHP message: PHP Warning: include(/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/composer/../league/tactician-bundle/TacticianBundle.php): failed to open stream: No such file or directory in /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/composer/ClassLoader.php on line 444\nPHP message: PHP Warning: include(): Failed opening '/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/composer/../league/tactician-bundle/TacticianBundle.php' for inclusion (include_path='/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/pear/pear_exception:/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/pear/console_getopt:/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/pear/pear-core-minimal/src:/home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/pear/archive_tar:.:/usr/share/php') in /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/composer/ClassLoader.php on line 444\nPHP message: PHP Fatal error: Uncaught Error: Class 'League\\Tactician\\Bundle\\TacticianBundle' not found in /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/app/AppKernel.php:59\nStack trace:\n#0 /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(488): AppKernel->registerBundles()\n#1 /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\\Component\\HttpKernel\\Kernel->initializeBundles()\n#2 /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(195): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/adminpanel/index.php(86): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, false)\n#4 {main}\n thrown in /home/656835.cloudwaysapps.com/qndngdkwzh/public_html/app/AppKernel.php on line 59\n', referer: https://prestashop-656835-2143685.cloudwaysapps.com/adminpanel/index.php?tab=AdminSelfUpgrade&token=7f806be2542436615a0548cd32633429"
```
how can I fix that pls ?

`PHP Fatal error: Uncaught Error: Class 'League\\Tactician\\Bundle\\TacticianBundle' not found`

**Comment by hibatallahAouadni** [comment]
Hello @ibrahimfsasmaz 

First, you need to **follow and respect the provided template to submit a complete bug report**:

![image](https://user-images.githubusercontent.com/23308427/132643905-5a2e771c-b0de-4aff-9bc8-c65103c59b6e.png)

![image](https://user-images.githubusercontent.com/23308427/132643951-32f10ffe-3a58-448f-9e0d-a02e87a6a9b7.png)

Cause, we need these informations to reproduce your issue and to fix it ASAP!
Second, this error means that your issue is related to a Bundle that you create it called **TacticianBundle**:
`PHP Fatal error: Uncaught Error: Class 'League\\Tactician\\Bundle\\TacticianBundle' not found`
And in PrestaShop Core, as much as I know there's no TacticianBundle!

So, I'm closing the issue and when you edit your issue following the template, ping me :wink: I will reopen it.

Thanks!
