### ISSUE TITLE
1-Click Upgrade from 1.6.1.24 to 1.7.7.8 error

### ISSUE THREAD

**Issue by theMost1ted** [PrestaShop/PrestaShop#25970]
Hello, 

Can't update from 1.6.1.24 to 1.7.7.8 using the latest version of 1-Click Upgrade
```
PHP-FPM 7.1.14
Mariadb:10.0.38

[INTERNAL] /var/www/html/classes/Hook.php line 225 - PrestaShopObjectNotFoundException: The hook id #80 does not exist in database #0 /var/www/html/classes/Hook.php(660): HookCore::getNameById(80) #1 /var/www/html/classes/module/Module.php(1008): HookCore::unregisterHook(Object(BlockLayered), 80, NULL) #2 /var/www/html/classes/module/Module.php(720): ModuleCore->unregisterHook(80) #3 /var/www/html/modules/ps_facetedsearch/ps_facetedsearch.php(269): ModuleCore->uninstall() #4 /var/www/html/modules/ps_facetedsearch/ps_facetedsearch.php(272): BlockLayered->{closure}() #5 /var/www/html/modules/ps_facetedsearch/ps_facetedsearch.php(183): Ps_Facetedsearch->uninstallPrestaShop16Module() #6 /var/www/html/src/Adapter/Module/Module.php(249): Ps_Facetedsearch->install() #7 /var/www/html/src/Core/Addon/Module/ModuleManager.php(302): PrestaShop\PrestaShop\Adapter\Module\Module->onInstall() #8 /var/www/html/src/Core/Addon/Theme/ThemeManager.php(345): PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->install(NULL) #9 /var/www/html/src/Core/Addon/Theme/ThemeManager.php(226): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array) #10 /var/www/html/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(92): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic') #11 /var/www/html/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme17('classic') #12 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(687): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic') #13 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(118): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme() #14 /var/www/html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #15 /var/www/html/admin0052pitx0/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #16 {main}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/5677535/134399423-412b849d-a458-4136-bc96-75819cc4ee96.png)

* PrestaShop version: 1.6.1.24
* PHP version: 7.4.14

**Comment by hibatallahAouadni** [comment]
Hello @theMost1ted 

You should upgrade your shop and then upgrade your PHP version :wink: 
By the way, after upgrading your shop, upgrade your PHP to 7.3 cause PS1778 is not compatible to PHP 7.4 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).
Closing the issue cause it's not a PS Core bug.

Thanks!
