### ISSUE TITLE
Uncaught Error: Call to a member function getLocale()  Controller.php

### ISSUE THREAD

**Issue by ZamperSPA** [PrestaShop/PrestaShop#26339]
Today i checked file error_log file and found thousands of same errors

```
First occurrence
prestashop version:1.7.7.5

[17-Jul-2021 20:26:53 Chile/Continental] PHP Fatal error:  Uncaught Error: Call to a member function getLocale() on null in /home2/store/classes/controller/Controller.php:196
Stack trace:
#0 /home2/store/classes/controller/FrontController.php(283): ControllerCore->init()
#1 /home2/store/classes/controller/Controller.php(287): FrontControllerCore->init()
#2 /home2/store/classes/Dispatcher.php(518): ControllerCore->run()
#3 /home2//store/index.php(28): DispatcherCore->dispatch()
#4 {main}
  thrown in /home2//store/classes/controller/Controller.php on line 196
.
Thousands of same errors later...
.
Today..
[20-Oct-2021 09:18:58 Chile/Continental] PHP Fatal error:  Uncaught Error: Call to a member function getLocale() on null in /home2/store/classes/controller/Controller.php:196
Stack trace:
#0 /home2/store/classes/controller/FrontController.php(283): ControllerCore->init()
#1 /home2/store/classes/controller/Controller.php(287): FrontControllerCore->init()
#2 /home2/store/classes/Dispatcher.php(518): ControllerCore->run()
#3 /home2/store/index.php(28): DispatcherCore->dispatch()
#4 {main}
  thrown in /home2/store/classes/controller/Controller.php on line 196
[20-Oct-2021 09:18:58 Chile/Continental] PHP Fatal error:  Uncaught Error: Call to a member function getLocale() on null in /home2/store/classes/controller/Controller.php:196
Stack trace:
#0 /home2/store/classes/controller/FrontController.php(283): ControllerCore->init()
#1 /home2/store/classes/controller/Controller.php(287): FrontControllerCore->init()
#2 /home2/store/classes/Dispatcher.php(518): ControllerCore->run()
#3 /home2/store/index.php(28): DispatcherCore->dispatch()
#4 {main}
  thrown in /home2/store/classes/controller/Controller.php on line 196
```
Which may be? 

* Today PrestaShop version: 1.7.7.8
* PHP version: 7.4.24

**Comment by hibatallahAouadni** [comment]
Hello @ZamperSPA 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: you need to downgrade your PHP version to 7.3 (check our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).

Thanks!
