### ISSUE TITLE
PS 1.7.8 Context currency is null in module front controller

### ISSUE THREAD

**Issue by max-baranikov** [PrestaShop/PrestaShop#27042]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi everyone!

I have a problem that the `Context::getContext()->currency` is `null` when the **front module controller** is called
So later when module calls for `Product::getAttributeCombinationsById()` it throws an exception like: 

```
/Users/max/ps_178/src/Core/Localization/CLDR/ComputingPrecision.php: Argument 1 passed to PrestaShop\PrestaShop\Core\Localization\CLDR\ComputingPrecision::getPrecision() must be of the type int, null given, called in /Users/max/ps_178/classes/Context.php on line 489 (current job: RetailcrmIcmlEvent)

#0 /Users/max/ps_178/classes/Context.php(489): PrestaShop\PrestaShop\Core\Localization\CLDR\ComputingPrecision->getPrecision(NULL)
#1 /Users/max/ps_178/classes/Product.php(2837): ContextCore->getComputingPrecision()
#2 /Users/max/ps_178/modules/retailcrm/lib/RetailcrmCatalog.php(213): ProductCore->getAttributeCombinationsById('24', 1)
#3 /Users/max/ps_178/modules/retailcrm/lib/RetailcrmIcml.php(133): RetailcrmCatalog->getOffers()
#4 /Users/max/ps_178/modules/retailcrm/lib/RetailcrmIcml.php(103): RetailcrmIcml->addOffers(Object(Generator))
#5 /Users/max/ps_178/modules/retailcrm/lib/events/RetailcrmIcmlEvent.php(63): RetailcrmIcml->generate(Array, Object(Generator))
#6 /Users/max/ps_178/modules/retailcrm/lib/RetailcrmJobManager.php(721): RetailcrmIcmlEvent->execute()
#7 /Users/max/ps_178/modules/retailcrm/lib/RetailcrmJobManager.php(472): RetailcrmJobManager::execHere('RetailcrmIcmlEv...', false, false, NULL)
#8 /Users/max/ps_178/modules/retailcrm/lib/RetailcrmJobManager.php(185): RetailcrmJobManager::runJob('RetailcrmIcmlEv...')
#9 /Users/max/ps_178/modules/retailcrm/lib/RetailcrmJobManager.php(94): RetailcrmJobManager::execJobs(Array)
#10 /Users/max/ps_178/modules/retailcrm/lib/RetailcrmTools.php(730): RetailcrmJobManager::startJobs(Array)
#11 /Users/max/ps_178/modules/retailcrm/controllers/front/Jobs.php(81): RetailcrmTools::startJobManager()
#12 /Users/max/ps_178/modules/retailcrm/controllers/front/Jobs.php(64): RetailcrmJobsModuleFrontController->getData()
#13 /Users/max/ps_178/modules/retailcrm/controllers/front/Jobs.php(72): RetailcrmJobsModuleFrontController->initContent()
#14 /Users/max/ps_178/classes/Dispatcher.php(518): RetailcrmJobsModuleFrontController->run()
#15 /Users/max/ps_178/index.php(28): DispatcherCore->dispatch()
#16 {main}
```

I've tried to look what is inside the Context instance, and json_encode returned the following:

```
{"cart":null,"customer":{"id":null,"id_shop":null,"id_shop_group":null,"secure_key":null,"note":null,"id_gender":0,"id_default_group":1,"id_lang":null,"lastname":null,"firstname":null,"birthday":null,"email":null,"newsletter":null,"ip_registration_newsletter":null,"newsletter_date_add":null,"optin":null,"website":null,"company":null,"siret":null,"ape":null,"outstanding_allow_amount":0,"show_public_prices":0,"id_risk":null,"max_payment_days":0,"passwd":null,"last_passwd_gen":null,"active":true,"is_guest":0,"deleted":0,"date_add":null,"date_upd":null,"years":null,"days":null,"months":null,"geoloc_id_country":null,"geoloc_id_state":null,"geoloc_postcode":null,"logged":0,"id_guest":"3","groupBox":null,"reset_password_token":null,"reset_password_validity":null,"id_shop_list":[],"force_id":false},"cookie":{},"session":{},"link":{"protocol_link":"http://","protocol_content":"http://"},"country":{"id":175,"id_zone":"7","id_currency":"0","iso_code":"RU","call_prefix":"7","name":"Russia","contains_states":"0","need_identification_number":"0","need_zip_code":"1","zip_code_format":"NNNNNN","display_tax_label":"1","active":"1","id_shop_list":[],"force_id":false},"employee":null,"controller":{"module":{"api":{},"default_lang":1,"default_currency":1,"default_country":175,"psVersion":"1.7","log":"/Users/max/Downloads/prestashop_1/var/logs/retailcrm_web_2021_12_20.log","confirmUninstall":"Are you sure you want to uninstall?","reference":{"default_lang":1,"carriers":[{"id_carrier":"1","id_reference":"1","id_tax_rules_group":"0","name":"Dev Presta 1.7.8.1","url":"","active":"1","deleted":"0","shipping_handling":"0","range_behavior":"0","is_module":"0","is_free":"1","shipping_external":"0","need_range":"0","external_module_name":"","shipping_method":"0","position":"0","max_width":"0","max_height":"0","max_depth":"0","max_weight":"0.000000","grade":"0","delay":"Pick up in-store"},{"id_carrier":"2","id_reference":"2","id_tax_rules_group":"0","name":"My carrier","url":"","active":"1","deleted":"0","shipping_handling":"1","range_behavior":"0","is_module":"0","is_free":"0","shipping_external":"0","need_range":"0","external_module_name":"","shipping_method":"0","position":"1","max_width":"0","max_height":"0","max_depth":"0","max_weight":"0.000000","grade":"0","delay":"Delivery next day!"}],"payment_modules":[],"apiStatuses":null},"assetsBase":"http://prestashop.1781.lc/modules/retailcrm/views","id":"64","version":"3.3.4","database_version":null,"registered_version":null,"ps_versions_compliancy":{"min":"1.6.1.0","max":"1.7.8.2"},"dependencies":[],"name":"retailcrm","displayName":"Simla.com","description":"Integration module for Simla.com","author":"DIGITAL RETAIL TECHNOLOGIES SL","author_uri":"","module_key":"dff3095326546f5fe8995d9e86288491","bootstrap":false,"description_full":null,"additional_description":null,"compatibility":null,"nb_rates":null,"avg_rate":null,"badges":null,"need_instance":1,"tab":"export","active":1,"trusted":false,"warning":null,"enable_device":7,"limited_countries":[],"controllers":[],"allow_push":null,"push_time_limit":180,"multistoreCompatibility":0},"errors":[],"warning":[],"success":[],"info":[],"iso":null,"orderBy":null,"orderWay":null,"p":null,"n":null,"auth":false,"guestAllowed":false,"authRedirection":false,"ssl":false,"nb_items_per_page":null,"objectPresenter":{},"cart_presenter":{},"page_name":"module-retailcrm-Jobs","css_files":[],"js_files":[],"ajax":false,"controller_type":"modulefront","php_self":null},"override_controller_name_for_translations":null,"language":{"id":1,"name":"English (English)","iso_code":"en","locale":"en-US","language_code":"en-us","date_format_lite":"m/d/Y","date_format_full":"m/d/Y H:i:s","is_rtl":"0","active":"1","id_shop_list":[],"force_id":false},"currency":null,"currentLocale":null,"tab":null,"shop":{"id_shop_group":"1","id_category":"2","theme_name":"classic","name":"Dev Presta 1.7.8.1","color":"","active":"1","deleted":"0","physical_uri":"/","virtual_uri":"","domain":"prestashop.1781.lc","domain_ssl":"prestashop.1781.lc","theme":{},"id":1,"id_shop_list":[],"force_id":false},"smarty":{"auto_literal":true,"error_unassigned":false,"use_include_path":false,"_templateDirNormalized":true,"_joined_template_dir":"/Users/max/Downloads/prestashop_1/themes/classic/templates/","_configDirNormalized":false,"_joined_config_dir":null,"default_template_handler_func":null,"default_config_handler_func":null,"default_plugin_handler_func":null,"_compileDirNormalized":true,"_pluginsDirNormalized":false,"_cacheDirNormalized":true,"force_compile":false,"use_sub_dirs":true,"allow_ambiguous_resources":false,"merge_compiled_includes":false,"extends_recursion":true,"force_cache":false,"left_delimiter":"{","right_delimiter":"}","literals":[],"security_class":"Smarty_Security","security_policy":null,"php_handling":0,"allow_php_templates":false,"debugging":false,"debugging_ctrl":"NONE","smarty_debug_id":"SMARTY_DEBUG","debug_tpl":"/Users/max/Downloads/prestashop_1/themes/debug.tpl","error_reporting":null,"config_overwrite":true,"config_booleanize":true,"config_read_hidden":false,"compile_locking":true,"cache_locking":false,"locking_timeout":10,"default_resource_type":"file","caching_type":"file","default_config_type":"file","cache_modified_check":false,"registered_plugins":{"function":{"widget":[[{},"smartyWidget"],true,[]],"render":[[{},"smartyRender"],true,[]],"form_field":[[{},"smartyFormField"],true,[]],"l":["smartyTranslate",true,[]],"hook":[[{},"smartyHook"],true,[]],"dateFormat":[[{},"dateFormat"],true,[]],"url":[[{},"getUrlSmarty"],true,[]]},"block":{"widget_block":[[{},"smartyWidgetBlock"],true,[]]},"modifier":{"escape":[[{},"smartyEscape"],true,[]],"truncate":[[{},"smarty_modifier_truncate"],true,[]],"json_encode":[[{},"jsonEncode"],true,[]],"json_decode":[[{},"jsonDecode"],true,[]],"boolval":[[{},"boolval"],true,[]],"cleanHtml":[[{},"smartyCleanHtml"],true,[]],"classname":[[{},"smartyClassname"],true,[]],"classnames":[[{},"smartyClassnames"],true,[]]}},"registered_objects":[],"registered_classes":[],"registered_filters":[],"registered_resources":{"module":{"uncompiled":false,"recompiled":false,"hasCompiledHandler":false,"paths":{"theme":"/Users/max/Downloads/prestashop_1/themes/classic/modules/","modules":"/Users/max/Downloads/prestashop_1/modules/"},"isAdmin":false},"parent":{"uncompiled":false,"recompiled":false,"hasCompiledHandler":false,"paths":[]}},"registered_cache_resources":[],"autoload_filters":[],"default_modifiers":[],"escape_html":true,"start_time":1640016120.299826,"_current_file":null,"_parserdebug":false,"_objType":1,"_debug":null,"cache_id":null,"compile_id":null,"caching":false,"compile_check":false,"cache_lifetime":3600,"tplFunctions":[],"_cache":[],"template_class":"SmartyDevTemplate","tpl_vars":[],"parent":null,"config_vars":[],"ext":{"objType":1,"registerResource":{"objMap":3},"registerPlugin":{"objMap":3},"createData":{"objMap":3}}},"mobile_detect":{},"mode":null,"container":null}
```

As you can see, currency property indeed is null
If I run it from the terminal with cli.php, it works fine
If I run it from the back office it works fine as well

How can I get currency loaded in the context instance for the module front controller?

### Expected behavior

Currency object successfully received from the Context, when module Front controller is called

### Steps to reproduce

1. Install Prestashop v1.7.8.2
2. Install retailcrm module v3.3.4
3. Go to the front index page and refresh the page several times (2 at least)
4. Go to `var/logs` and open `retailcrm_web_<datetime>.log` file
5. See the error

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.3-7.4

### If your bug is related to a module, specify its name and its version

retailcrm v3.3.4

**Comment by marwachelly** [comment]
Hello,

Thanks for your report. Is this module provided by prestashop?

Thanks!

**Comment by max-baranikov** [comment]
Don't fully understand the question, but I'll try to answer

This module isn't the core module, but can be easily downloaded from the official addons marketplace here - https://addons.prestashop.com/ru/order-management/47974-simlacom.html
Oh, and it was rebranded recently, so now it called Simla.com

**Comment by hibatallahAouadni** [comment]
Hello @max-baranikov 

It seems that your issue is not a PrestaShop core bug.
Please contact support team on Addons

We will close this issue.

Thanks!

**Comment by max-baranikov** [comment]
But there's actually a core call for `ProductCore->getAttributeCombinationsById('24', 1)` which leads to the exception:

```
/Users/max/ps_178/src/Core/Localization/CLDR/ComputingPrecision.php: Argument 1 passed to PrestaShop\PrestaShop\Core\Localization\CLDR\ComputingPrecision::getPrecision() must be of the type int, null given, called in /Users/max/ps_178/classes/Context.php on line 489 (current job: RetailcrmIcmlEvent)

#0 /Users/max/ps_178/classes/Context.php(489): PrestaShop\PrestaShop\Core\Localization\CLDR\ComputingPrecision->getPrecision(NULL)
#1 /Users/max/ps_178/classes/Product.php(2837): ContextCore->getComputingPrecision()
```

Are you sure that support team on Addons cover it? Cause for me it seems like a `ContextCore` problem
Also, it works fine on previous versions of PrestaShop like 1.7.6, but crashes on 1.7.8

I can provide a minimal code example or demo module to reproduce the error if it's needed

**Comment by hibatallahAouadni** [comment]
Hello @max-baranikov 

> I can provide a minimal code example or demo module to reproduce the error if it's needed

If you can, YES please :pray: then if I reproduce the issue, I will reopen it :wink: 

Thanks!

**Comment by Laimonas-Mituzas** [comment]
Check the 'ps_cart' does the id_currency` has valid value. In my case it was "0". Changed to "1" - fixed.

**Comment by matrixino** [comment]
This is a years old bug, never fixed and still present. The currency context is never initialized in module front controllers.
