### ISSUE TITLE
prestashop.translation.translator_language_loader"

### ISSUE THREAD

**Issue by pulkitjuneja1997** [PrestaShop/PrestaShop#27786]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "prestashop.translation.translator_language_loader". in F:\xampp\htdocs\prestashop1.7.8\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Container.php:348 Stack trace: #0 F:\xampp\htdocs\prestashop1.7.8\classes\Context.php(448): Symfony\Component\DependencyInjection\Container->get('prestashop.tran...') #1 F:\xampp\htdocs\prestashop1.7.8\classes\Context.php(398): ContextCore->getTranslatorFromLocale('en-US') #2 F:\xampp\htdocs\prestashop1.7.8\classes\module\Module.php(3437): ContextCore->getTranslator() #3 F:\xampp\htdocs\prestashop1.7.8\classes\module\Module.php(3444): ModuleCore->getTranslator() #4 F:\xampp\htdocs\prestashop1.7.8\modules\ps_checkpayment\ps_checkpayment.php(64): ModuleCore->trans('Payments by che...', Array, 'Modules.Checkpa...') #5 [internal function]: Ps_Checkpayment->__construct() #6 F:\xampp\htdocs\prestashop1.7.8\src\Core\Foundation\IoC\Container.ph in F:\xampp\htdocs\prestashop1.7.8\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Container.php on line 348`

### Expected behavior

It should return an order created xml

### Steps to reproduce

1. I am sending this order xml to create order on Prestashop using webservice

```
$order_xml =    '<prestashop>
			            <order>
				            <id_address_delivery><![CDATA[4]]></id_address_delivery>
				            <id_address_invoice><![CDATA[4]]></id_address_invoice>
				            <id_cart><![CDATA[13]]></id_cart>
				            <id_currency><![CDATA[1]]></id_currency>
				            <id_lang><![CDATA[1]]></id_lang>
				            <id_customer><![CDATA[0]]></id_customer>
				            <id_carrier><![CDATA[2]]></id_carrier>
				            <current_state><![CDATA[1]]></current_state>
				            <module><![CDATA[ps_checkpayment]]></module>
				            <invoice_number><![CDATA[0]]></invoice_number>
				            <invoice_date><![CDATA[0000-00-00 00:00:00]]></invoice_date>
				            <delivery_number><![CDATA[0]]></delivery_number>
				            <delivery_date><![CDATA[0000-00-00 00:00:00]]></delivery_date>
				            <valid><![CDATA[0]]></valid>
				            <date_add><![CDATA[2022-01-10 08:59:24]]></date_add>
				            <date_upd><![CDATA[2022-01-10 08:59:27]]></date_upd>
				            <shipping_number notFilterable="true"><![CDATA[]]></shipping_number>
				            <note><![CDATA[]]></note>
				            <id_shop_group><![CDATA[1]]></id_shop_group>
				            <id_shop><![CDATA[1]]></id_shop>
				            <secure_key><![CDATA[]]></secure_key>
				            <payment><![CDATA[Payment by check]]></payment>
				            <recyclable><![CDATA[0]]></recyclable>
				            <gift><![CDATA[0]]></gift>
				            <gift_message><![CDATA[]]></gift_message>
				            <mobile_theme><![CDATA[0]]></mobile_theme>
				            <total_discounts><![CDATA[0.000000]]></total_discounts>
				            <total_discounts_tax_incl><![CDATA[0.000000]]></total_discounts_tax_incl>
				            <total_discounts_tax_excl><![CDATA[0.000000]]></total_discounts_tax_excl>
				            <total_paid><![CDATA[169.900000]]></total_paid>
				            <total_paid_tax_incl><![CDATA[169.900000]]></total_paid_tax_incl>
				            <total_paid_tax_excl><![CDATA[169.900000]]></total_paid_tax_excl>
				            <total_paid_real><![CDATA[0.000000]]></total_paid_real>
				            <total_products><![CDATA[169.900000]]></total_products>
				            <total_products_wt><![CDATA[169.900000]]></total_products_wt>
				            <total_shipping><![CDATA[0.000000]]></total_shipping>
				            <total_shipping_tax_incl><![CDATA[0.000000]]></total_shipping_tax_incl>
				            <total_shipping_tax_excl><![CDATA[0.000000]]></total_shipping_tax_excl>
				            <carrier_tax_rate><![CDATA[0.000]]></carrier_tax_rate>
				            <total_wrapping><![CDATA[0.000000]]></total_wrapping>
				            <total_wrapping_tax_incl><![CDATA[0.000000]]></total_wrapping_tax_incl>
				            <total_wrapping_tax_excl><![CDATA[0.000000]]></total_wrapping_tax_excl>
				            <round_mode><![CDATA[0]]></round_mode>
				            <round_type><![CDATA[0]]></round_type>
				            <conversion_rate><![CDATA[1.000000]]></conversion_rate>
				            <reference><![CDATA[OHSATSERP]]></reference>
				            <associations>
					            <order_rows>
						            <order_row>
							            <product_id><![CDATA[4]]></product_id>
							            <product_attribute_id><![CDATA[18]]></product_attribute_id>
							            <product_quantity><![CDATA[2]]></product_quantity>
							            <product_name><![CDATA[The adventure begins Framed poster - Size : 80x120cm]]></product_name>
							            <product_reference><![CDATA[demo_5]]></product_reference>
							            <product_price><![CDATA[79.000000]]></product_price>
							            <id_customization><![CDATA[0]]></id_customization>
							            <unit_price_tax_incl><![CDATA[79.000000]]></unit_price_tax_incl>
							            <unit_price_tax_excl><![CDATA[79.000000]]></unit_price_tax_excl>
						            </order_row>
						            <order_row>
							            <product_id><![CDATA[8]]></product_id>
							            <product_attribute_id><![CDATA[0]]></product_attribute_id>
							            <product_quantity><![CDATA[1]]></product_quantity>
							            <product_name><![CDATA[Mug Today is a good day]]</product_name>
							            <product_reference><![CDATA[demo_13]]></product_reference>
							            <product_price><![CDATA[11.900000]]></product_price>
							            <id_customization><![CDATA[0]]></id_customization>
							            <unit_price_tax_incl><![CDATA[11.900000]]></unit_price_tax_incl>
							            <unit_price_tax_excl><![CDATA[11.900000]]></unit_price_tax_excl>
						            </order_row>
					            </order_rows>
				            </associations>
					</order>
				</prestashop>';		
```	

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

**Comment by pulkitjuneja1997** [comment]
I think there is some issue in prestashop backend settings

**Comment by hibatallahAouadni** [comment]
Hello @pulkitjuneja-cedcoss 

Do you have multiple language enabled on your shop? Cause it seems your issue related to this one #27411
Please check and feedback.

Thanks!

**Comment by pulkitjuneja1997** [comment]
Hi @hibatallahAouadni thankyou for your help. This issue is solved now. I have followed this
https://github.com/PrestaShop/PrestaShop/pull/27622

**Comment by hibatallahAouadni** [comment]
@pulkitjuneja-cedcoss Glad to hear :tada:
