### ISSUE TITLE
Error with translation when sprintf doesn't contain parameters

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#31950]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you modify a translation that includes a _sprintf_ and don't define any parameter, the response is an unexpected string.

```
$this->context->smarty->assign(array(
    'var1' => 'Hi',
    'var2' => 'Bye',
));
```

```
{l s='OK: %1$s %2$s' sprintf=[$var1, $var2] d='Modules.Dummymodule.Dummy'}<br /><br />
{l s='NOK1: %1$s Text2 %2$s' sprintf=[$var1, $var2] d='Modules.Dummymodule.Dummy'}<br /><br />
{l s='NOK2: %s' sprintf=[$var1] d='Modules.Dummymodule.Dummy'}
```

Translation with the parameters removed:
![image](https://user-images.githubusercontent.com/15104724/228261303-57c1677e-b111-47f8-a8d8-39e7b2699e11.png)

Result:
![image](https://user-images.githubusercontent.com/15104724/228261410-dd89fd58-129d-4a3d-b078-9d97f89f05fc.png)

### Expected behavior

The translation should replace the variables, but keep the correct translation when the variables are removed.

### Steps to reproduce

1. Install this module
[dummymodule.zip](https://github.com/PrestaShop/PrestaShop/files/11090306/dummymodule.zip)

2. Check the translations in the home

### PrestaShop version(s) where the bug happened

8.0.2

**Comment by florine2623** [comment]
Hello @idnovate ,

I have reproduced your issue on PS `8.0.2` and `8.1.0`. I'll add this to the backlog so it can be fixed. :x:

<img width="213" alt="Screenshot 2023-03-30 at 14 16 06" src="https://user-images.githubusercontent.com/16019289/228833050-ecfb66d3-adbd-4c0a-8afc-449260ba54f7.png">

It a regression, in 1.7.8.8, it worked well : ✅ 
<img width="164" alt="Screenshot 2023-03-30 at 14 16 10" src="https://user-images.githubusercontent.com/16019289/228833027-f168bae4-dc30-4190-bc83-7f76376aa34e.png">
Tested with develop branch, it works well also. ✅ 
<img width="185" alt="Screenshot 2023-03-30 at 14 18 43" src="https://user-images.githubusercontent.com/16019289/228833519-cfbe1627-c6aa-4c6d-a7e5-0cafde974efa.png">


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by MatShir** [comment]
@idnovate do you know where the issue could come from ?

**Comment by idnovate** [comment]
> @idnovate do you know where the issue could come from ?

The problem seems to be in this function:

https://github.com/PrestaShop/PrestaShop/blob/0b2f246f731a8fc800e28d330ac3432ecce487d2/classes/Translate.php#L252-L261

The parameters received are:

`NOK1: 100.00`

```
array:2 [▼
  0 => "Hi"
  1 => "Bye"
]
```

So it replaces `1` with `Bye` and `0` with `Hi`:

`NOKBye: ByeHiHi.HiHi`

The backtrace is:

```
#0 C:\wamp64\www\ps810\classes\Translate.php(205): TranslateCore::checkAndReplaceArgs('NOK1: 100.00', Array)
#1 C:\wamp64\www\ps810\src\Adapter\Localization\LegacyTranslator.php(63): TranslateCore::getModuleTranslation('dummymodule', 'NOK1: %1$s Text...', 'dummy', Array, false, NULL, false, false) ◀
#2 C:\wamp64\www\ps810\src\PrestaShopBundle\Translation\PrestaShopTranslatorTrait.php(167): PrestaShop\PrestaShop\Adapter\Localization\LegacyTranslator->translate('dummymodule', 'NOK1: %1$s Text...', 'dummy', Array, false, NULL, false, false) ◀
#3 C:\wamp64\www\ps810\src\PrestaShopBundle\Translation\PrestaShopTranslatorTrait.php(67): PrestaShopBundle\Translation\TranslatorComponent->translateUsingLegacySystem('NOK1: %1$s Text...', Array, 'Modules.Dummymo...', NULL) ◀
#4 C:\wamp64\www\ps810\config\smartyfront.config.inc.php(223): PrestaShopBundle\Translation\TranslatorComponent->trans('NOK1: %1$s Text...', Array, 'Modules.Dummymo...') ◀
#5 C:\wamp64\www\ps810\var\cache\dev\smarty\compile\classic\98\37\d9\9837d9c70aa0c336c61d6826126062e0b41eee5c_2.file.dummy.tpl.php(26): smartyTranslate(Array, Object(SmartyDevTemplate)) ◀
#6 C:\wamp64\www\ps810\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_64d5d532b4f5b2_78008695(Object(SmartyDevTemplate))
#7 C:\wamp64\www\ps810\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) ◀
#8 C:\wamp64\www\ps810\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(SmartyDevTemplate))
#9 C:\wamp64\www\ps810\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(239): Smarty_Internal_Template->render(false, 0)
#10 C:\wamp64\www\ps810\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(SmartyDevTemplate), NULL, NULL, NULL, 0) ◀
#11 C:\wamp64\www\ps810\classes\Smarty\SmartyDevTemplate.php(55): Smarty_Internal_TemplateBase->fetch(NULL, NULL, NULL, NULL)
#12 C:\wamp64\www\ps810\classes\module\Module.php(2229): SmartyDevTemplateCore->fetch()
#13 C:\wamp64\www\ps810\modules\dummymodule\dummymodule.php(76): ModuleCore->display('C:\\wamp64\\www\\p...', 'dummy.tpl')
#14 C:\wamp64\www\ps810\classes\Hook.php(993): Dummymodule->hookDisplayHome(Array)
#15 C:\wamp64\www\ps810\classes\Hook.php(418): HookCore::coreCallHook(Object(Dummymodule), 'hookDisplayHome', Array)
#16 C:\wamp64\www\ps810\classes\Hook.php(928): HookCore::callHookOn(Object(Dummymodule), 'displayHome', Array)
#17 C:\wamp64\www\ps810\controllers\front\IndexController.php(40): HookCore::exec('displayHome')
#18 C:\wamp64\www\ps810\classes\controller\Controller.php(319): IndexControllerCore->initContent()
#19 C:\wamp64\www\ps810\classes\Dispatcher.php(510): ControllerCore->run()
#20 C:\wamp64\www\ps810\index.php(28): DispatcherCore->dispatch()
#21 {main}
```

What do you think about it? Maybe the solution is to detect if there's any sprintf placeholder (`%?`) before calling this function?

**Comment by idnovate** [comment]
@kpodemski 

Can you reopen this issue?
