### ISSUE TITLE
Module ps_facebook filling server log

### ISSUE THREAD

**Issue by PeNov** [PrestaShop/PrestaShop#33042]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello Thomas @Quetzacoalt91, 

module ps_facebook generate thousand errors in the server log.

Where could be problem?

Module version: v1.27.0

Thank you
Best regards
Petr

Log:
`[29-Jun-2023 09:43:52 Europe/Prague] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to ProductControllerCore::addProductCustomizationData() must be of the type array, bool given, called in /home/www/domain.cz/www/domain.cz/controllers/front/ProductController.php on line 1146 and defined in /home/www/domain.cz/www/domain.cz/controllers/front/ProductController.php:1297
Stack trace:
#0 /home/www/domain.cz/www/domain.cz/controllers/front/ProductController.php(1146): ProductControllerCore->addProductCustomizationData()
#1 /home/www/domain.cz/www/domain.cz/modules/ps_facebook/classes/Provider/EventDataProvider.php(151): ProductControllerCore->getTemplateVarProduct()
#2 /home/www/domain.cz/www/domain.cz/modules/ps_facebook/classes/Provider/EventDataProvider.php(113): PrestaShop\Module\PrestashopFacebook\Provider\EventDataProvider->getProductPageData()
#3 /home/www/domain.cz/www/domain.cz/modules/ps_facebook/classes/Dispatcher/EventDispatcher.php(90): PrestaShop\Module\PrestashopFacebook\Provider\EventDataProvider->generateEventData()
#4  in /home/www/domain.cz/www/domain.cz/controllers/front/ProductController.php on line 1297
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Undefined index: product in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 71
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Trying to get property 'value' of non-object in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 71
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Trying to access array offset on value of type null in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 71
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Trying to access array offset on value of type null in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 71
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Trying to access array offset on value of type null in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 71
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Undefined index: product in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 73
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Trying to get property 'value' of non-object in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 73
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Trying to access array offset on value of type null in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 73
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Undefined index: product in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 95
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Trying to get property 'value' of non-object in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 95
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Trying to access array offset on value of type null in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 95
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Trying to access array offset on value of type null in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 95
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Undefined index: product in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 99
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Trying to get property 'value' of non-object in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 99
[29-Jun-2023 09:44:00 Europe/Prague] PHP Notice:  Trying to access array offset on value of type null in /home/www/domain.cz/www/domain.cz/var/cache/prod/smarty/compile/classic/f5/3e/77/f53e779fd1a49c4de042aaba0367b47a3360185d_2.file.header.tpl.php on line 99`

### Expected behavior

Working without errors.

### Steps to reproduce

Activate and set module ps_facebook. You can see 1200 rows/per day  related this module in the server log.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

ps_facebook v1.27.0

**Comment by florine2623** [comment]
Hello @PeNov ,

Your issue is taken care of by the right team.
This is not a core issue, so I will close it.

Thanks!

**Comment by Quetzacoalt91** [comment]
Hi @PeNov,

Thanks for the feedback.
From my understanding, it could be related to a hook called before the code we rely on is fully initialized.

We'll try to reproduce this on our side and we'll try to move the pixel events in a hook called later in the page (i.e footer) if that's relevant.
