### ISSUE TITLE
autoupgrade - Upgrade from 1.7.8.10 to 8.1.1 is NOK

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#33446]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Upgrade from 1.7.8.10 to 8.1.1 is broken, even after multiple tries.

<img width="1272" alt="Screenshot 2023-07-27 at 11 03 10" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/f78a9086-0d59-449c-ab3e-bcfa6ca811a6">

```
[INTERNAL] /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php line 86 - Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "prestashop.adapter.news.circuit_breaker.settings" has a dependency on a non-existent service "prestashop.core.circuit_breaker.guzzle.cache_subscriber". #0 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Reference), false) #1 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false) #2 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Array, false) #3 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false) #4 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Array, false) #5 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false) #6 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Array, false) #7 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false) #8 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Array, false) #9 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false) #10 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(94): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Array) #11 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true) #12 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true) #13 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true) #14 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(47): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Array, true) #15 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(40): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #16 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(94): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #17 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(762): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #18 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(594): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #19 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer() #20 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/app/AppKernel.php(96): Symfony\Component\HttpKernel\Kernel->boot() #21 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): AppKernel->boot() #22 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(44): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #23 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(87): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->initConstants() #24 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(46): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #25 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(43): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->doUpgrade() #26 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/admin0340fmo9s/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #27 {main}
ROLLBACK
```

### Expected behavior

Upgrade should go through

### Steps to reproduce

1. Go to BO > Module > autoupgrade
2. Choose Local Archive
3. Add .zip and .xml files
4. Upgrade
5. See error

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

autoupgrade v4.16.1

**Comment by ECC64** [comment]
hello 
i have the same problem and i resolve it with PHP 7.4 and 1024 RAM

best regards
Patrick

**Comment by Hlavtox** [comment]
@florine2623 Please open `/admin/autoupgrade/tmp` and attach `log.txt` here.

**Comment by florine2623** [comment]
Hello @Hlavtox ,

Here it is : [log.txt](https://github.com/PrestaShop/PrestaShop/files/12213072/log.txt)

**Comment by Hlavtox** [comment]
Ping @PrestaShop/prestashop-core-developers This must be a cache issue there is no other explanation.

```
[2023-07-27 10:51:01] All files upgraded. Now upgrading database...
[2023-07-27 10:51:01] [SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[2023-07-27 10:51:01] [CLEANING CACHE] File prod removed
[2023-07-27 10:51:02] Migrating old setting file...
[2023-07-27 10:51:02] parameters file already exists!
[2023-07-27 10:51:02] Finished...
[2023-07-27 10:51:02] Parameters file updated
[2023-07-27 10:51:06] [INTERNAL] /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php line 86 - Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "prestashop.adapter.news.circuit_breaker.settings" has a dependency on a non-existent service "prestashop.core.circuit_breaker.guzzle.cache_subscriber".
#0 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Reference), false)
#1 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#2 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Array, false)
#3 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#4 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Array, false)
#5 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#6 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Array, false)
#7 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#8 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Array, false)
#9 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#10 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(94): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Array)
#11 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#12 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#13 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#14 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(47): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Array, true)
#15 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(40): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#16 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(94): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#17 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(762): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#18 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(594): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#19 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#20 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/app/AppKernel.php(96): Symfony\Component\HttpKernel\Kernel->boot()
#21 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): AppKernel->boot()
#22 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(44): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel()
#23 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(87): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->initConstants()
#24 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(46): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade()
#25 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(43): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->doUpgrade()
#26 /Users/fHea/Desktop/prestashop_1.7.8.10+build.1/admin0340fmo9s/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run()
#27 {main}

```

**Comment by kpodemski** [comment]
I've had this issue several times during the CLI upgrade but never during the web version update. It is because one of the files is not removed correctly during the upgrade and has a reference to non-existent service.
