### ISSUE TITLE
Error dropExistingForeignKeys method when updating doctrine schema

### ISSUE THREAD

**Issue by ideas-rc** [PrestaShop/PrestaShop#33600]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

i've a laot of error when i try to upgrade to 8.0.5 version.

me site stop working

### Expected behavior

```
[INTERNAL] /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/src/PrestaShopBundle/Command/UpdateSchemaCommand.php line 141 - TypeError: Unsupported operand types: int + Doctrine\DBAL\ForwardCompatibility\Result 
#0 /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/src/PrestaShopBundle/Command/UpdateSchemaCommand.php(76): PrestaShopBundle\Command\UpdateSchemaCommand->dropExistingForeignKeys() 
#1 /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): PrestaShopBundle\Command\UpdateSchemaCommand->execute() 
#2 /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1039): Symfony\Component\Console\Command\Command->run() 
#3 /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand() 
#4 /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(275): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() 
#5 /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun() 
#6 /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun() 
#7 /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/src/PrestaShopBundle/Service/Command/AbstractCommand.php(81): Symfony\Component\Console\Application->run() 
#8 /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(56): PrestaShopBundle\Service\Command\AbstractCommand->execute() 
#9 /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(68): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->runSchemaUpgradeCommand() 
#10 /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(110): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->upgradeDb() 
#11 /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(43): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() 
#12 /homepages/42/d961957784/htdocs/clickandbuilds/PrestaShop/Ideas_eShop/h0dlrwemkpfv5b9b/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() 
#13 {main}

```
### Steps to reproduce

1- click to upgrade

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

: 8.1.22

### If your bug is related to a module, specify its name and its version

1-Click Upgrade

### Your company or customer's name goes here (if applicable).

ideas

**Comment by matks** [comment]
Hello this error seems the same as https://github.com/PrestaShop/PrestaShop/issues/33564

A fix has been submitted https://github.com/PrestaShop/PrestaShop/pull/33573

**Comment by sallemiines** [comment]
Hello @ideas-rc 

Coulkd you please provide us you actual PS version ? and coulld you please check the [PHP compatibility chart ](https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/#php-requirements)


Waiting for your feedback ! 
Thank you

**Comment by ideas-rc** [comment]
Dear, my current version :
Your current PrestaShop version: 8.0.4
Your current PHP version: 8.1.22

**Comment by sallemiines** [comment]
@ideas-rc can you check the fix montionned by @matks above 

https://github.com/PrestaShop/PrestaShop/issues/33600#issuecomment-1674613660

Please Check and feedback ! 
Thank you

**Comment by ideas-rc** [comment]
Ines,

Sorry i do’nt understand what is the solve solution because i can only used the auto ugrade.

Regards 
Sébastien

**Comment by Hlavtox** [comment]
@sallemiines Fixed by https://github.com/PrestaShop/PrestaShop/pull/33573
