### ISSUE TITLE
Unable to install/upgrade to PS 8.1.1 under Windows

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#33615]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When upgrading from PS 8.1 to PS 8.1.1 under Windows I got the following error: _Unable to generate private keys using openssl_pkey_new. Check your OpenSSL configuration, especially the path to openssl.cafile._

PHP's Openssl module is installed and previous Prestashops versions didn't give this problem. 

See also this error on the forum about a failed installation: https://www.prestashop.com/forums/topic/1079137-unable-to-generate-private-keys-using-openssl_pkey_new/
The file paths in this report suggest it is WIndows too.

### Expected behavior

flawless installation

### Steps to reproduce

Install PS 8.1.
Upgrade to PS 8.1.1

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
This is why we implemented this check, if it wasn't there, the installation would crash. You need to fix your PHP configuration. You would have problems with other things even in older versions, for example - you may not be able to download a language pack etc.

**Comment by musicpanda** [comment]
> This is why we implemented this check, if it wasn't there, the installation would crash. You need to fix your PHP configuration. You would have problems with other things even in older versions, for example - you may not be able to download a language pack etc.

Didn't you read my submission? I explicitly mentioned that OpenSSL is installed. 

It looks like some obstructionists at Prestashop have tried to "solve" the `'api_public_key' problem` (see https://github.com/PrestaShop/PrestaShop/discussions/33351).

They have added a check to D/modules/autoupgrade/classes/UpgradeSelfCheck.php that looks like
`        $privateKey = openssl_pkey_new([
            'private_key_bits' => 2048,
            'private_key_type' => OPENSSL_KEYTYPE_RSA,
        ]);

        if ($privateKey === false) {
            return false;
        }

        return true;`

The function openssl_pkey_new() needs a path to openssl.cnf and it looks my Xampp installation doesn't provide that by default.

Never mind that the great majority of Prestashops doesn't have any need for public and private keys.

**Comment by Hlavtox** [comment]
@musicpanda 

> Didn't you read my submission? I explicitly mentioned that OpenSSL is installed.

I can read just fine, but openssl installed and enabled is not enough. You must check the paths to the certificates in php.ini, in XAMPP it's not configured correctly sometimes.

> It looks like some obstructionists at Prestashop have tried to "solve" the 'api_public_key' problem

Yeah that was me, because it's better to notify the user before installing, then throwing a fatal error during the install.

Open `C:\xampp\php\php.ini` and check that these two values are correct:
`curl.cainfo = "\xampp\apache\bin\curl-ca-bundle.crt"`
`openssl.cafile = "\xampp\apache\bin\curl-ca-bundle.crt"`

**Comment by musicpanda** [comment]
> Open C:\xampp\php\php.ini and check that these two values are correct:
> curl.cainfo = "\xampp\apache\bin\curl-ca-bundle.crt"
> openssl.cafile = "\xampp\apache\bin\curl-ca-bundle.crt"

Yes, those values are correct in my php.ini.

I did some experiment and saw that when I add a "config" setting to the Prestashop code it will work:
`        $privateKey = openssl_pkey_new([
	    'config' => 'C:/xampp/apache/conf/openssl.cnf',
            'private_key_bits' => 2048,
            'private_key_type' => OPENSSL_KEYTYPE_RSA,
        ]);`

However, I don't know how to add that to php.ini.

**Comment by Hlavtox** [comment]
@musicpanda This is my local PHP configuration, check everything that contains "openssl" and try to find what you have different. It will work fine without code modification. We can then put it into https://devdocs.prestashop-project.org/. ;-)

[phpinfo.zip](https://github.com/PrestaShop/PrestaShop/files/12342429/phpinfo.zip)

**Comment by musicpanda** [comment]
I ran "php -i" and I saw the following setting:

> OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.1.1s  1 Nov 2022
OpenSSL Header Version => OpenSSL 1.1.1s  1 Nov 2022
Openssl default config => C:\Program Files\Common Files\SSL/openssl.cnf

Obviously Xampp didn't put its files there and in fact the directory "C:\Program Files\Common Files\SSL" doesn't even exist on my computer.

What I understand is that OpenSSL takes its default directory from the time when it was compiled and the only way around that is setting a Windows environment variable (as you did with OPENSSL_CONF). Making a setting in php.ini seems impossible.

So the only viable way I see for Prestashop to get this working for Windows is to get the php.ini setting for openssl.cafile. That will give you the Apache directory and from there you can make a guess where the openssl.cfg file is located. You can check whether the file exists and then make a call setting the OPENSSL_CONF  environment variable. As some people have more than one Xampp installation on their computer this should be done before each call that uses this setting.

I am not sure whether that will work for WAMP and Laragon.

**Comment by musicpanda** [comment]
An alternative might be that Prestashop owns its own openssl.cnf. When I searched for openssl.cnf I notice that quite a few modules have their own version. I saw it for ps_accounts, ps_metrics, ps_eventbus and ps_checkout, although not for all versions.

**Comment by Hlavtox** [comment]
@musicpanda The environment variable is set by XAMPP. Can you check? Open httpd-xampp.conf and check that you have the OPENSSL_CONF specified.

```
#
# XAMPP settings
#

<IfModule env_module>
    SetEnv MIBDIRS "/xampp/php/extras/mibs"
    SetEnv MYSQL_HOME "\\xampp\\mysql\\bin"
    SetEnv OPENSSL_CONF "/xampp/apache/bin/openssl.cnf" <<< THIS
...
```

Update, I also have it as windows environment variable.

![Snímek obrazovky 2023-08-15 222540](https://github.com/PrestaShop/PrestaShop/assets/6097524/7a59ba5f-13cf-4a27-9fdd-361a176514a5)

Please try it and tell me if it fixes the issue. ;-)

**Comment by musicpanda** [comment]
No, none of these variables is set in my Windows environment.

It makes me wonder what this "IfModule env_module" checks for.

**Comment by Hlavtox** [comment]
OK, so try to set OPENSSL_CONF like I have.

**Comment by musicpanda** [comment]
I tried quite a few variations. But none had the effect that the PS upgrade passed the test.

**Comment by musicpanda** [comment]
When I checked on Stackoverflow I noticed that more people complain that it doesn't work for them. I get the impression that it worked in the past but no longer.

**Comment by ComonSoft** [comment]
Same issue under Wamp, This is clearly an issue beacause it worked in previous versions. It happens also if you configure PS in http mode (should not)!
After several researchs, seems to be a WAMP or XAMP issue. We found a workround check with phpinfo() where is located the "Openssl default config" in our case C:\Apache24\conf/openssl.cnf. If you don't know how to change this configuration just create folders path and copy openssl.cnf into.

**Comment by Hlavtox** [comment]
@ComonSoft You need to properly configure your environment, I suggest getting help of a skilled Windows admin or googling. :-)

**Comment by musicpanda** [comment]
> @ComonSoft You need to properly configure your environment, I suggest getting help of a skilled Windows admin or googling. :-)

This reaction doesn't make sense. If you want to claim that people don't have their Windows properly configured you should specify where. Windows is not Linux: its users don't extensively configure it. Most installations look exactly the same.

**Comment by kpodemski** [comment]
@musicpanda 

We might add documentation about it, but configuration differs whether you use WAMPP, XAMPP, Laragon, or whatever other app there is on Windows.

**Comment by Hlavtox** [comment]
@musicpanda The stack people are using is not correctly configured, I am sure that if you googled and we compared our configurations, it will work properly.

> Windows is not Linux: its users don't extensively configure it. Most installations look exactly the same.

Yep, for normal use, but if you want to run a webserver on it, it needs some configuration. And XAMPP is not configured well for it by default. 

Didn't you have to properly enable all extensions, setup opcache, memory limits etc. when you installed XAMPP? ;-)

--------------------

I will try it on a clean windows PC and update the docs for steps. ;-)

**Comment by musicpanda** [comment]
Initially setting OPENSSL_CONF didn't work. But when I came back a few days later and also changed the php directory in PATH it suddenly worked. But it annoys me that all this humbug is necessary on a Windows installation that usually is meant as the experimentation copy of a life shop. It is also annoying as I have several Xampp installations for different PHP versions.

Unfortunately there are yet more serious problems. PS 8.x has serious cache problems under Windows - probably due to Symfony malfunctioning. This goes to such an extent that I am puzzled how Prestashop could adopt this. When you can't get the most basic things right under Windows I don't trust you to get anything else right. I see the below type of errors daily. Refreshing the page usually helps. But the wondering how this could happen remains:
![rename](https://github.com/PrestaShop/PrestaShop/assets/13930107/5d85eead-a796-4120-816f-d9c32c6920c8)

I tried PS 8.1 both as an update and a fresh installation. The update (from 8.1.0) succeeded now at once. The installation has failed four times now and the end is not in sight. And every time the error is different. 

The first time the installation stopped at 67% and I got the message that the ps_edition_basic module could not be installed. Interestingly the errorlog contained a hundred messages, most about undefined constants. Amazing that it still reached 67%.

> [Tue Sep 19 23:01:42.744927 2023] [php7:notice] [pid 9620:tid 1980] [client ::1:62913] PHP Notice:  Constant _PS_DO_NOT_LOAD_CONFIGURATION_ already defined in D:\\xampp74g\\htdocs\\_ps811\\install\\controllers\\http\\smarty_compile.php on line 26, referer: http://localhost/_ps811/install/
[Tue Sep 19 23:01:42.748923 2023] [php7:warn] [pid 9620:tid 1980] [client ::1:62913] PHP Warning:  Use of undefined constant _DB_PREFIX_ - assumed '_DB_PREFIX_' (this will throw an Error in a future version of PHP) in D:\\xampp74g\\htdocs\\_ps811\\classes\\Configuration.php on line 175, referer: http://localhost/_ps811/install/
[Tue Sep 19 23:01:42.749923 2023] [php7:warn] [pid 9620:tid 1980] [client ::1:62913] PHP Warning:  Use of undefined constant _DB_SERVER_ - assumed '_DB_SERVER_' (this will throw an Error in a future version of PHP) in D:\\xampp74g\\htdocs\\_ps811\\classes\\db\\Db.php on line 219, referer: http://localhost/_ps811/install/
[Tue Sep 19 23:01:42.749923 2023] [php7:warn] [pid 9620:tid 1980] [client ::1:62913] PHP Warning:  Use of undefined constant _DB_USER_ - assumed '_DB_USER_' (this will throw an Error in a future version of PHP) in D:\\xampp74g\\htdocs\\_ps811\\classes\\db\\Db.php on line 219, referer: http://localhost/_ps811/install/
[Tue Sep 19 23:01:42.749923 2023] [php7:warn] [pid 9620:tid 1980] [client ::1:62913] PHP Warning:  Use of undefined constant _DB_PASSWD_ - assumed '_DB_PASSWD_' (this will throw an Error in a future version of PHP) in D:\\xampp74g\\htdocs\\_ps811\\classes\\db\\Db.php on line 219, referer: http://localhost/_ps811/install/
[Tue Sep 19 23:01:42.749923 2023] [php7:warn] [pid 9620:tid 1980] [client ::1:62913] PHP Warning:  Use of undefined constant _DB_NAME_ - assumed '_DB_NAME_' (this will throw an Error in a future version of PHP) in D:\\xampp74g\\htdocs\\_ps811\\classes\\db\\Db.php on line 219, referer: http://localhost/_ps811/install/
[Tue Sep 19 23:01:45.449408 2023] [php7:error] [pid 9620:tid 1980] [client ::1:62913] PHP Fatal error:  Uncaught PrestaShopException: Link to database cannot be established: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Host is onbekend.  in D:\\xampp74g\\htdocs\\_ps811\\classes\\db\\DbPDO.php:119\nStack trace:\n#0 D:\\xampp74g\\htdocs\\_ps811\\classes\\db\\Db.php(331): DbPDOCore->connect()\n#1 D:\\xampp74g\\htdocs\\_ps811\\classes\\db\\Db.php(241): DbCore->__construct('_DB_SERVER_', '_DB_USER_', '_DB_PASSWD_', '_DB_NAME_')\n#2 D:\\xampp74g\\htdocs\\_ps811\\config\\alias.php(47): DbCore::getInstance()\n#3 D:\\xampp74g\\htdocs\\_ps811\\config\\alias.php(52): pSQL('configuration')\n#4 D:\\xampp74g\\htdocs\\_ps811\\classes\\Configuration.php(175): bqSQL('configuration')\n#5 D:\\xampp74g\\htdocs\\_ps811\\classes\\Configuration.php(229): ConfigurationCore::loadConfiguration()\n#6 D:\\xampp74g\\htdocs\\_ps811\\config\\smarty.config.inc.php(28): ConfigurationCore::get('PS_SMARTY_LOCAL')\n#7 D:\\xampp74g\\htdocs\\_ps811\\install\\controllers\\http\\smarty_compile.php(37): require_once('D:\\\\xampp74g\\\\htd...')\n#8 D:\\xampp74g\\htdocs\\_ps811\\install\\classes\\c in D:\\xampp74g\\htdocs\\_ps811\\classes\\db\\DbPDO.php on line 119, referer: http://localhost/_ps811/install/


![basemodule](https://github.com/PrestaShop/PrestaShop/assets/13930107/6df49d92-46a0-49ea-86b6-54bf35303109)

The following times there were hardly any error messages. The second time a.o. some translation messages:

> [Wed Sep 20 15:38:04.637171 2023] [php7:notice] [pid 9620:tid 1960] [client ::1:49374] PHP Notice:  Trying to get property 'theme_name' of non-object in D:\\xampp\htdocs\\var\\cache\\prod\\ContainerR8edCdg\\appAppKernelProdContainer.php on line 2906, referer: http://localhost/install/index.php
[Wed Sep 20 15:40:50.932188 2023] [php7:warn] [pid 9620:tid 1948] [client ::1:49391] PHP Warning:  require(D:\\xampp\htdocs\\var\\cache\\prod\\ContainerR8edCdg\\getPrestashop_Translation_TranslatorLanguageLoaderService.php): failed to open stream: No such file or directory in D:\\xampp\htdocs\\var\\cache\\prod\\ContainerR8edCdg\\appAppKernelProdContainer.php on line 2254, referer: http://localhost/install/index.php
[Wed Sep 20 15:40:50.932188 2023] [php7:error] [pid 9620:tid 1948] [client ::1:49391] PHP Fatal error:  require(): Failed opening required 'D:\\xampp\htdocs\\var\\cache\\prod\\ContainerR8edCdg\\getPrestashop_Translation_TranslatorLanguageLoaderService.php' (include_path='D:\\xampp\htdocs\\vendor/pear/pear_exception;D:\\xampp\htdocs\\vendor/pear/console_getopt;D:\\xampp\htdocs\\vendor/pear/pear-core-minimal/src;D:\\xampp\htdocs\\vendor/pear/archive_tar;D:\\xampp74g\\php\\PEAR') in D:\\xampp\htdocs\\var\\cache\\prod\\ContainerR8edCdg\\appAppKernelProdContainer.php on line 2254, referer: http://localhost/install/index.php
[Wed Sep 20 15:40:51.364266 2023] [php7:warn] [pid 9620:tid 1956] [client ::1:49390] PHP Warning:  require(D:\\xampp\htdocs\\var\\cache\\prod\\ContainerR8edCdg\\getPrestashop_Translation_TranslatorLanguageLoaderService.php): failed to open stream: No such file or directory in D:\\xampp\htdocs\\var\\cache\\prod\\ContainerR8edCdg\\appAppKernelProdContainer.php on line 2254, referer: http://localhost/install/index.php
[Wed Sep 20 15:40:51.364266 2023] [php7:error] [pid 9620:tid 1956] [client ::1:49390] PHP Fatal error:  require(): Failed opening required 'D:\\xampp\htdocs\\var\\cache\\prod\\ContainerR8edCdg\\getPrestashop_Translation_TranslatorLanguageLoaderService.php' (include_path='D:\\xampp\htdocs\\vendor/pear/pear_exception;D:\\xampp\htdocs\\vendor/pear/console_getopt;D:\\xampp\htdocs\\vendor/pear/pear-core-minimal/src;D:\\xampp\htdocs\\vendor/pear/archive_tar;D:\\xampp74g\\php\\PEAR') in D:\\xampp\htdocs\\var\\cache\\prod\\ContainerR8edCdg\\appAppKernelProdContainer.php on line 2254, referer: http://localhost/install/index.php
[Wed Sep 20 15:42:28.966427 2023] [php7:notice] [pid 9620:tid 1960] [client ::1:49374] PHP Notice:  Trying to get property 'theme_name' of non-object in D:\\xampp\htdocs\\var\\cache\\prod\\ContainerNx53ry0\\appAppKernelProdContainer.php on line 3435, referer: http://localhost/install/index.php

The message was:
![link_block](https://github.com/PrestaShop/PrestaShop/assets/13930107/4f59a057-8a7e-495e-af14-23b987bbd41d)

The third time produced just like the first time a message that a module could not be installed. Only this time it concerned two modules:
![install3](https://github.com/PrestaShop/PrestaShop/assets/13930107/acf774c3-498f-47f2-a42c-dbcaa0c5e4be)

The fourth time I had enabled debug mode. This time I got a message that I should use at least PHP 8.1 (I use 7.4).
![composer](https://github.com/PrestaShop/PrestaShop/assets/13930107/29a47285-a157-4221-b5a6-b1f67bf2fd4a)

**Comment by musicpanda** [comment]
Here another victim: https://www.prestashop.com/forums/topic/1080264-turnkey-lamp-cant-install-ps8/

**Comment by Hlavtox** [comment]
@musicpanda Firstly, glad to hear that your issue has been fixed, but we are starting to mix pears and apples. :-)

> Initially setting OPENSSL_CONF didn't work. But when I came back a few days later and also changed the php directory in PATH it suddenly worked. But it annoys me that all this humbug is necessary on a Windows installation that usually is meant as the experimentation copy of a life shop.

Setting up PHP on Windows requires some configuration, you see that it was matter of one minute to set it up. It's mentioned here in the official PHP documentation. https://www.php.net/manual/en/openssl.installation.php

Prestashop has nothing to do with this.

> It is also annoying as I have several Xampp installations for different PHP versions.

You can setup multiple PHP instances on xampp, then setup which folder should use which PHP version. Or there are alternatives like MAMP PRO, where you can switch versions.

> Unfortunately there are yet more serious problems. PS 8.x has serious cache problems under Windows - probably due to Symfony malfunctioning. This goes to such an extent that I am puzzled how Prestashop could adopt this. When you can't get the most basic things right under Windows I don't trust you to get anything else right. I see the below type of errors daily. Refreshing the page usually helps. But the wondering how this could happen remains:

It sucks, I know, it happens to me also from time to time, but it does so only locally, so I can live with it. I never experienced it on Linux webservers. It would be cool if you could get it fixed and submit a PR for it.

Regarding the errors you sent and the link to forums, all these errors are coming from Prestashop company edition of the sofware, which we unfortunately can't control. :(

Please use the clean edition to install it - https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.1, it doesn't contain any tracking, buggy modules.

**Comment by BenoitAdam** [comment]
It's still a thing

> This is why we implemented this check, if it wasn't there, the installation would crash. 

Implementing a check is a good thing. But you must also implement a clear and simple solution to it..


I've been using Prestashop from time to times (I mainly use Wordpress & Drupal, and I often teach PHP/SQL/CMS to students), and EVERYTIME Prestashop is the CMS giving me the hard time on local installation !!!!


I use Wamp 3.3.0 (PHP 8.1) on Windows 10


Prestashop, plz fix.

**Comment by Hlavtox** [comment]
@BenoitAdam94 We can't implement tutorials to properly configure your web server environment, sorry.

**Comment by BenoitAdam** [comment]
> @BenoitAdam94 We can't implement tutorials to properly configure your web server environment, sorry.

I can't recommend my students and my clients to use Prestashop then.


We talk about basic local windows environment here, not a random linux VPS.

**Comment by Hyblaweb** [comment]
You simply need to install OpenSSL from Shining Light Productions (slproweb.com).
You won't need to add anything on xampp or wamp.

**Comment by TeddyBear06** [comment]
Hi there,

@BenoitAdam94 @musicpanda 

I faced the same "issue" under `Windows 11` using `Wamp 3.3.7 64bits` and `Prestashop 8.2.0`.

![Image](https://github.com/user-attachments/assets/4090dc73-976e-4171-9c2e-36f5cfe03bde)

Having a look at [phpinfo()](http://localhost/?phpinfo=-1) indicates us that the default OpenSSL configuration is searching "_Openssl default config_" file under : `c:\Program Files\Common Files\SSL/openssl.cnf` (x64, otherwise C:\Program Files (x86)\Common Files\SSL\openssl.cnf x86 or, prior to PHP 7.4.0, C:\usr\local\ssl\openssl.cnf), as pointed by @Hlavtox more informations available here [OpenSSL installation](https://www.php.net/manual/en/openssl.installation.php))

![Image](https://github.com/user-attachments/assets/f296c492-c5a8-47ef-95b0-245579bead9a)

Both the directory and the file were not present by default on my computer.

Follow thoose simple steps to make it work properly:

1. Copy the `openssl.cnf` file from `C:\wamp64\bin\apache\apache2.4.62.1\conf\openssl.cnf` (or wherever you've configured the installation folder of Wamp, I used the default one for simplicity)
2. Create the `C:\Program Files\Common Files\SSL` folder (if not created yet, requires administrator privileges)
3. Paste the `openssl.cnf` file there (requires administrator privileges)
4. Restart Wamp services

You're done ;-)

![Image](https://github.com/user-attachments/assets/f000c254-b25f-465b-b41f-64f4b88c0b83)

P.S : I choosed to copy/paste the `openssl.cnf` file rather than modifying php.ini for simplicity and reproductability of thoose steps.

Thanks @ComonSoft for pointing out that `openssl.cnf` file already exists :-)

**Comment by Quetzacoalt91** [comment]
By following the documentation of PHP about OpenSSL and my `phpinfo()`, I've ended on the same solution: Make the openssl.cnf visible in the `C:\Program Files\Common Files\SSL` directory.

If this helps to avoid duplicating files all over your filesystem, note symbolic links will work as well. 

![Image](https://github.com/user-attachments/assets/f7934624-9f60-4a9d-a6e2-d61ec634d20e)
(Sorry for the screenshot contents written in 🥖)

Globally, I would say this issue is not related to PrestaShop itself but how your PHP environment is configured. The check displayed in the PrestaShop installer (and Update Assistant) covers you from other errors in the future, and should be taken in account.

There is one thing that is worth a change. In the error message, what is this file `openssl.cafile`? I wonder if there is a typo that prevents people to know where to look exactly. @Hlavtox what do you think?

**EDIT:** I got my answer with https://github.com/PrestaShop/PrestaShop/issues/33286#issuecomment-1640196037. Maybe rephrasing with "Failed to generate private keys using openssl_pkey_new(). Please check your PHP configuration, especially the openssl.cafile setting, and ensure that the specified file exists and is accessible."
