### ISSUE TITLE
Fatal error:  Uncaught Error: Undefined constant "_DB_PREFIX_" in Configuration.php:175

### ISSUE THREAD

**Issue by aymeric75** [PrestaShop/PrestaShop#33717]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

During my prestashop 8.1 installation on Windows 10 with Wamp server, everything works until the shop installation where I get a HTTP 500 - error -

So I went to check in **wamp64/logs/php_error**

And I see
```

[24-Aug-2023 11:19:00 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "_DB_PREFIX_" in C:\wamp64\www\prestashop\classes\Configuration.php:175
Stack trace:
```

I did not find any solution for this.

Thanks

### Steps to reproduce

Install Prestashop 8.1 on Windows 10 with wamp

### PrestaShop version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment]
Hello @aymeric75 

Could you please provide more details and a screen record or some screenshots 🙏 
Waiting for your feedback.

Thanks!

**Comment by aymeric75** [comment]
Hi, thanks for your help

Environment:
```
Windows 10
Wampserver 3.3.0
Php 8.0.26
Apache 2.4.54.2
MySQL 8.0.31
```

Screenshot:

![Sans titre](https://github.com/PrestaShop/PrestaShop/assets/12927600/8927e79d-3f4a-4bd5-9117-50ebd2301b78)


Full error log (from _C:/wamp64/logs/php_error_)
```
[24-Aug-2023 18:23:14 UTC] PHP Warning:  Constant _PS_DO_NOT_LOAD_CONFIGURATION_ already defined in C:\wamp64\www\prestashop\install\controllers\http\smarty_compile.php on line 26
[24-Aug-2023 18:23:14 UTC] PHP Stack trace:
[24-Aug-2023 18:23:14 UTC] PHP   1. {main}() C:\wamp64\www\prestashop\install\index.php:0
[24-Aug-2023 18:23:14 UTC] PHP   2. InstallControllerHttp::execute() C:\wamp64\www\prestashop\install\index.php:53
[24-Aug-2023 18:23:14 UTC] PHP   3. require_once() C:\wamp64\www\prestashop\install\classes\controllerHttp.php:190
[24-Aug-2023 18:23:14 UTC] PHP   4. define($constant_name = '_PS_DO_NOT_LOAD_CONFIGURATION_', $value = TRUE) C:\wamp64\www\prestashop\install\controllers\http\smarty_compile.php:26
[24-Aug-2023 18:23:14 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "_DB_PREFIX_" in C:\wamp64\www\prestashop\classes\Configuration.php:175
Stack trace:
#0 C:\wamp64\www\prestashop\classes\Configuration.php(229): ConfigurationCore::loadConfiguration()
#1 C:\wamp64\www\prestashop\config\smarty.config.inc.php(28): ConfigurationCore::get('PS_SMARTY_LOCAL')
#2 C:\wamp64\www\prestashop\install\controllers\http\smarty_compile.php(37): require_once('C:\\wamp64\\www\\p...')
#3 C:\wamp64\www\prestashop\install\classes\controllerHttp.php(190): require_once('C:\\wamp64\\www\\p...')
#4 C:\wamp64\www\prestashop\install\index.php(53): InstallControllerHttp::execute()
#5 {main}
  thrown in C:\wamp64\www\prestashop\classes\Configuration.php on line 175
[24-Aug-2023 18:23:15 UTC] PHP Warning:  Constant _PS_DO_NOT_LOAD_CONFIGURATION_ already defined in C:\wamp64\www\prestashop\install\controllers\http\smarty_compile.php on line 26
[24-Aug-2023 18:23:15 UTC] PHP Stack trace:
[24-Aug-2023 18:23:15 UTC] PHP   1. {main}() C:\wamp64\www\prestashop\install\index.php:0
[24-Aug-2023 18:23:15 UTC] PHP   2. InstallControllerHttp::execute() C:\wamp64\www\prestashop\install\index.php:53
[24-Aug-2023 18:23:15 UTC] PHP   3. require_once() C:\wamp64\www\prestashop\install\classes\controllerHttp.php:190
[24-Aug-2023 18:23:15 UTC] PHP   4. define($constant_name = '_PS_DO_NOT_LOAD_CONFIGURATION_', $value = TRUE) C:\wamp64\www\prestashop\install\controllers\http\smarty_compile.php:26
[24-Aug-2023 18:23:15 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "_DB_PREFIX_" in C:\wamp64\www\prestashop\classes\Configuration.php:175
Stack trace:
#0 C:\wamp64\www\prestashop\classes\Configuration.php(229): ConfigurationCore::loadConfiguration()
#1 C:\wamp64\www\prestashop\config\smarty.config.inc.php(28): ConfigurationCore::get('PS_SMARTY_LOCAL')
#2 C:\wamp64\www\prestashop\install\controllers\http\smarty_compile.php(37): require_once('C:\\wamp64\\www\\p...')
#3 C:\wamp64\www\prestashop\install\classes\controllerHttp.php(190): require_once('C:\\wamp64\\www\\p...')
#4 C:\wamp64\www\prestashop\install\index.php(53): InstallControllerHttp::execute()
#5 {main}
  thrown in C:\wamp64\www\prestashop\classes\Configuration.php on line 175
[24-Aug-2023 20:23:15 Europe/Paris] PHP Warning:  openssl_pkey_export(): Cannot get key from parameter 1 in C:\wamp64\www\prestashop\src\PrestaShopBundle\Install\Install.php on line 197
[24-Aug-2023 20:23:15 Europe/Paris] PHP Stack trace:
[24-Aug-2023 20:23:15 Europe/Paris] PHP   1. {main}() C:\wamp64\www\prestashop\install\index.php:0
[24-Aug-2023 20:23:15 Europe/Paris] PHP   2. InstallControllerHttp::execute() C:\wamp64\www\prestashop\install\index.php:53
[24-Aug-2023 20:23:15 Europe/Paris] PHP   3. InstallControllerHttpProcess->process() C:\wamp64\www\prestashop\install\classes\controllerHttp.php:277
[24-Aug-2023 20:23:15 Europe/Paris] PHP   4. InstallControllerHttpProcess->processGenerateSettingsFile() C:\wamp64\www\prestashop\install\controllers\http\process.php:90
[24-Aug-2023 20:23:15 Europe/Paris] PHP   5. PrestaShopBundle\Install\Install->generateSettingsFile($database_host = '127.0.0.1', $database_user = 'root', $database_password = '', $database_name = 'presta8', $database_prefix = 'ps_', $database_engine = 'InnoDB') C:\wamp64\www\prestashop\install\controllers\http\process.php:150
[24-Aug-2023 20:23:15 Europe/Paris] PHP   6. openssl_pkey_export($key = FALSE, $output = NULL) C:\wamp64\www\prestashop\src\PrestaShopBundle\Install\Install.php:197
[24-Aug-2023 20:23:15 Europe/Paris] PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in C:\wamp64\www\prestashop\src\PrestaShopBundle\Install\Install.php:198
Stack trace:
#0 C:\wamp64\www\prestashop\src\PrestaShopBundle\Install\Install.php(198): openssl_pkey_get_details(false)
#1 C:\wamp64\www\prestashop\install\controllers\http\process.php(150): PrestaShopBundle\Install\Install->generateSettingsFile('127.0.0.1', 'root', '', 'presta8', 'ps_', 'InnoDB')
#2 C:\wamp64\www\prestashop\install\controllers\http\process.php(90): InstallControllerHttpProcess->processGenerateSettingsFile()
#3 C:\wamp64\www\prestashop\install\classes\controllerHttp.php(277): InstallControllerHttpProcess->process()
#4 C:\wamp64\www\prestashop\install\index.php(53): InstallControllerHttp::execute()
#5 {main}
  thrown in C:\wamp64\www\prestashop\src\PrestaShopBundle\Install\Install.php on line 198

```

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers can someone please help 🙏

**Comment by aymeric75** [comment]
?

**Comment by kpodemski** [comment]
It may be related to OpenSSL configuration in your system. Please follow this guide:
https://build.prestashop-project.org/news/2023/core-monthly-2023-07-01-2023-07-31/#prestashop-811-the-first-patch-version-and-upgrade-issues

If you have more questions, please open [a new discussion inside the Q&A section](https://github.com/PrestaShop/PrestaShop/discussions/categories/q-a). It's not a problem with the software but your environment.

**Comment by aymeric75** [comment]
Hello, I just followed your instructions (also for generating the cert I had to follow this tuto [https://www.blog.florian-bogey.fr/installer-un-certificat-ssl-sous-wamp.html](https://www.blog.florian-bogey.fr/installer-un-certificat-ssl-sous-wamp.html) )

and I still get this error:
```

#5 {main}
  thrown in C:\wamp64\www\prestashop\classes\Configuration.php on line 175
[31-Aug-2023 07:31:24 UTC] PHP Warning:  Constant _PS_DO_NOT_LOAD_CONFIGURATION_ already defined in C:\wamp64\www\prestashop\install\controllers\http\smarty_compile.php on line 26
[31-Aug-2023 07:31:24 UTC] PHP Stack trace:
[31-Aug-2023 07:31:24 UTC] PHP   1. {main}() C:\wamp64\www\prestashop\install\index.php:0
[31-Aug-2023 07:31:24 UTC] PHP   2. InstallControllerHttp::execute() C:\wamp64\www\prestashop\install\index.php:53
[31-Aug-2023 07:31:24 UTC] PHP   3. require_once() C:\wamp64\www\prestashop\install\classes\controllerHttp.php:190
[31-Aug-2023 07:31:24 UTC] PHP   4. define($constant_name = '_PS_DO_NOT_LOAD_CONFIGURATION_', $value = TRUE) C:\wamp64\www\prestashop\install\controllers\http\smarty_compile.php:26
[31-Aug-2023 07:31:24 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "_DB_PREFIX_" in C:\wamp64\www\prestashop\classes\Configuration.php:175
Stack trace:
#0 C:\wamp64\www\prestashop\classes\Configuration.php(229): ConfigurationCore::loadConfiguration()
#1 C:\wamp64\www\prestashop\config\smarty.config.inc.php(28): ConfigurationCore::get('PS_SMARTY_LOCAL')
#2 C:\wamp64\www\prestashop\install\controllers\http\smarty_compile.php(37): require_once('C:\\wamp64\\www\\p...')
#3 C:\wamp64\www\prestashop\install\classes\controllerHttp.php(190): require_once('C:\\wamp64\\www\\p...')
#4 C:\wamp64\www\prestashop\install\index.php(53): InstallControllerHttp::execute()
#5 {main}
  thrown in C:\wamp64\www\prestashop\classes\Configuration.php on line 175
[31-Aug-2023 09:31:24 Europe/Paris] PHP Warning:  openssl_pkey_export(): Cannot get key from parameter 1 in C:\wamp64\www\prestashop\src\PrestaShopBundle\Install\Install.php on line 197
[31-Aug-2023 09:31:24 Europe/Paris] PHP Stack trace:
[31-Aug-2023 09:31:24 Europe/Paris] PHP   1. {main}() C:\wamp64\www\prestashop\install\index.php:0
[31-Aug-2023 09:31:24 Europe/Paris] PHP   2. InstallControllerHttp::execute() C:\wamp64\www\prestashop\install\index.php:53
[31-Aug-2023 09:31:24 Europe/Paris] PHP   3. InstallControllerHttpProcess->process() C:\wamp64\www\prestashop\install\classes\controllerHttp.php:277
[31-Aug-2023 09:31:24 Europe/Paris] PHP   4. InstallControllerHttpProcess->processGenerateSettingsFile() C:\wamp64\www\prestashop\install\controllers\http\process.php:90
[31-Aug-2023 09:31:24 Europe/Paris] PHP   5. PrestaShopBundle\Install\Install->generateSettingsFile($database_host = '127.0.0.1', $database_user = 'root', $database_password = '', $database_name = 'presta8', $database_prefix = 'ps_', $database_engine = 'InnoDB') C:\wamp64\www\prestashop\install\controllers\http\process.php:150
[31-Aug-2023 09:31:24 Europe/Paris] PHP   6. openssl_pkey_export($key = FALSE, $output = NULL) C:\wamp64\www\prestashop\src\PrestaShopBundle\Install\Install.php:197
[31-Aug-2023 09:31:24 Europe/Paris] PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in C:\wamp64\www\prestashop\src\PrestaShopBundle\Install\Install.php:198
Stack trace:
#0 C:\wamp64\www\prestashop\src\PrestaShopBundle\Install\Install.php(198): openssl_pkey_get_details(false)
#1 C:\wamp64\www\prestashop\install\controllers\http\process.php(150): PrestaShopBundle\Install\Install->generateSettingsFile('127.0.0.1', 'root', '', 'presta8', 'ps_', 'InnoDB')
#2 C:\wamp64\www\prestashop\install\controllers\http\process.php(90): InstallControllerHttpProcess->processGenerateSettingsFile()
#3 C:\wamp64\www\prestashop\install\classes\controllerHttp.php(277): InstallControllerHttpProcess->process()
#4 C:\wamp64\www\prestashop\install\index.php(53): InstallControllerHttp::execute()
#5 {main}
  thrown in C:\wamp64\www\prestashop\src\PrestaShopBundle\Install\Install.php on line 198
```

**Comment by kpodemski** [comment]
I still see this error:
PHP Warning:  openssl_pkey_export(): Cannot get key from parameter 1 in C:\wamp64\www\prestashop\src\PrestaShopBundle\Install\Install.php on line 197

I've never used Wamp, so I don't know what else could be the thing there. When I worked on Windows, I used Laragon, WSL or Docker.

**Comment by aymeric75** [comment]
Ok, maybe I will use docker so, thanks

**Comment by stevenbrookes** [comment]
I had the same error running on PHP8.2 had to downgrade to 8.1 and install worked fine.

**Comment by dzatoah** [comment]
I encountered this issue too.
I've tested with PHP8.2 and PHP8.1.
Debian 12.
Latest Prestashop stable release.
I even tried this windows fix: https://build.prestashop-project.org/news/2023/core-monthly-2023-07-01-2023-07-31/#prestashop-811-the-first-patch-version-and-upgrade-issues

**Comment by nsordk** [comment]
Had same issue on windows using xampp and followed this guide found on Stackoverflow:

Click on the START button
Click on CONTROL PANEL
Click on SYSTEM AND SECURITY
Click on SYSTEM
Click on ADVANCED SYSTEM SETTINGS
Click on ENVIRONMENT VARIABLES
Under "System Variables" click on "NEW"
Enter the "Variable name" OPENSSL_CONF
Enter the "Variable value".

Wamp - C:\wamp\bin\apache\Apache2.2.17\conf\openssl.cnf
Xampp - C:\xampp\apache\conf\openssl.cnf

Click "OK" and close all the windows and RESTART your computer.
The OPENSSL should be correctly working.

Restart is crucial, or it will not have any effect.

**Comment by dzatoah** [comment]
I believe my issue was fixed by upgrading Prestashop to the latest version. I can't remember if I did anything else that day.
