### ISSUE TITLE
8.1.2 found a javascript error in the new product page pushing on "add a customization field" button

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#34205]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
if you go in the details section of the new product page, I get a javascript error

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/ba8553d6-a98d-4979-9667-9b4604480d2b)
![2](https://github.com/PrestaShop/PrestaShop/assets/653230/4bdc6dc7-420c-4ef6-a5e5-ba9adc1a07c8)

bye

### Steps to reproduce

1. Active the new style for the admin product page
2. go in the details section
3. open the console
4. push on the button "add a customization field"

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @maofree ,

I have reproduced your issue in 8.1.2. I'll add this to the backlog so it can be fixed.

<img width="1428" alt="Screenshot 2023-10-09 at 11 57 21" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/fa8c5660-c389-4fd4-a3f0-88edd15fd324">

```
product_edit.bundle.js?8.1.2:1058 Uncaught TypeError: n.refreshFormInputs is not a function
    at Ey.addCustomizationField (product_edit.bundle.js?8.1.2:1058:917)
    at HTMLButtonElement.<anonymous> (product_edit.bundle.js?8.1.2:1058:501)
    at HTMLDivElement.dispatch (main.bundle.js:660:39542)
    at g.handle (main.bundle.js:660:37537)
```


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
