### ISSUE TITLE
WebServices when using JSON output format: Uncaught TypeError: array_filter(): Argument #1 ($array)

### ISSUE THREAD

**Issue by ZlatanOmerovic** [PrestaShop/PrestaShop#34794]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am receiving the following PHP error when trying to use JSON output format for Web Services, regardless if I pass the Query String or Header parameter to specify the output format.

```
[Sat Dec 09 01:37:07.914633 2023] [php:error] [pid 00000] [client 000.000.000.000:00000] PHP Fatal error:  Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, string given in /my/prestashop/classes/webservice/WebserviceOutputJSON.php:168\nStack trace:\n#0 /my/prestashop/classes/webservice/WebserviceOutputJSON.php(168): array_filter()\n#1 [internal function]: WebserviceOutputJSONCore->{closure}()\n#2 /my/prestashop/classes/webservice/WebserviceOutputJSON.php(169): array_walk()\n#3 /my/prestashop/classes/webservice/WebserviceOutputBuilder.php(350): WebserviceOutputJSONCore->overrideContent()\n#4 /my/prestashop/classes/webservice/WebserviceRequest.php(1842): WebserviceOutputBuilderCore->getResourcesList()\n#5 /my/prestashop/classes/webservice/WebserviceRequest.php(634): WebserviceRequestCore->returnOutput()\n#6 /my/prestashop/webservice/dispatcher.php(94): WebserviceRequestCore->fetch()\n#7 {main}\n  thrown in /my/prestashop/classes/webservice/WebserviceOutputJSON.php on line 168
```

When I looked into the `classes/webservice/WebserviceOutputJSON.php:168`, I noticed that `array_walk` call in that method wasn't type-checking the `$item`:

```php
array_walk($this->content, function (&$item) {
    $item = array_filter($item);
});
```

That can lead to unexpected behavior, since `array_filter` always expects an `array`.

In order to proceed using JSON output format, I've applied a small patch:

```php
array_walk($this->content, function (&$item) {
    if(is_array($item)) $item = array_filter($item);
});
```

### Expected behavior

I expected to get JSON output format, instead, I got a `500 Internal Server Error`.

For example, for the following call:

```http
GET /api HTTP/1.1
Host: my.prestashop.tld
Authorization: Basic AaBbCcDdEeFfGgHhIJKLMNOPQRSTUVWXYZ0123456789
Output-Format: JSON
Cookie: 4a3201b735f5d5238e2ec4541c5e9e2f4a3201b735f5d5238e2ec4541c5e9e2f4a3201b735f5d5238e2ec4541c5e9e2f4a3201b735f5d5238e2ec4541c5e9e2f4a3201b735f5d5238e2ec4541c5e9e2f4a3201b735f5d5238e2ec4541c5e9e2f4a3201b735f5d5238e2ec4541c5e9e2f4a3201b735f5d5238e2ec4541c5e9e2f4a3201b735f5d5238e2ec4541c5e9e2f4a3201b735f5d5238e2ec4541c5e9e2f4a3201b735f5d5238e2ec4541c5e9e2f4a3201b735f5d5238e2ec4541c5e9e2f4a3201b735f5d5238e2ec4541c5e9e2f4a3201b735f5d5238e
```

I expected to get this response:

```json
[
    "attachments",
    "categories",
    "images",
    "price_ranges",
    "product_customization_fields",
    "product_feature_values",
    "product_features",
    "product_option_values",
    "product_options",
    "product_suppliers",
    "products",
    "shop_groups",
    "shop_urls",
    "specific_price_rules",
    "specific_prices",
    "stock_availables",
    "suppliers",
    "tags",
    "tax_rules",
    "taxes",
    "warehouses"
]
```

### Steps to reproduce

1. Enable Web Services
2. Create a new key
3. Select the resource items from the list below
4. Try sending any HTTP request towards a Web Service endpoint and include JSON output format parameters

Resources I selected (all HTTP methods)

```
attachments
categories
images
price_ranges
product_customization_fields
product_feature_values
product_features
product_option_values
product_options
product_suppliers
products
shop_groups
shop_urls
specific_price_rules
specific_prices
stock_availables
suppliers
tags
tax_rules
taxes
warehouses
```

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.2

**Comment by AvivoB** [comment]
Another solution is to check whether the content is of type Array.

` public function overrideContent($content)
    {
        array_walk($this->content, function (&$item) {
            //$item = array_filter($item); //removed
	    $item = is_array($item)?array_filter($item):$item; //inserted
        });
        $content = json_encode($this->content, JSON_UNESCAPED_UNICODE);

        return (false !== $content) ? $content : '';
    }`

**Comment by AvivoB** [comment]
Another solution is to check whether the content is of type Array.
```
public function overrideContent($content)
    {
        array_walk($this->content, function (&$item) {
            //$item = array_filter($item); //removed
	    $item = is_array($item)?array_filter($item):$item; //inserted
        });
        $content = json_encode($this->content, JSON_UNESCAPED_UNICODE);

        return (false !== $content) ? $content : '';
    }

**Comment by OrionCodeDev** [comment]
> Another solution is to check whether the content is of type Array.
> 
> ```
> public function overrideContent($content)
>     {
>         array_walk($this->content, function (&$item) {
>             //$item = array_filter($item); //removed
> 	    $item = is_array($item)?array_filter($item):$item; //inserted
>         });
>         $content = json_encode($this->content, JSON_UNESCAPED_UNICODE);
> 
>         return (false !== $content) ? $content : '';
>     }
> ```

working fine for me. Also i can confirm this error PS 8.1.3

**Comment by mplattu** [comment]
This appears still to be outstanding in development branch and therefore in the current 8.1.7, too.

This is probably caused by a empty datasets where the aforementioned function is called with type `string` parameter instead of `array`. In my case I had just created a new PrestaShop with no data. When the web service of my fulfillment service tried to reach my PrestaShop via the API the server gave http error 500.

The XML call works flawlessly.

:100: to @ZlatanOmerovic for his excellent bug report!

**Comment by boo-code** [comment]
Still fatal on `9.2.x`, two years on, and the diagnosis in the report is exactly right.

```php
$renderer = new WebserviceOutputJSON();
$renderer->renderNodeHeader('api', []);
$renderer->renderNodeHeader('customers', []);
$renderer->overrideContent('');
// TypeError: array_filter(): Argument #1 ($array) must be of type array, string given
```

The reason the entries are not all arrays is `renderNodeHeader()`:

```php
if ($isAPICall && !in_array($node_name, ['description', 'schema', 'api'])) {
    $this->content[] = $node_name;   // a string
}
```

so listing the API root mixes resource names as strings with entities as arrays, and `overrideContent()` filters every entry unconditionally.

PR #42304 applies the guard you proposed, with a unit test that raises the same TypeError without it. @AvivoB's alternative of checking the content type would work too; filtering per entry keeps the empty-value filtering that entities rely on, which is why I kept it at that level.
