### ISSUE TITLE
PHP Fatal Error SortOrder

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#34819]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I receive on error_log_php many times the same error

```
[12-Dec-2023 16:39:08 Europe/Rome] PHP Fatal error:  Uncaught PrestaShop\PrestaShop\Core\Product\Search\Exception\InvalidSortOrderDirectionException: Invalid SortOrder direction `desc?order=product`. Expecting one of: `ASC`, `DESC`, or `RANDOM`. in /home/jvillagc/public_html/shop/src/Core/Product/Search/SortOrder.php:199
Stack trace:
#0 /home/jvillagc/public_html/shop/src/Core/Product/Search/SortOrder.php(67): PrestaShop\PrestaShop\Core\Product\Search\SortOrder->setDirection('desc?order=prod...')
#1 /home/jvillagc/public_html/shop/src/Core/Product/Search/SortOrder.php(125): PrestaShop\PrestaShop\Core\Product\Search\SortOrder->__construct('product', 'name', 'desc?order=prod...')
#2 /home/jvillagc/public_html/shop/classes/controller/ProductListingFrontController.php(286): PrestaShop\PrestaShop\Core\Product\Search\SortOrder::newFromString('product.name.de...')
#3 /home/jvillagc/public_html/shop/classes/controller/ProductListingFrontController.php(580): ProductListingFrontControllerCore->getProductSearchVariables()
#4 /home/jvillagc/public_html/shop/controllers/fro in /home/jvillagc/public_html/shop/src/Core/Product/Search/SortOrder.php on line 199
```

### Expected behavior

changing short order cannot be a problem nor generate a PHP error.
I don't know if is related to a theme (warehouse) or a core bug.

### Steps to reproduce

1. enter into a category
2. try to change short order type and filters (faceted) using also ASC and DESC

 

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.2

**Comment by florine2623** [comment]
Hello @HartLarsson ,

I can't reproduce your issue on PS `1.7.8.x`, `8.1.x` and `9.0`.

I tried to sort the categories in BO and FO. But I don't have the same as you in my log file in `/var/log/dev.log`.

I'm closing the issue to avoid clogging the backlog. If you have more details to reproduce the issue, let us know.

Thanks.

**Comment by daresh** [comment]
Hello,
it happens in case there is a wrong sort order in the URL. I reproduced it easily on 1.7 / 8.1.

Just go to any category, change products sort order, then modify it (in the URL) to some incorrect one, for example:
en/4-men?order=product.name.a

A fatal error occurs, resulting in a blank page.

It should not behave this way, there should be some error message, not a store crash.

Someone can have a link to the shop with a sort order set, in case the parameter gets corrupted for some reason, there is a blank page.

I think it should fall back to some default sort order instead.

@florine2623 if you don't reopen this issue, I will create a new one.

Recently many of my customers experience this in the logs, must be some bots visiting PrestaShop stores with wrong sort orders.

**Comment by kpodemski** [comment]
I'm reopening this issue, I agree we should silently make things right instead of crashing the store.

**Comment by paulc010** [comment]
You get similar errors with malformed price ranges (PrestaShop\PrestaShop\Core\Localization\Number\Formatter->format()) if the faceted search module is enabled and the root cause is that there's no error checking in ProductListingFrontControllerCore->doProductSearch() as it's intended to be agnostic of sort orders, filters etc. Maybe the solution is to wrap that and catch any exceptions, then redirect to the 404 Controller. Personally I think a malformed url (caused by an error down the chain) should result in a 404 error.

I'm seeing this more and more - and matching with the raw server logs it usually points to a bot (the ChatGPT bot seems to be one example). No idea why it's forming the requests the way it is though.

**Comment by LaBisquerie** [comment]
Hello,
Any news about this issue ?

**Comment by Shoprunners** [comment]
I would just do a Exception handling in the ProductListingFrontController.php class
sth, like. (Around line 330 

```
 // set the sort order if provided in the URL
    if (($encodedSortOrder = Tools::getValue('order'))) {
	try {
		$sortOrder = SortOrder::newFromString($encodedSortOrder);
		$query->setSortOrder($sortOrder);	
	}catch(Exception $exx) {
		//invalid paramets.. just do nothing
	}
    }
```

**Comment by nysander** [comment]
## Root Cause Analysis

I've traced this through the full call chain across PS 8.1, 8.2, 9.0, and 9.1. The bug is still present and unfixed in all versions.

### Call chain

1. **`ProductListingFrontController.php:330`** reads `$_GET['order']` via `Tools::getValue('order')` and passes it unsanitized to `SortOrder::newFromString()`
2. **`SortOrder::newFromString()`** does `explode('.', $sortOrderConfiguration)` — splits on dots, assigns the third segment as `$direction`
3. **`SortOrder::setDirection()`** calls `strtolower($direction)` then checks `in_array($formattedDirection, ['asc', 'desc', 'random'])` — any extra character causes the exception

### Why it crashes

The `order` GET parameter is user-controlled input that reaches `setDirection()` without any validation or sanitization. Malformed URLs like:
- `?order=product.price.desc'` (trailing quote — bots/crawlers)
- `?order=product.name.desc?order=product` (double parameter — as in the original report)
- `?order=product.price.a` (truncated — as @daresh showed)

All cause `InvalidSortOrderDirectionException` and a fatal error / blank page.

### Suggested fix

The fix should be in `ProductListingFrontController` — wrap the `newFromString` call in a try/catch and fall back to the default sort order:

```php
// set the sort order if provided in the URL
if (($encodedSortOrder = Tools::getValue('order'))) {
    try {
        $query->setSortOrder(SortOrder::newFromString($encodedSortOrder));
    } catch (InvalidSortOrderDirectionException $e) {
        // Malformed sort order from user input — fall back to default
    }
}
```

This is the minimal, correct fix. The exception is a validation error on user input, not a programming error — it should be handled gracefully, not crash the store.

### Real-world impact

We're seeing this triggered by bots (ChatGPT bot, various crawlers) sending malformed `order` parameters to category pages. The result is a fatal error and blank page for any visitor who follows such a link.

Confirmed affected: PS 8.1, 8.2, 9.0, 9.1 (checked source for all four).
