### ISSUE TITLE
Updating stock via API call thow error

### ISSUE THREAD

**Issue by malcek** [PrestaShop/PrestaShop#34855]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When we try to update stock from our ERP system over API call it throw an error

java.lang.Exception: Update of 80 stocks failed: Connection failed : 500 ; Respond : <?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[133]]></code>
<message><![CDATA[You can't update stock that is available ; Request : https://pivovarium.si/api/stock_availables/
    at com.metakocka.MetaKockaMain.server.GenericWebShop.PrestaShop.GenericWebShopPrestaShop.updateStock(GenericWebShopPrestaShop.java:749)
    at com.metakocka.MetaKockaMain.server.GenericWebShop.PrestaShop.GenericWebShopPrestaShop.syncProductStockToEShop(GenericWebShopPrestaShop.java:712)
    at com.metakocka.MetaKockaMain.server.DBImpl.WebLinksDBImpl.eShopSyncManualSync(WebLinksDBImpl.java:2341)
    at com.metakocka.MetaKockaMain.server.DBImpl.WebLinksDBImpl.callMethodOnePerCompany(WebLinksDBImpl.java:395)
    at com.metakocka.MetaKockaMain.server.DBImpl.WebLinksDBImpl.callMethod(WebLinksDBImpl.java:303)
    at com.metakocka.MetaKockaMain.server.MainServiceImpl.callMethod(MainServiceImpl.java:3021)
    at com.metakocka.MetaKockaMain.server.MainServiceImpl.callMethod(MainServiceImpl.java:2949)
    at sun.reflect.GeneratedMethodAccessor1397.invoke(Unknown Source)
    
    

### Steps to reproduce

After API call to update stock from our ERP system.

### PrestaShop version(s) where the bug happened

8.0.5

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

API call

**Comment by paulnoelcholot** [comment]
Hello @malcek,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by boo-code** [comment]
This cannot happen on `9.x`, and the error code in the report pins down exactly why.

Error 133 came from `StockAvailable::updateWs()`, which on `8.2.x` reads:

```php
public function updateWs()
{
    if ($this->depends_on_stock) {
        return WebserviceRequest::getInstance()->setError(
            500,
            $this->trans('You cannot update the available stock when it depends on stock.', [], 'Admin.Catalog.Notification'),
            133
        );
    }

    return $this->update();
}
```

The guard refused a webservice update whenever the quantity was driven by advanced stock management rather than stored directly, which is what an ERP pushing quantities into `stock_availables` runs into.

On `9.2.x` the same method is:

```php
public function updateWs()
{
    return $this->update();
}
```

Advanced stock management was removed in 9.0 - `ADVANCED_STOCK_MANAGEMENT` no longer appears anywhere in the code base, while `8.2.x` still has it in `Cart`, `Product` and `PaymentModule` - so `depends_on_stock` no longer gates anything and the branch that produced error 133 is gone. `stock_availables` remains writable through the webservice, with only `POST` and `DELETE` forbidden.

So an ERP doing `PUT /api/stock_availables/{id}` on 9.x no longer meets this error. Worth closing unless someone still sees a 133 on a 9.x shop, which would mean it comes from somewhere else entirely.
