### ISSUE TITLE
$cart->getOrderTotal from module/src/Command

### ISSUE THREAD

**Issue by Maaaleeek** [PrestaShop/PrestaShop#34858]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am trying to create a command in my PrestaShop 1.7 module to generate an order from the client's cart. However, when I attempt to use **$cart->getOrderTotal**, I always encounter a Fatal error.

```
 protected function execute(InputInterface $input, OutputInterface $output){
    try{
        $cart = new Cart(2433);
        $total = (float)$cart->getOrderTotal(true, Cart::BOTH);
        $output->writeln('total '. $total);
    }catch (Exception $e){
        $output->writeln('error'. $e->getMessage());
        die();
    }
}
```

Error:

```
Fatal error - #0 /project/classes/Product.php(3623): ToolsCore::displayError()
#1 /project/classes/Product.php(5632): ProductCore::getPriceStatic(20, false, 0, 6, NULL, false, true, 1)
#2 /project/classes/Cart.php(833): ProductCore::getProductProperties(2, Array)
#3 /project/classes/Cart.php(2144): CartCore->getProducts(false, false, NULL, true, false)
#4 /project/modules/order_install/src/Command/CheckOrderCreationCommand.php(105): CartCore->getOrderTotal(true, 4)
#5 /project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): order_install\Command\CheckOrderCreationCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1010): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(86): Symfony\Component\Console\Application->doRunCommand(Object(order_install\Command\CheckOrderCreationCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(255): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(order_install\Command\CheckOrderCreationCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(74): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /project/bin/console(27): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#12 {main}
```

I think the cause is  `$context->employee` is always NULL from Command

Function : getPriceStatic
File: classes/Product.php

```
if (!$id_cart && !isset($context->employee)) {
   die(Tools::displayError());
}
```

### Steps to reproduce

Make new Command in each module
Try to getOrderTotal of existed Cart
You will get the bug 

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.3.29

**Comment by Hlavtox** [comment]
This happens every time when the context is front office and cart is not provided. I think we should improve it so it works without the cart.

Ping veterans @ShaiMagal @kpodemski

**Comment by rwawiorka** [comment]
@Maaaleeek 
I think you could use LegacyContextLoader class
More described in: https://devdocs.prestashop-project.org/1.7/development/components/console/context-helper/

**Comment by boo-code** [comment]
Still reproduces on `9.2.x`, though the fatal has become an explicit exception:

```php
$cart = new Cart($id);          // no cart in the context
$cart->getOrderTotal(true, Cart::BOTH);
// PrestaShopException: If no employee is assigned in the context, cart ID must be provided to this method.
```

The throw is `classes/Product.php` line 3435:

```php
if (!is_object($cur_cart) || (Validate::isUnsignedInt($id_cart) && $id_cart && $cur_cart->id != $id_cart)) {
    if (!$id_cart && !isset($context->employee)) {
        throw new PrestaShopException('If no employee is assigned in the context, cart ID must be provided to this method.');
    }
```

so it needs either a cart in the context, an explicit `$id_cart`, or an employee. A console command has none of the three.

What makes it avoidable is that the cart is known all along and simply never travels down. `Cart::getOrderTotal()` calls `getProducts()`, which filters on `cp.id_cart = $this->id`, and each row then goes to `Product::getProductProperties()`, which calls `getPriceStatic()` with eight arguments and stops before `$id_cart`:

```php
$row['price_tax_exc'] = $priceTaxExcluded = Product::getPriceStatic(
    (int) $row['id_product'], false, $id_product_attribute, ..., $quantityToUseForPriceCalculations
);
```

So @Hlavtox's reading is right, and the missing piece is narrow: the cart id, not the context.

The conservative shape would be to pass it only when the context has no cart, so every existing flow keeps computing exactly as today and only the case that throws today starts working. Passing it unconditionally would also change back office situations where the employee's context cart differs from the cart being read, which is a pricing behaviour change rather than a fix.

This is the price path, so I would rather not pick between those two on my own. Say which one you want and I will open the PR with a test that calls `getOrderTotal()` with an empty context.
