### ISSUE TITLE
filterProductContent hook bug

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#35043]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When two or more modules implement the "filterProductContent" hook, the following error is produced:

Fatal error: Uncaught TypeError: HookCore::callHookOn(): Argument #3 ($hookArgs) must be of type array, null given, called in C:\websites\clients\test\www\classes\Hook.php on line 981 and defined in C:\websites\clients\test\www\classes\Hook.php:408 Stack trace: #0 C:\websites\clients\test\www\classes\Hook.php(981): HookCore::callHookOn(Object(PfDownloads), 'filterProductCo...', NULL) #1 C:\websites\clients\test\www\controllers\front\ProductController.php(432): HookCore::exec('filterProductCo...', NULL, NULL, false, true, false, NULL, true) #2 C:\websites\clients\test\www\classes\controller\Controller.php(319): ProductControllerCore->initContent() #3 C:\websites\clients\test\www\classes\Dispatcher.php(510): ControllerCore->run() #4 C:\websites\clients\test\www\index.php(28): DispatcherCore->dispatch() #5 {main} thrown in C:\websites\clients\test\www\classes\Hook.php on line 408

But it seems to work OK when only one module is utilising the hook.

### Expected behavior

Any number of modules should be able to utilise this hook.

### Steps to reproduce

1.  Create two separate test modules which both implement the "filterProductContent" hook
2. Load the store front and the error should appear

### PrestaShop version(s) where the bug happened

8.0, 8.1.x

### PHP version(s) where the bug happened

8

**Comment by musaffarpatel** [comment]
My mistake, the $params param needs to be returned from this hook as it's a chained hook
