### ISSUE TITLE
Problem migrating site from localhost to live

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#35111]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I setup a plain Prestashop 8.1.0 site locally (Windows / Laragaon) and then upload the site to my linux server (dumping the files and DB), however the following error appears:

Warning: require_once(/home/webgener/sb.webgeneration.co.uk/classes\Tools.php): Failed to open stream: No such file or directory in /home/webgener/sb.webgeneration.co.uk/vendor/prestashop/autoload/src/Autoloader.php on line 86

Fatal error: Uncaught Error: Failed opening required '/home/webgener/sb.webgeneration.co.uk/classes\Tools.php' (include_path='/home/webgener/sb.webgeneration.co.uk/vendor/pear/pear_exception:/home/webgener/sb.webgeneration.co.uk/vendor/pear/console_getopt:/home/webgener/sb.webgeneration.co.uk/vendor/pear/pear-core-minimal/src:/home/webgener/sb.webgeneration.co.uk/vendor/pear/archive_tar:.:/opt/cpanel/ea-php81/root/usr/share/pear') in /home/webgener/sb.webgeneration.co.uk/vendor/prestashop/autoload/src/Autoloader.php:86 Stack trace: #0 /home/webgener/sb.webgeneration.co.uk/vendor/prestashop/autoload/src/Autoloader.php(96) : eval()'d code(1): PrestaShop\Autoload\Autoloader->load('ToolsCore') #1 /home/webgener/sb.webgeneration.co.uk/vendor/prestashop/autoload/src/Autoloader.php(96): eval() #2 /home/webgener/sb.webgeneration.co.uk/config/config.inc.php(83): PrestaShop\Autoload\Autoloader->load('Tools') #3 /home/webgener/sb.webgeneration.co.uk/index.php(27): require('/home/webgener/...') #4 {main} thrown in /home/webgener/sb.webgeneration.co.uk/vendor/prestashop/autoload/src/Autoloader.php on line 86

I've done this in the past without issues (Prestashop 1.7)

It looks like it may have something to do with the directory separator but I can't see how this can be changed.

### Steps to reproduce

Setup a fresh Prestashop site locally on Windows
Migrate site by dumping the DB and files across to a unix server

### PrestaShop version(s) where the bug happened

8.1.0

**Comment by musaffarpatel** [comment]
Cache needed to be cleared, how embarrassing
