### ISSUE TITLE
 Autoupgrade - From 1.7.1.0 to 1.7.3.0 - My 1.7.3.0 will still be blank 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#35987]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I do an Upgrade from 1.7.1.0 to 1.7.3.0, with a dev autoupgrade, I can do the upgrade but my shop after that will be blank all time ( 1.7.3.0 should be support php 7.1) as you can see : 

[recording(196).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/df38e69d-9b21-4d40-adaf-09475ef1cb6b)

### Expected behavior

I wish I could use my Prestashop Version 1.7.3.0 entirely 

### Steps to reproduce

1. Install Prestashop V1.7.1.0 
2. Install Autoupgrade dev mod (for exemple https://github.com/PrestaShop/autoupgrade/pull/688 )
3. Do an upgrade from 1.7.1.0 to 1.7.3.0 thank to local archive
4. Clic on Dashboard to go an you shop v1.7.3.0 :x:

### PrestaShop version(s) where the bug happened

1.7.3.0

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.1 from dev branch (https://github.com/PrestaShop/autoupgrade/pull/688)

### Your company or customer's name goes here (if applicable).

PS

**Comment by Hlavtox** [comment]
> Avoid reporting "error 500" or "white page" errors - this is a universal error message that does not provide enough information to qualify the issue. Enable debug mode in the Performance section of PrestaShop or manually in /config/defines.inc.php and try again. You should get a proper error message.

**Comment by Quetzacoalt91** [comment]
Managed to reproduce the error:
![image](https://github.com/PrestaShop/PrestaShop/assets/6768917/0fb2f58e-f826-457e-b1a0-2367bad5d1e0)

**Comment by ga-devfront** [comment]
```
PHP Fatal error:  Uncaught Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException: Cannot dump definition because of invalid class name (NULL) in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:1403\nStack trace:\n
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php(790): Symfony\\Component\\DependencyInjection\\Dumper\\PhpDumper->dumpLiteralClass('NULL')\n
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php(394): Symfony\\Component\\DependencyInjection\\Dumper\\PhpDumper->addNewInstance('_defaults', Object(Symfony\\Component\\DependencyInjection\\Definition), 'return ', '$this->services...')\n
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php(639): Symfony\\Component\\DependencyInjection\\Dumper\\PhpDumper->addServiceInstance('_defaults', Object(Symfony\\Component\\DependencyInjection\\Definition))\n#3 /var/www/html/vendor/symfony/symfony in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php on line 1403
```

With last version, then I try the update I got this error. We have to investigate on it.
