### ISSUE TITLE
Array to string conversion in tools\profiling\Profiler.php on line 165

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#36738]
### Steps to reproduce

1. Install develop.
2. Enable debug profiler in BO.
3. Visit a product page in FO.
4. See `Array to string conversion in C:\xampp\htdocs\dev\tools\profiling\Profiler.php on line 165`

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.3

**Comment by kpodemski** [comment]
Unfortunately, I can't reproduce this issue. I see that it is related to this piece of code:

```
foreach ($GLOBALS as $key => $value) {
            if ($key === 'GLOBALS') {
                continue;
            }
            $this->totalGlobalVarSize += ($size = $this->getVarSize($value));

            if ($size > 1024) {
                $this->globalVarSize[$key] = round($size / 1024);
            }
        }
```

but seems that it fails only if the data is array, but... why is this data array? could you add dump here:

```
private function getVarData($var)
    {
        // test
        if (is_array($var)) { dump($var); exit; }

        if (is_object($var)) {
            return $var;
        }

        return (string) $var;
    }
```

**Comment by Hlavtox** [comment]
@kpodemski 

```
 array:223 [▼
  "objectmodel_def_Shop" => array:4 [▶]
  "objectmodel_Shop_1_0_0" => array:7 [▶]
  "Shop::setUrl_1" => array:4 [▶]
  "objectmodel_def_Country" => array:6 [▶]
  "objectmodel_Country_16_1_1" => array:11 [▶]
  "objectmodel_def_ShopGroup" => array:4 [▶]
  "objectmodel_ShopGroup_1_0_0" => array:7 [▶]
  "objectmodel_def_Language" => array:4 [▶]
  "objectmodel_Language_1_1_0" => array:8 [▶]
  "objectmodel_shop_Language_1-1" => true
  "objectmodel_def_Customer" => array:4 [▶]
  "objectmodel_Customer_3_0_0" => array:32 [▶]
  "Language::getIdByIso_cs" => 1
  "active_hooks" => array:1034 [▶]
  "hook_module_exec_list__1_3" => array:133 [▶]
  "hook_aliases" => array:85 [▶]
  "hook_aliases_actionAfterLoadRoutes" => []
  "hook_aliases_actionDispatcherBefore" => []
  "objectmodel_def_Category" => array:7 [▶]
  "objectmodel_Category_3_1_1" => array:20 [▶]
  "hook_aliases_actionFrontControllerInitBefore" => []
  "hook_aliases_actionControllerInitBefore" => []
  "Language::getIdByLocale_cs-CZ" => 1
  "Currency::getIdByIsoCode_CZK-0-deleted" => 1
  "objectmodel_def_Currency" => array:6 [▶]
  "objectmodel_Currency_1_1_1" => array:11 [▶]
  "hook_aliases_actionControllerInitAfter" => []
  "objectmodel_def_Cart" => array:4 [▶]
  "objectmodel_Cart_7_0_0" => array:18 [▶]
  "objectmodel_def_Group" => array:6 [▶]
  "objectmodel_Group_2_1_0" => array:6 [▶]
  "objectmodel_shop_Group_2-1" => true
  "objectmodel_Currency_1_1_0" => array:11 [▶]
  "objectmodel_shop_Currency_1-1" => true
  "Customer::isBanned_3" => false
  "Cart::getCartRules_7-1" => array:1 [▶]
  "objectmodel_def_Address" => array:4 [▶]
  "objectmodel_Address_7_0_0" => array:23 [▶]
  "country_getNameById_16_1" => "Česko"
  "Address::initialize_7" => Address {#141 ▶}
  "product_id_tax_rules_group_5_1" => 1
  "hook_idsbyname_withalias" => array:1114 [▶]
  "hook_module_list" => array:135 [ …135]
  "objectmodel_def_Tax" => array:6 [ …6]
  "objectmodel_Tax_1_0_0" => array:4 [ …4]
  "16-0-530 09-1" => TaxCalculator {#133 …2}
  "hook_aliases_actionProductPriceCalculation" => []
  "16-0-530 09-0" => TaxCalculator {#132 …2}
  "StockAvailable::getQuantityAvailableByProduct_5-0-0" => 900
  "StockAvailable::getQuantityAvailableByProduct_5-19-0" => 300
  "Product::getAttributesParams_5-19-1" => array:1 [ …1]
  "16-0-0-1" => TaxCalculator {#126 …2}
  "objectmodel_def_Combination" => array:6 [ …6]
  "objectmodel_Combination_19_1_0" => array:19 [ …19]
  "hook_aliases_actionGetProductPropertiesAfterUnitPrice" => []
  "Product::getPriceStatic_5-7" => 55
  "Image::getBestImageAttribute-5-19-1-1" => array:2 [ …2]
  "product_id_tax_rules_group_1_1" => 1
  "StockAvailable::getQuantityAvailableByProduct_1-0-0" => 2400
  "StockAvailable::getQuantityAvailableByProduct_1-1-0" => 300
  "Product::getAttributesParams_1-1-1" => array:2 [ …2]
  "objectmodel_Combination_1_1_0" => array:19 [ …19]
  "Product::getPriceStatic_1-7" => 1
  "Image::getBestImageAttribute-1-1-1-1" => array:2 [ …2]
  "objectmodel_def_CartRule" => array:6 [ …6]
  "objectmodel_CartRule_1_0_1" => array:33 [ …33]
  "Cart::getOrderedCartRulesIds_7-1-ids" => array:1 [ …1]
  "getContextualValue_1_1_7_1_5_19_1_1" => 23.14
  "getContextualValue_1_0_7_1_5_19_1_1" => 19.12
  "hook_aliases_actionValidateCartRule" => []
  "objectmodel_Country_16_1_0" => array:11 [ …11]
  "hook_aliases_actionFrontControllerInitAfter" => array:1 [ …1]
  "Category::checkAccess_3-3" => true
  "hook_aliases_actionPresentCategory" => []
  "hook_aliases_filterCategoryContent" => []
  "hook_aliases_actionFrontControllerSetMedia" => []
  "hook_idsbyname" => array:1034 [ …1034]
  "exceptionsCache" => []
  "hook_canonical_names" => array:86 [ …86]
  "hook_aliases_actionPresentCart" => []
  "presentedCart_17" => 
PrestaShop\PrestaShop\Adapter\Presenter\Cart
\
CartLazyArray {#122 …23}
  "hook_aliases_filterHtmlContent" => []
  "objectmodel_def_Gender" => array:6 [ …6]
  "objectmodel_Gender_1_0_0" => array:3 [ …3]
  "objectmodel_def_Risk" => array:6 [ …6]
  "objectmodel_def_AddressFormat" => array:4 [ …4]
  "AddressFormat::getFormatDB16" => """
    firstname lastname

    company

    vat_number

    address1

    address2

    postcode city

    Country:name

    phone
    """
  "Meta::getCategoryMetas3-1" => array:20 [ …20]
  "Module::getModuleIdByName_ps_legalcompliance" => 0
  "Module::isEnabledps_legalcompliance" => false
  "objectmodel_Category_3_1_2" => array:20 [ …20]
  "objectmodel_Category_3_1_3" => array:20 [ …20]
  "objectmodel_Category_3_1_4" => array:20 [ …20]
  "objectmodel_Category_3_1_5" => array:20 [ …20]
  "objectmodel_def_State" => array:4 [ …4]
  "hook_aliases_actionFrontControllerSetVariables" => []
  "Cart::getCartRules_7-4" => array:1 [ …1]
  "getContextualValue_1_1_7_4_5_19_1_1" => 23.14
  "getContextualValue_1_0_7_4_5_19_1_1" => 19.12
  "objectmodel_def_Product" => array:7 [ …7]
  "objectmodel_Product_5_1_1" => array:67 [ …67]
  "hook_aliases_actionPresentProductListing" => []
  "objectmodel_Product_1_1_1" => array:67 [ …67]
  "hook_aliases_actionBuildFrontEndObject" => []
  "hook_aliases_displayHeader" => array:1 [ …1]
  "hook_aliases_productSearchProvider" => []
  "hook_aliases_actionProductSearchProviderRunQueryBefore" => []
  "objectmodel_Category_3_1_0" => array:20 [ …20]
  "hook_aliases_actionProductSearchProviderRunQueryAfter" => []
  "product_id_tax_rules_group_2_1" => 1
  "StockAvailable::getQuantityAvailableByProduct_2-0-0" => 2100
  "StockAvailable::getQuantityAvailableByProduct_2-9-0" => 1200
  "Product::getAttributesParams_2-9-1" => array:1 [ …1]
  "objectmodel_Combination_9_1_0" => array:19 [ …19]
  "objectmodel_Product_2_1_1" => array:67 [ …67]
  "hook_aliases_filterProductSearch" => []
  "hook_aliases_actionProductSearchAfter" => []
  "hook_aliases_displayOverrideTemplate" => []
  "hook_aliases_displayAfterTitleTag" => []
  "objectmodel_Product_5_1_0" => array:67 [ …67]
  "Address::isCountryActiveById_7" => true
  "Carrier::getAvailableCarrierList_5-1" => []
  "Carrier::getCarriers_b13c102c294473a7b2c681a5311e4296" => array:2 [ …2]
  "objectmodel_def_Carrier" => array:7 [ …7]
  "objectmodel_Carrier_1_1_0" => array:20 [ …20]
  "objectmodel_Carrier_2_1_0" => array:20 [ …20]
  "Carrier::getMaxDeliveryPriceByWeight_2-1" => "5.000000"
  "Cart::getCartRules_7-3" => []
  "objectmodel_Carrier_2_1_1" => array:20 [ …20]
  "carrier_id_tax_rules_group_2_1" => 1
  "getPackageShippingCost_7_7_2_1_16_1_5_19_1_1" => 8.47
  "hook_aliases_actionCartGetPackageShippingCost" => []
  "getPackageShippingCost_7_7_2_0_16_1_5_19_1_1" => 7.0
  "Carrier::getAvailableCarrierList_getCarriersForOrder_1-7" => array:2 [ …2]
  "objectmodel_Product_1_1_0" => array:67 [ …67]
  "Carrier::getAvailableCarrierList_1-1" => []
  "objectmodel_Carrier_1_1_1" => array:20 [ …20]
  "getPackageShippingCost_7_7_1_1_16_0_5_19_1_1" => 0
  "getPackageShippingCost_7_7_1_0_16_0_5_19_1_1" => 0
  "getPackageShippingCost_7_7_2_1_16_0_5_19_1_1" => 8.47
  "getPackageShippingCost_7_7_2_0_16_0_5_19_1_1" => 7.0
  "hook_aliases_actionFilterDeliveryOptionList" => []
  "5_19_quantity" => 300
  "Address::initialize_c74d97b01eae257e44aa9d5bade97baf" => Address {#1838 …40}
  "16-0-0-0" => TaxCalculator {#1840 …2}
  "StockAvailable::getQuantityAvailableByProduct_5-20-0" => 300
  "5_20_quantity" => 300
  "StockAvailable::getQuantityAvailableByProduct_5-21-0" => 300
  "5_21_quantity" => 300
  "hook_aliases_actionProductFlagsModifier" => []
  "1_1_quantity" => 300
  "StockAvailable::getQuantityAvailableByProduct_1-2-0" => 300
  "1_2_quantity" => 300
  "StockAvailable::getQuantityAvailableByProduct_1-3-0" => 300
  "1_3_quantity" => 300
  "StockAvailable::getQuantityAvailableByProduct_1-4-0" => 300
  "1_4_quantity" => 300
  "StockAvailable::getQuantityAvailableByProduct_1-5-0" => 300
  "1_5_quantity" => 300
  "StockAvailable::getQuantityAvailableByProduct_1-6-0" => 300
  "1_6_quantity" => 300
  "StockAvailable::getQuantityAvailableByProduct_1-7-0" => 300
  "1_7_quantity" => 300
  "StockAvailable::getQuantityAvailableByProduct_1-8-0" => 300
  "1_8_quantity" => 300
  "Product::getAttributesParams_1-2-1" => array:2 [ …2]
  "hook_aliases_displayAfterBodyOpeningTag" => []
  "hook_aliases_displayBanner" => []
  "hook_aliases_displayNav1" => []
  "Module::getModuleIdByName_ps_contactinfo" => 4
  "Module::isEnabledps_contactinfo" => true
  "hook_aliases_displayNav2" => []
  "Module::getModuleIdByName_ps_languageselector" => 5
  "Module::isEnabledps_languageselector" => true
  "Module::getModuleIdByName_ps_currencyselector" => 6
  "Module::isEnabledps_currencyselector" => true
  "Module::getModuleIdByName_ps_customersignin" => 7
  "Module::isEnabledps_customersignin" => true
  "Module::getModuleIdByName_ps_shoppingcart" => 8
  "Module::isEnabledps_shoppingcart" => true
  "hook_aliases_displayTop" => array:1 [ …1]
  "Module::getModuleIdByName_ps_mainmenu" => 9
  "Module::isEnabledps_mainmenu" => true
  "Module::getModuleIdByName_ps_searchbar" => 10
  "Module::isEnabledps_searchbar" => true
  "hook_aliases_displayNavFullWidth" => []
  "hook_aliases_displayWrapperTop" => []
  "hook_aliases_displayLeftColumn" => array:1 [ …1]
  "Module::getModuleIdByName_ps_categorytree" => 21
  "Module::isEnabledps_categorytree" => true
  "hook_aliases_displayContentWrapperTop" => []
  "objectmodel_Category_4_1_1" => array:20 [ …20]
  "objectmodel_Category_5_1_1" => array:20 [ …20]
  "hook_aliases_displayHeaderCategory" => []
  "objectmodel_Product_2_1_0" => array:67 [ …67]
  "2_9_quantity" => 1200
  "StockAvailable::getQuantityAvailableByProduct_2-10-0" => 300
  "2_10_quantity" => 300
  "StockAvailable::getQuantityAvailableByProduct_2-11-0" => 300
  "2_11_quantity" => 300
  "StockAvailable::getQuantityAvailableByProduct_2-12-0" => 300
  "2_12_quantity" => 300
  "hook_aliases_displayProductListReviews" => []
  "Module::getModuleIdByName_productcomments" => 20
  "Module::isEnabledproductcomments" => true
  "hook_aliases_displayFooterCategory" => []
  "hook_aliases_displayContentWrapperBottom" => []
  "hook_aliases_displayWrapperBottom" => []
  "hook_aliases_displayFooterBefore" => []
  "Module::getModuleIdByName_ps_emailsubscription" => 17
  "Module::isEnabledps_emailsubscription" => true
  "hook_aliases_displayGDPRConsent" => []
  "Module::getModuleIdByName_ps_socialfollow" => 18
  "Module::isEnabledps_socialfollow" => true
  "hook_aliases_displayFooter" => array:1 [ …1]
  "Module::getModuleIdByName_ps_linklist" => 1
  "Module::isEnabledps_linklist" => true
  "Module::getModuleIdByName_ps_customeraccountlinks" => 19
  "Module::isEnabledps_customeraccountlinks" => true
  "hook_aliases_displayFooterAfter" => []
  "hook_aliases_displayBeforeBodyClosingTag" => []
  "objectmodel_def_ConnectionsSource" => array:4 [ …4]
  "hook_aliases_actionOutputHTMLBefore" => []
]
```

**Comment by Hlavtox** [comment]
@kpodemski It's the cache variable

```
$cache = Cache::retrieveAll();
$this->totalCacheSize = $this->getVarSize($cache);
```

It cannot be serialized because it throws

```
Fatal error: Uncaught BadMethodCallException: Cannot serialize Symfony\Component\Cache\Adapter\FilesystemAdapter in C:\xampp\htdocs\dev\vendor\symfony\cache\Traits\FilesystemCommonTrait.php:172 Stack trace: #0 [internal function]: Symfony\Component\Cache\Adapter\FilesystemAdapter->__sleep() #1 C:\xampp\htdocs\dev\tools\profiling\Profiler.php(229): serialize(Array) #2 C:\xampp\htdocs\dev\tools\profiling\Controller.php(122): Profiler->processData() #3 C:\xampp\htdocs\dev\tools\profiling\Controller.php(88): Controller->displayProfiling() #4 C:\xampp\htdocs\dev\classes\Dispatcher.php(492): Controller->run() #5 C:\xampp\htdocs\dev\index.php(73): DispatcherCore->dispatch() #6 {main} thrown in C:\xampp\htdocs\dev\vendor\symfony\cache\Traits\FilesystemCommonTrait.php on line 172
```

so it gets passed into `getVarData` which can work only with string castable things and objects

**Comment by kpodemski** [comment]
@Hlavtox yep, solution could be to do:

```
if (is_array($var)) {
            return (object) $var;
        }
```

**Comment by ingridusta** [comment]
Hello @Hlavtox ,

I reproduce the issue with PrestaShop version 9.0.x and PHP 8.1.13, I'll add this to the backlog so it can be fixed.

![Capture d’écran 2024-09-25 à 14 23 16](https://github.com/user-attachments/assets/3c6564c6-20a4-4381-9e38-f40ac93e681e)


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

**As a reminder @Hlavtox, do not forget for your next bug report to check the Prerequisites' boxes.**

Thank you

**Comment by musicpanda** [comment]
This bug is also present in PS 8.2.0 In that case it is on line 158.

Steps to reproduce:
 - have a shop with more than one language
 - enable debug mode and profiling.
 - Go to the home page.
 - This is will produce a redirect page that redirects you to a language page (like from www.domain.com/ to www.domain.com/fr/)
 - On the redirect page you will see the error.
