### ISSUE TITLE
Fatal error: Uncaught SmartyException: Unable to load template module:ps_brandlist/views/templates/_partials/$brand_display_type.tpl

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#36739]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There is a fatal error on category pages. The ps_brandlist template seems weird - `{include file="module:ps_brandlist/views/templates/_partials/$brand_display_type.tpl" brands=$brands}`, is this syntax allowed?

### Expected behavior

...

### Steps to reproduce

1. Install develop.
2. Use hummingbird.
3. Go to category page.
4. I see following error.

```
Fatal error</b>:  Uncaught SmartyException: Unable to load template 'module:ps_brandlist/views/templates/_partials/$brand_display_type.tpl' in C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php:96
Stack trace:
#0 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(384): Smarty_Template_Compiled-&gt;render(Object(SmartyDevTemplate))
#1 C:\xampp\htdocs\dev\var\cache\dev\smarty\compile\hummingbird\ad\76\05\ad7605d3e1afaa968ac113b0444601df2cff1153_2.module.ps_brandlistviewstemplateshookps_brandlist.tpl.cache.php(50): Smarty_Internal_Template-&gt;_subTemplateRender('module:ps_brand...', 'ps_brandlist|1|...', 'hummingbird', 9999, 31536000, Array, 0, true)
#2 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_66c5a6cec7db02_71722892(Object(SmartyDevTemplate))
#3 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base-&gt;getRenderedTemplateCode(Object(SmartyDevTemplate))
#4 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_updatecache.php(38): Smarty_Template_Compiled-&gt;render(Object(SmartyDevTemplate))
#5 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_cached.php(143): Smarty_Internal_Runtime_UpdateCache-&gt;updateCache(Object(Smarty_Template_Cached), Object(SmartyDevTemplate), false)
#6 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(212): Smarty_Template_Cached-&gt;render(Object(SmartyDevTemplate), false)
#7 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(238): Smarty_Internal_Template-&gt;render(false, 0)
#8 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase-&gt;_execute(Object(SmartyDevTemplate), NULL, NULL, NULL, 0)
#9 C:\xampp\htdocs\dev\classes\Smarty\SmartyDevTemplate.php(55): Smarty_Internal_TemplateBase-&gt;fetch(NULL, NULL, NULL, NULL)
#10 C:\xampp\htdocs\dev\classes\module\Module.php(2238): SmartyDevTemplateCore-&gt;fetch()
#11 C:\xampp\htdocs\dev\modules\ps_brandlist\ps_brandlist.php(268): ModuleCore-&gt;fetch('module:ps_brand...', 'ps_brandlist|1|...')
#12 C:\xampp\htdocs\dev\classes\Hook.php(1091): Ps_Brandlist-&gt;renderWidget('displayLeftColu...', Array)
#13 C:\xampp\htdocs\dev\tools\profiling\Hook.php(64): HookCore::coreRenderWidget(Object(Ps_Brandlist), 'displayLeftColu...', Array)
#14 C:\xampp\htdocs\dev\classes\Hook.php(1022): Hook::coreRenderWidget(Object(Ps_Brandlist), 'displayLeftColu...', Array)
#15 C:\xampp\htdocs\dev\config\smarty.config.inc.php(195): HookCore::exec('displayLeftColu...', Array, NULL)
#16 C:\xampp\htdocs\dev\classes\Smarty\SmartyLazyRegister.php(81): smartyHook(Array, Object(SmartyDevTemplate))
#17 C:\xampp\htdocs\dev\var\cache\dev\smarty\compile\hummingbirdlayouts_layout_left_column_tpl\ff\5b\1e\ff5b1e894b0eb45a70d92185e39c0f7811409100_2.file.layout-left-column.tpl.php(55): SmartyLazyRegister-&gt;__call('smartyHook', Array)
#18 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(248): Block_163327635566c5a6ceb0fc02_22114186-&gt;callBlock(Object(SmartyDevTemplate))
#19 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance-&gt;callBlock(Object(Block_163327635566c5a6ceb0fc02_22114186), Object(SmartyDevTemplate))
#20 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance-&gt;process(Object(SmartyDevTemplate), Object(Block_163327635566c5a6ceb0fc02_22114186))
#21 C:\xampp\htdocs\dev\var\cache\dev\smarty\compile\hummingbirdlayouts_layout_left_column_tpl\ff\5b\1e\ff5b1e894b0eb45a70d92185e39c0f7811409100_2.file.layout-left-column.tpl.php(139): Smarty_Internal_Runtime_Inheritance-&gt;instanceBlock(Object(SmartyDevTemplate), 'Block_163327635...', 'left_column', 2)
#22 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(248): Block_154416477666c5a6ceb0f2a7_91531281-&gt;callBlock(Object(SmartyDevTemplate))
#23 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance-&gt;callBlock(Object(Block_154416477666c5a6ceb0f2a7_91531281), Object(SmartyDevTemplate))
#24 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(186): Smarty_Internal_Runtime_Inheritance-&gt;process(Object(SmartyDevTemplate), Object(Block_154416477666c5a6ceb0f2a7_91531281), Object(Block_24160866966c5a6ceb1fd30_00046701))
#25 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance-&gt;process(Object(SmartyDevTemplate), Object(Block_24160866966c5a6ceb1fd30_00046701))
#26 C:\xampp\htdocs\dev\var\cache\dev\smarty\compile\hummingbirdlayouts_layout_left_column_tpl\d6\e7\55\d6e755b8c68f0287e62b5454379c9d45f530f0c3_2.file.layout-both-columns.tpl.php(85): Smarty_Internal_Runtime_Inheritance-&gt;instanceBlock(Object(SmartyDevTemplate), 'Block_241608669...', 'content_columns')
#27 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_66c5a6ceb25742_00506099(Object(SmartyDevTemplate))
#28 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base-&gt;getRenderedTemplateCode(Object(SmartyDevTemplate))
#29 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(217): Smarty_Template_Compiled-&gt;render(Object(SmartyDevTemplate))
#30 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(386): Smarty_Internal_Template-&gt;render()
#31 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(115): Smarty_Internal_Template-&gt;_subTemplateRender('layouts/layout-...', NULL, 'hummingbirdlayo...', 0, 3600, Array, 2, false, NULL, NULL)
#32 C:\xampp\htdocs\dev\var\cache\dev\smarty\compile\hummingbirdlayouts_layout_left_column_tpl\ff\5b\1e\ff5b1e894b0eb45a70d92185e39c0f7811409100_2.file.layout-left-column.tpl.php(33): Smarty_Internal_Runtime_Inheritance-&gt;endChild(Object(SmartyDevTemplate), 'layouts/layout-...')
#33 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_66c5a6ceb12153_00739933(Object(SmartyDevTemplate))
#34 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base-&gt;getRenderedTemplateCode(Object(SmartyDevTemplate))
#35 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(217): Smarty_Template_Compiled-&gt;render(Object(SmartyDevTemplate))
#36 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(386): Smarty_Internal_Template-&gt;render()
#37 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(115): Smarty_Internal_Template-&gt;_subTemplateRender('layouts/layout-...', NULL, 'hummingbirdlayo...', 0, 3600, Array, 2, false, NULL, NULL)
#38 C:\xampp\htdocs\dev\var\cache\dev\smarty\compile\hummingbirdlayouts_layout_left_column_tpl\ad\62\c8\ad62c86cddd8c923dd6be5e664d2b8ce311558c4_2.file.product-list.tpl.php(43): Smarty_Internal_Runtime_Inheritance-&gt;endChild(Object(SmartyDevTemplate), 'layouts/layout-...')
#39 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_66c5a6ceb03605_60906397(Object(SmartyDevTemplate))
#40 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base-&gt;getRenderedTemplateCode(Object(SmartyDevTemplate))
#41 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(217): Smarty_Template_Compiled-&gt;render(Object(SmartyDevTemplate))
#42 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(386): Smarty_Internal_Template-&gt;render()
#43 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(115): Smarty_Internal_Template-&gt;_subTemplateRender('catalog/listing...', NULL, 'hummingbirdlayo...', 0, 3600, Array, 2, false, NULL, NULL)
#44 C:\xampp\htdocs\dev\var\cache\dev\smarty\compile\hummingbirdlayouts_layout_left_column_tpl\45\23\32\452332e5a3fcd632b97d3376549524ceaeee6c88_2.file.category.tpl.php(40): Smarty_Internal_Runtime_Inheritance-&gt;endChild(Object(SmartyDevTemplate), 'catalog/listing...')
#45 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_66c5a6ceaeea64_45145874(Object(SmartyDevTemplate))
#46 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base-&gt;getRenderedTemplateCode(Object(SmartyDevTemplate))
#47 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(217): Smarty_Template_Compiled-&gt;render(Object(SmartyDevTemplate))
#48 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(238): Smarty_Internal_Template-&gt;render(false, 0)
#49 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase-&gt;_execute(Object(SmartyDevTemplate), NULL, 'hummingbirdlayo...', NULL, 0)
#50 C:\xampp\htdocs\dev\classes\Smarty\SmartyDev.php(40): Smarty_Internal_TemplateBase-&gt;fetch('catalog/listing...', NULL, 'hummingbirdlayo...', NULL)
#51 C:\xampp\htdocs\dev\classes\controller\FrontController.php(726): SmartyDev-&gt;fetch('catalog/listing...', NULL, 'hummingbirdlayo...')
#52 C:\xampp\htdocs\dev\classes\controller\FrontController.php(708): FrontControllerCore-&gt;smartyOutputContent('catalog/listing...')
#53 C:\xampp\htdocs\dev\tools\profiling\Controller.php(111): FrontControllerCore-&gt;display()
#54 C:\xampp\htdocs\dev\tools\profiling\Controller.php(88): Controller-&gt;displayProfiling()
#55 C:\xampp\htdocs\dev\classes\Dispatcher.php(492): Controller-&gt;run()
#56 C:\xampp\htdocs\dev\index.php(73): DispatcherCore-&gt;dispatch()
#57 {main}

Next PrestaShop\PrestaShop\Core\Exception\CoreException: Unable to load template 'module:ps_brandlist/views/templates/_partials/$brand_display_type.tpl' in C:\xampp\htdocs\dev\classes\Hook.php:1095
Stack trace:
#0 C:\xampp\htdocs\dev\tools\profiling\Hook.php(64): HookCore::coreRenderWidget(Object(Ps_Brandlist), 'displayLeftColu...', Array)
#1 C:\xampp\htdocs\dev\classes\Hook.php(1022): Hook::coreRenderWidget(Object(Ps_Brandlist), 'displayLeftColu...', Array)
#2 C:\xampp\htdocs\dev\config\smarty.config.inc.php(195): HookCore::exec('displayLeftColu...', Array, NULL)
#3 C:\xampp\htdocs\dev\classes\Smarty\SmartyLazyRegister.php(81): smartyHook(Array, Object(SmartyDevTemplate))
#4 C:\xampp\htdocs\dev\var\cache\dev\smarty\compile\hummingbirdlayouts_layout_left_column_tpl\ff\5b\1e\ff5b1e894b0eb45a70d92185e39c0f7811409100_2.file.layout-left-column.tpl.php(55): SmartyLazyRegister-&gt;__call('smartyHook', Array)
#5 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(248): Block_163327635566c5a6ceb0fc02_22114186-&gt;callBlock(Object(SmartyDevTemplate))
#6 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance-&gt;callBlock(Object(Block_163327635566c5a6ceb0fc02_22114186), Object(SmartyDevTemplate))
#7 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance-&gt;process(Object(SmartyDevTemplate), Object(Block_163327635566c5a6ceb0fc02_22114186))
#8 C:\xampp\htdocs\dev\var\cache\dev\smarty\compile\hummingbirdlayouts_layout_left_column_tpl\ff\5b\1e\ff5b1e894b0eb45a70d92185e39c0f7811409100_2.file.layout-left-column.tpl.php(139): Smarty_Internal_Runtime_Inheritance-&gt;instanceBlock(Object(SmartyDevTemplate), 'Block_163327635...', 'left_column', 2)
#9 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(248): Block_154416477666c5a6ceb0f2a7_91531281-&gt;callBlock(Object(SmartyDevTemplate))
#10 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance-&gt;callBlock(Object(Block_154416477666c5a6ceb0f2a7_91531281), Object(SmartyDevTemplate))
#11 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(186): Smarty_Internal_Runtime_Inheritance-&gt;process(Object(SmartyDevTemplate), Object(Block_154416477666c5a6ceb0f2a7_91531281), Object(Block_24160866966c5a6ceb1fd30_00046701))
#12 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance-&gt;process(Object(SmartyDevTemplate), Object(Block_24160866966c5a6ceb1fd30_00046701))
#13 C:\xampp\htdocs\dev\var\cache\dev\smarty\compile\hummingbirdlayouts_layout_left_column_tpl\d6\e7\55\d6e755b8c68f0287e62b5454379c9d45f530f0c3_2.file.layout-both-columns.tpl.php(85): Smarty_Internal_Runtime_Inheritance-&gt;instanceBlock(Object(SmartyDevTemplate), 'Block_241608669...', 'content_columns')
#14 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_66c5a6ceb25742_00506099(Object(SmartyDevTemplate))
#15 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base-&gt;getRenderedTemplateCode(Object(SmartyDevTemplate))
#16 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(217): Smarty_Template_Compiled-&gt;render(Object(SmartyDevTemplate))
#17 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(386): Smarty_Internal_Template-&gt;render()
#18 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(115): Smarty_Internal_Template-&gt;_subTemplateRender('layouts/layout-...', NULL, 'hummingbirdlayo...', 0, 3600, Array, 2, false, NULL, NULL)
#19 C:\xampp\htdocs\dev\var\cache\dev\smarty\compile\hummingbirdlayouts_layout_left_column_tpl\ff\5b\1e\ff5b1e894b0eb45a70d92185e39c0f7811409100_2.file.layout-left-column.tpl.php(33): Smarty_Internal_Runtime_Inheritance-&gt;endChild(Object(SmartyDevTemplate), 'layouts/layout-...')
#20 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_66c5a6ceb12153_00739933(Object(SmartyDevTemplate))
#21 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base-&gt;getRenderedTemplateCode(Object(SmartyDevTemplate))
#22 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(217): Smarty_Template_Compiled-&gt;render(Object(SmartyDevTemplate))
#23 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(386): Smarty_Internal_Template-&gt;render()
#24 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(115): Smarty_Internal_Template-&gt;_subTemplateRender('layouts/layout-...', NULL, 'hummingbirdlayo...', 0, 3600, Array, 2, false, NULL, NULL)
#25 C:\xampp\htdocs\dev\var\cache\dev\smarty\compile\hummingbirdlayouts_layout_left_column_tpl\ad\62\c8\ad62c86cddd8c923dd6be5e664d2b8ce311558c4_2.file.product-list.tpl.php(43): Smarty_Internal_Runtime_Inheritance-&gt;endChild(Object(SmartyDevTemplate), 'layouts/layout-...')
#26 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_66c5a6ceb03605_60906397(Object(SmartyDevTemplate))
#27 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base-&gt;getRenderedTemplateCode(Object(SmartyDevTemplate))
#28 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(217): Smarty_Template_Compiled-&gt;render(Object(SmartyDevTemplate))
#29 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(386): Smarty_Internal_Template-&gt;render()
#30 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php(115): Smarty_Internal_Template-&gt;_subTemplateRender('catalog/listing...', NULL, 'hummingbirdlayo...', 0, 3600, Array, 2, false, NULL, NULL)
#31 C:\xampp\htdocs\dev\var\cache\dev\smarty\compile\hummingbirdlayouts_layout_left_column_tpl\45\23\32\452332e5a3fcd632b97d3376549524ceaeee6c88_2.file.category.tpl.php(40): Smarty_Internal_Runtime_Inheritance-&gt;endChild(Object(SmartyDevTemplate), 'catalog/listing...')
#32 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_66c5a6ceaeea64_45145874(Object(SmartyDevTemplate))
#33 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base-&gt;getRenderedTemplateCode(Object(SmartyDevTemplate))
#34 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(217): Smarty_Template_Compiled-&gt;render(Object(SmartyDevTemplate))
#35 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(238): Smarty_Internal_Template-&gt;render(false, 0)
#36 C:\xampp\htdocs\dev\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase-&gt;_execute(Object(SmartyDevTemplate), NULL, 'hummingbirdlayo...', NULL, 0)
#37 C:\xampp\htdocs\dev\classes\Smarty\SmartyDev.php(40): Smarty_Internal_TemplateBase-&gt;fetch('catalog/listing...', NULL, 'hummingbirdlayo...', NULL)
#38 C:\xampp\htdocs\dev\classes\controller\FrontController.php(726): SmartyDev-&gt;fetch('catalog/listing...', NULL, 'hummingbirdlayo...')
#39 C:\xampp\htdocs\dev\classes\controller\FrontController.php(708): FrontControllerCore-&gt;smartyOutputContent('catalog/listing...')
#40 C:\xampp\htdocs\dev\tools\profiling\Controller.php(111): FrontControllerCore-&gt;display()
#41 C:\xampp\htdocs\dev\tools\profiling\Controller.php(88): Controller-&gt;displayProfiling()
#42 C:\xampp\htdocs\dev\classes\Dispatcher.php(492): Controller-&gt;run()
#43 C:\xampp\htdocs\dev\index.php(73): DispatcherCore-&gt;dispatch()
#44 {main}
  thrown in <b>C:\xampp\htdocs\dev\classes\Hook.php</b> on line <b>1095</b><br />
```

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.3

**Comment by Hlavtox** [comment]
Same error regarding `ps_supplierlist` after uninstalling this module.

**Comment by florine2623** [comment]
Hello @Hlavtox ,

I can't reproduce your issue.

I'm using develop branch, hummingbird v0.2.0, ps_brandlist v1.0.3.
I also uninstalled ps_supplierlist v1.0.6.

I check category pages on FO and on BO, I couldn't reproduce your issue.

https://github.com/user-attachments/assets/00e01460-a039-431a-aefb-71f1d203b42a

Am I missing something ?
Waiting for your feedback ^^

**Comment by Hlavtox** [comment]
@florine2623 Florine, you are missing something, but I don't know what. :-D There is some other magic that broke it for me. @maxime-aknin made a PR for it, maybe it's specific to PHP version?

**Comment by florine2623** [comment]
@Hlavtox yes I saw the PR, that's why I wanted to check the issue related ^^

For hummingbird theme, did you use the develop branch ? or the version included in PS develop version ?

**Comment by Hlavtox** [comment]
@florine2623 Hummingbird theme included in nightly build, develop branch, PHP 8.2 or 8.3 I think

**Comment by Hlavtox** [comment]
Ping @florine2623

**Comment by florine2623** [comment]
Hello @Hlavtox ,

Sorry I didn't see your ping.

I tried again. I installed a fresh install of 9.0.x with PHP 8.2 with theme hummingbird v0.2.0 included in the shop. 
I applied the theme, went on the FO in some categories pages with no error on front nor in console.
I checked the log, but nothing regarding the issue is displayed on it.

![Image](https://github.com/user-attachments/assets/cc361d67-32be-4a7c-bbf4-9c0c7d82508e)

I'm not sure where the issue is exactly.

**Comment by Hlavtox** [comment]
@florine2623 

- 9.0.x branch
- ps_supplierlist v1.0.6 installed
- When I delete themes/hummingbird/modules/ps_supplierlist, the problem is still there.
- When I enable force compilation and cache off, the problem disappears finally.

![Image](https://github.com/user-attachments/assets/318b2fc8-b32c-41f1-a7d9-a3ae8bca0b27)
