### ISSUE TITLE
Numeric value out of range

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#37338]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I had a strange case here, some orders was not created properly in the shop.
I found this in the logs

PHP Fatal error:  Uncaught PDOException: SQLSTATE[22003]: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range in '`domain`.`od`.`product_quantity` - `domain`.`od`.`product_quantity_refunded`' in /var/www/domain.se/classes/db/DbPDO.php:149
Stack trace:
#0 /var/www/domain.se/classes/db/DbPDO.php(149): PDO->query()
#1 /var/www/domain.se/classes/db/Db.php(377): DbPDOCore->_query()
#2 /var/www/domain.se/classes/db/Db.php(567): DbCore->query()
#3 /var/www/domain.se/src/Adapter/StockManager.php(175): DbCore->execute()
#4 /var/www/domain.se/src/Adapter/StockManager.php(104): PrestaShop\PrestaShop\Adapter\StockManager->updateReservedProductQuantity()
#5 /var/www/domain.se/classes/order/OrderHistory.php(433): PrestaShop\PrestaShop\Adapter\StockManager->updatePhysicalProductQuantity()
#6 /var/www/domain.se/classes/order/OrderHistory.php(603): OrderHistoryCore->changeIdOrderState()
#7 /var/www/domain.se/classes/webservice/WebserviceRequest.php(1671): OrderHistoryCore->addWs()
#8 /var/www/domain.se/classes/webservice/WebserviceRequest.php(1446): WebserviceRequestCore->saveEntityFromXml()
#9 /var/www/domain.se/classes/webservice/WebserviceRequest.php(582): WebserviceRequestCore->executeEntityPost()
#10 /var/www/domain.se/webservice/dispatcher.php(94): WebserviceRequestCore->fetch()
#11 {main}

and it seems to be due to some kind of misshap in the DB, this is and old shop, upgraded and has used lots of third party modules, so not sure how the data has been corrupted, but some orders seems to have had more refunds than ordered products

![Image](https://github.com/user-attachments/assets/4e7f93f9-c312-4b0c-a0c2-601ebd00402e)

and this cause the order creation process to crash since the column in the database for reserved_quantity in stock_available does not allow negative numbers.

### Expected behavior

The order should be completed properly. 
reserved quantity should perhaps be set to 0.

### Steps to reproduce

1. In the db, change data in one of the order details to have refunded value higher than ordered quantity.
2. create a new order of that product.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Prestaworks

**Comment by florine2623** [comment]
Hello @Prestaworks ,

I have reproduces your issue on PS 9.0.0 :

product_quantity_refunded is higher than product_quantity :
![Image](https://github.com/user-attachments/assets/062a2615-cb76-4e7a-98ab-818930e1563a)

When I try to order the product, I have an exception :
![Image](https://github.com/user-attachments/assets/4e89c8c1-e1f6-4bb8-9bef-28e35597d87a)

Although I don't have any error on my log.

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers ,

What do you think about this issue ?

**Comment by PrestaSafe** [comment]
hi, i've the same issue, i've modified the `updateReservedProductQuantity` of the `src/Adapter/StockManager.php` and it works. 

```php
/**
     * @param int $shopId
     * @param int $errorState
     * @param int $cancellationState
     * @param int|null $idProduct
     * @param int|null $idOrder
     *
     * @return bool
     */
    private function updateReservedProductQuantity($shopId, $errorState, $cancellationState, $idProduct = null, $idOrder = null)
    {
        $updateReservedQuantityQuery = '
        UPDATE {table_prefix}stock_available sa
        LEFT JOIN (
            SELECT 
                od.product_id,
                od.product_attribute_id,
                SUM(
                    GREATEST(0, 
                        CAST(od.product_quantity AS SIGNED) - CAST(od.product_quantity_refunded AS SIGNED)
                    )
                ) AS new_reserved_quantity
            FROM 
                {table_prefix}order_detail od
            INNER JOIN 
                {table_prefix}orders o ON od.id_order = o.id_order
            INNER JOIN 
                {table_prefix}order_state os ON os.id_order_state = o.current_state
            WHERE 
                o.id_shop = :shop_id
                AND os.shipped != 1 
                AND (
                    o.valid = 1 
                    OR (
                        os.id_order_state != :error_state 
                        AND os.id_order_state != :cancellation_state
                    )
                )
            GROUP BY 
                od.product_id, od.product_attribute_id
        ) calculated_quantity ON sa.id_product = calculated_quantity.product_id 
            AND sa.id_product_attribute = calculated_quantity.product_attribute_id
        SET 
            sa.reserved_quantity = IFNULL(calculated_quantity.new_reserved_quantity, 0)
        WHERE 
            sa.id_shop = :shop_id
    ';

        $strParams = [
            '{table_prefix}' => _DB_PREFIX_,
            ':shop_id' => (int) $shopId,
            ':error_state' => (int) $errorState,
            ':cancellation_state' => (int) $cancellationState,
        ];

        if ($idProduct) {
            $updateReservedQuantityQuery .= ' AND sa.id_product = :product_id';
            $strParams[':product_id'] = (int) $idProduct;
        }

        if ($idOrder) {
            $updateReservedQuantityQuery .= ' AND sa.id_product IN (SELECT product_id FROM {table_prefix}order_detail WHERE id_order = :order_id)';
            $strParams[':order_id'] = (int) $idOrder;
        }

        $updateReservedQuantityQuery = strtr($updateReservedQuantityQuery, $strParams);

        return Db::getInstance()->execute($updateReservedQuantityQuery);
    }
```

**Comment by nicohery** [comment]
I've already encountered this bug on a migration. I considered that it's not possible to refund more than what had been sold. So to my mind it had to remain as a constraint of integrity. I've patched with a simple request:
``UPDATE FROM `ps_order_detail` SET `product_quantity_refunded` = `product_quantity` WHERE `product_quantity_refunded` > `product_quantity` ``
Whatever the answer on integrity, we must find a solution to prevent or catch the exception.

**Comment by boo-code** [comment]
Answering @florine2623's ping from 2024, since this has an open fix that the issue does not mention.

The mechanism is an unsigned underflow rather than corrupt data reaching the wrong place. `product_quantity` and `product_quantity_refunded` are both UNSIGNED, so on an over-refunded line the subtraction wraps instead of going negative and MySQL aborts the whole statement with `BIGINT UNSIGNED value is out of range` — which is why one bad row stops an unrelated order from being created. It occurs in two places that compute the same sum:

- `src/Adapter/StockManager.php`, in the `UPDATE ... SET sa.reserved_quantity = (SELECT SUM(od.product_quantity - od.product_quantity_refunded) ...)`
- `src/Adapter/Product/Stock/Repository/StockAvailableRepository.php`, in the Doctrine equivalent — `addSelect('SUM(od.product_quantity - od.product_quantity_refunded) AS reserved_quantity')`

@PrestaSafe's #38345 fixed the first with `GREATEST(0, CAST(...))`, which is the right shape; it has been changes-requested with no follow-up since April 2025 and now conflicts. #41869 does the same clamp in both places, on `9.2.x`, with an integration test that reproduces the underflow rather than asserting the query text. That test passes on the PR head (1 test, 2 assertions), and the branch merges cleanly onto today's `9.2.x` (`git merge --no-commit --no-ff` → exit 0).

On the design question in the original report — *"reserved quantity should perhaps be set to 0"* — clamping per line rather than per product is the narrower reading: a line that has been refunded more than it was ordered reserves nothing, while the other lines of the same order keep reserving normally. Clamping the total instead would hide a genuine negative caused by several lines.

The `Waiting for dev` label looks like it can come off either way — the decision the ping asked for is the clamp, and it is implemented in both PRs.
